/**
 * API Route: Footers Management
 * Author: generated by Amazon Q
 * Created: 2024-01-20
 */

import { NextRequest, NextResponse } from 'next/server';
import { PrismaClient } from '@prisma/client';
import { verifyToken } from '@/lib/auth';

const prisma = new PrismaClient();

export const dynamic = 'force-dynamic';

// GET: لیست تمام فوترها
export async function GET(request: NextRequest) {
  try {
    const authHeader = request.headers.get('authorization');
    const token = authHeader?.replace('Bearer ', '');
    
    if (!token || !verifyToken(token)) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const footers = await prisma.footer.findMany({
      orderBy: { updatedAt: 'desc' },
    });

    return NextResponse.json({ 
      success: true,
      footers: footers.map(footer => ({
        ...footer,
        contactInfo: footer.contactInfo ? JSON.parse(footer.contactInfo) : null,
        columns: JSON.parse(footer.columns || '[]'),
        bottomBar: footer.bottomBar ? JSON.parse(footer.bottomBar) : null,
        style: footer.style ? JSON.parse(footer.style) : null
      }))
    });
  } catch (error) {
    console.error('Footers GET error:', error);
    return NextResponse.json({ 
      success: false,
      error: 'Internal server error' 
    }, { status: 500 });
  }
}

// POST: ایجاد فوتر جدید
export async function POST(request: NextRequest) {
  try {
    const authHeader = request.headers.get('authorization');
    const token = authHeader?.replace('Bearer ', '');
    
    if (!token || !verifyToken(token)) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const data = await request.json();

    // Validate required fields
    if (!data.language || !data.companyName) {
      return NextResponse.json({ 
        success: false,
        error: 'Language and company name are required' 
      }, { status: 400 });
    }

    // چک کردن اینکه فوتر برای این زبان وجود نداره
    const existingFooter = await prisma.footer.findUnique({
      where: { language: data.language }
    });

    if (existingFooter) {
      return NextResponse.json({ 
        success: false,
        error: `Footer for language "${data.language}" already exists` 
      }, { status: 400 });
    }

    const footer = await prisma.footer.create({
      data: {
        language: data.language,
        companyName: data.companyName,
        tagline: data.tagline || '',
        description: data.description || '',
        contactInfo: JSON.stringify(data.contactInfo || {}),
        columns: JSON.stringify(data.columns || []),
        bottomBar: JSON.stringify(data.bottomBar || {}),
        style: JSON.stringify(data.style || {}),
        isActive: data.isActive !== undefined ? data.isActive : true
      },
    });

    return NextResponse.json({ 
      success: true,
      footer: {
        ...footer,
        contactInfo: JSON.parse(footer.contactInfo || '{}'),
        columns: JSON.parse(footer.columns || '[]'),
        bottomBar: JSON.parse(footer.bottomBar || '{}'),
        style: JSON.parse(footer.style || '{}')
      }
    });
  } catch (error: any) {
    console.error('Footers POST error:', error);
    return NextResponse.json({ 
      success: false,
      error: error.message || 'Internal server error' 
    }, { status: 500 });
  }
}
