/**
 * Light theme visual enhancements - alternatives to dark gradients
 * Author: generated by Amazon Q
 * Created: 2024-01-15
 */

export const lightThemeEnhancements = {
  // Subtle patterns and textures for light theme
  patterns: {
    dots: 'bg-[radial-gradient(circle_at_1px_1px,rgba(0,0,0,0.05)_1px,transparent_0)]',
    grid: 'bg-[linear-gradient(rgba(0,0,0,0.03)_1px,transparent_1px),linear-gradient(90deg,rgba(0,0,0,0.03)_1px,transparent_1px)]',
    diagonal: 'bg-[linear-gradient(45deg,rgba(0,0,0,0.02)_25%,transparent_25%,transparent_75%,rgba(0,0,0,0.02)_75%)]',
  },
  
  // Colored borders and shadows for visual interest
  accents: {
    violet: 'border-l-4 border-violet-200 bg-violet-50/50',
    cyan: 'border-l-4 border-cyan-200 bg-cyan-50/50', 
    indigo: 'border-l-4 border-indigo-200 bg-indigo-50/50',
    emerald: 'border-l-4 border-emerald-200 bg-emerald-50/50',
  },
  
  // Soft shadows for depth
  shadows: {
    soft: 'shadow-sm shadow-slate-200/50',
    medium: 'shadow-md shadow-slate-200/30',
    large: 'shadow-lg shadow-slate-200/20',
  },
  
  // Light theme specific backgrounds
  backgrounds: {
    feature: 'bg-gradient-to-br from-slate-50 to-slate-100/50',
    hero: 'bg-gradient-to-br from-violet-50/80 via-white to-cyan-50/80',
    section: 'bg-gradient-to-b from-slate-50/50 to-white',
  }
} as const;