/**
 * App Builder Marketing Page
 * Author: generated by Amazon Q
 * Created: 2024-01-15
 */

'use client';

import { AppBuilderHero } from '@/components/app-builder/AppBuilderHero';
import { BuilderTabs } from '@/components/app-builder/BuilderTabs';
import { CTASection } from '@/components/form-builder/CTASection';
import { useTranslation } from '@/hooks/useTranslation';





export default function AppBuilderPage() {
  const { t } = useTranslation();
  return (
    <div className="min-h-screen bg-slate-50 dark:bg-slate-900">
      <div className="py-20 text-center bg-gradient-to-br from-slate-50 via-white to-slate-100/50 dark:bg-slate-900">
        <div className="max-w-4xl mx-auto px-6">
          <h1 className="text-4xl md:text-5xl font-bold text-slate-900 dark:text-white mb-4">
            {t('pages.appBuilder.title')}
          </h1>
          <p className="text-xl text-slate-600 dark:text-slate-300 mb-6">
            {t('pages.appBuilder.subtitle')}
          </p>
          <p className="text-lg text-slate-500 dark:text-slate-400">
            {t('pages.appBuilder.description')}
          </p>
        </div>
      </div>
      <AppBuilderHero />
      
      <div className="h-px bg-gradient-to-r from-transparent via-slate-900/20 dark:via-white/20 to-transparent" />
      
      {/* Why Section */}
      <section className="bg-white dark:bg-slate-900 text-slate-900 dark:text-white py-16 relative">
        <div className="absolute inset-0 bg-[radial-gradient(circle_at_1px_1px,rgba(0,0,0,0.03)_1px,transparent_0)] dark:bg-none" style={{backgroundSize: '24px 24px'}} />
        <div className="max-w-7xl mx-auto px-6">
          <div className="grid lg:grid-cols-[260px_1fr] gap-10">
            <aside className="hidden lg:block sticky top-6 self-start">
              <div className="rounded-2xl bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 p-4">
                <div className="text-xs uppercase tracking-wide text-slate-400 mb-3">{t('components.appBuilder.specHighlights')}</div>
                <ul className="space-y-2 text-sm">
                  <li>• {t('components.appBuilder.buildInDays')}</li>
                  <li>• {t('components.appBuilder.pagesWorkflows')}</li>
                  <li>• {t('components.appBuilder.rolesPermissions')}</li>
                  <li>• {t('components.appBuilder.integrations')}</li>
                  <li>• {t('components.appBuilder.security')}</li>
                </ul>
              </div>
            </aside>
            
            <div>
              <h2 className="text-3xl md:text-4xl font-bold mb-4">
                {t('components.appBuilder.whyAppBuilder')}
              </h2>
              <p className="text-slate-600 dark:text-slate-300 mb-8 leading-relaxed max-w-3xl">
                {t('components.appBuilder.whyDescription')}
              </p>
              
              <div className="grid md:grid-cols-3 gap-6">
                {[
                  { title: t('components.appBuilder.speedToValue'), description: t('components.appBuilder.speedDescription') },
                  { title: t('components.appBuilder.businessFit'), description: t('components.appBuilder.businessDescription') },
                  { title: t('components.appBuilder.unifiedData'), description: t('components.appBuilder.dataDescription') }
                ].map((item, index) => (
                  <div 
                    key={index}
                    className="rounded-2xl bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 p-6 hover:-translate-y-1 transition-transform shadow-sm shadow-slate-200/30 dark:shadow-none"
                  >
                    <h3 className="font-semibold mb-3">{item.title}</h3>
                    <p className="text-sm text-slate-600 dark:text-slate-300">{item.description}</p>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Workspaces Section */}
      <section className="bg-slate-50 dark:bg-slate-800 text-slate-900 dark:text-white py-16 relative">
        <div className="absolute inset-0 bg-[radial-gradient(circle_at_1px_1px,rgba(99,102,241,0.06)_1px,transparent_0)] dark:bg-none" style={{backgroundSize: '20px 20px'}} />
        <div className="max-w-7xl mx-auto px-6">
          <div className="grid lg:grid-cols-2 gap-12 items-center">
            <div className="order-2 lg:order-1">
              <div className="aspect-[4/3] bg-white dark:bg-slate-700 rounded-3xl border border-slate-200 dark:border-slate-600 flex items-center justify-center shadow-lg shadow-indigo-200/20 dark:shadow-none">
                <div className="text-center text-slate-600 dark:text-slate-300">
                  <div className="text-4xl mb-2">🏢</div>
                  <p className="text-sm">Separate workspaces for internal, partners, and customers</p>
                </div>
              </div>
            </div>
            
            <div className="order-1 lg:order-2">
              <h2 className="text-3xl md:text-4xl font-bold mb-4">
                {t('components.appBuilder.workspaces')}
              </h2>
              <p className="text-slate-600 dark:text-slate-300 mb-6 leading-relaxed">
                {t('components.appBuilder.workspacesDescription')}
              </p>
              
              <div className="grid sm:grid-cols-2 gap-4">
                {[t('components.appBuilder.roleBasedAccess'), t('components.appBuilder.customDashboards'), t('components.appBuilder.externalOnboarding'), t('components.appBuilder.workspaceThemes')].map((feature, index) => (
                  <div 
                    key={index}
                    className="p-4 rounded-xl bg-white dark:bg-slate-700 border border-slate-200 dark:border-slate-600 hover:-translate-y-1 transition-transform shadow-sm shadow-slate-200/30 dark:shadow-none"
                  >
                    <p className="text-sm">{feature}</p>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      </section>

      <BuilderTabs />

      {/* Use Cases */}
      <section className="bg-white dark:bg-slate-900 text-slate-900 dark:text-white py-16 relative">
        <div className="absolute inset-0 bg-[radial-gradient(circle_at_1px_1px,rgba(16,185,129,0.06)_1px,transparent_0)] dark:bg-none" style={{backgroundSize: '20px 20px'}} />
        <div className="max-w-7xl mx-auto px-6">
          <div className="text-center mb-12">
            <h2 className="text-3xl md:text-4xl font-bold mb-4">{t('components.appBuilder.useCases')}</h2>
            <p className="text-slate-600 dark:text-slate-300 max-w-3xl mx-auto">
              {t('components.appBuilder.useCasesDescription')}
            </p>
          </div>
          
          <div className="grid md:grid-cols-5 gap-4 mb-12">
            {['crm', 'ticketing', 'analytics', 'portals', 'inventory'].map((useCase, index) => (
              <div 
                key={index}
                className="rounded-xl bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 p-6 hover:-translate-y-1 transition-transform shadow-sm shadow-slate-200/30 dark:shadow-none"
              >
                <h3 className="text-lg font-semibold mb-2">{t(`components.appBuilder.useCaseItems.${useCase}`)}</h3>
                <p className="text-sm text-slate-600 dark:text-slate-300">{t(`components.appBuilder.useCaseItems.${useCase}Desc`)}</p>
              </div>
            ))}
          </div>

          {/* Testimonials */}
          <div className="grid md:grid-cols-3 gap-6">
            {['logistics', 'finance', 'healthcare'].map((testimonial, index) => (
              <blockquote 
                key={index}
                className="rounded-xl bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 p-6 shadow-sm shadow-slate-200/30 dark:shadow-none"
              >
                <p className="text-sm text-slate-700 dark:text-slate-200 mb-4">&ldquo;{t(`components.appBuilder.testimonials.${testimonial}`)}&rdquo;</p>
                <div className="text-xs text-slate-500 dark:text-slate-400">{t(`components.appBuilder.testimonials.${testimonial}Author`)}</div>
              </blockquote>
            ))}
          </div>
        </div>
      </section>

      <CTASection />
    </div>
  );
}