import { SECTION_CATEGORIES, SectionTemplate } from '../section-registry.types';

/**
 * home-cover / home-innovation — scroll-linked "parallax" showcase pair
 * inspired by the Mitsui & Co. homepage's pinned-cover + sticky-title-card-flow
 * pattern. See .kiro/specs/home-cover-innovation-sections for the full spec.
 */
export const HOME_SHOWCASE_TEMPLATES: SectionTemplate[] = [
  {
    id: 'home-cover-default',
    name: 'Home Cover (Video Hero)',
    type: 'home-cover',
    category: SECTION_CATEGORIES.HEADERS,
    description:
      'Full-viewport video/image cover with staged text reveal and a configurable parallax or pin-reveal scroll release.',
    icon: '🌊',
    defaultData: {
      id: '',
      type: 'home-cover',
      order: 0,
      data: {
        mediaType: 'video',
        videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
        imageUrl: 'https://picsum.photos/seed/home-cover-fallback/1600/900',
        posterImageDesktop: 'https://picsum.photos/seed/home-cover-desktop/1600/900',
        posterImageMobile: 'https://picsum.photos/seed/home-cover-mobile/900/1600',
        videoAutoplay: true,
        videoLoop: true,
        videoMuted: true,
        overlayColor: '#000000',
        overlayOpacity: 0.35,
        tagline: 'Every idea, one connected direction.',
        body: 'We bring people, ideas, and opportunity together —\nturning ambitious plans into work you can see.',
        cta: { text: 'Discover more', href: '#', enabled: true },
        opening: {
          enabled: true,
          logoUrl: '/media/home-showcase/sample-logo.svg',
          logoAlt: 'Brand wordmark',
          backgroundColor: '#fafafa',
          durationMs: 1200,
        },
        theme: 'dark',
        showScrollCue: true,
        scrollEffect: 'parallax',
        parallaxIntensity: 30,
        pinDistanceVh: 80,
        minHeight: '100vh',
      },
      style: { backgroundColor: '', textColor: 'text-white', padding: 'py-0' },
    },
    configSchema: {},
  },
  {
    id: 'home-innovation-default',
    name: 'Home Innovation (Showcase Cards)',
    type: 'home-innovation',
    category: SECTION_CATEGORIES.CONTENT,
    description:
      'Sticky-title showcase of media cards in staggered, lightly parallaxed columns, with an optional world-map location highlight.',
    icon: '🧭',
    defaultData: {
      id: '',
      type: 'home-innovation',
      order: 1,
      data: {
        eyebrow: 'What we do',
        headline: '360° of what makes us different.',
        supportingCopy: 'A closer look at the people, projects, and ideas behind the work.',
        sideTitle: 'Built around real outcomes.',
        sideDescription: 'Every story below is a different angle on the same goal: turning complexity into clarity.',
        columnCount: 3,
        parallaxIntensity: 20,
        cta: { text: 'View all stories', href: '#', enabled: true },
        theme: 'dark',
        locationMap: {
          enabled: true,
          mapImageUrl: '/media/home-showcase/world-map.svg',
          pinRevealMode: undefined,
        },
        cards: [
          {
            id: 'home-innovation-card-1',
            category: 'Innovation',
            title: 'Reimagining how teams collaborate',
            format: 'horizontal',
            mediaType: 'video',
            mediaUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
            href: '#',
            column: 0,
            locationTag: { label: 'USA', x: 22, y: 40, thumbnailUrl: 'https://picsum.photos/seed/loc-usa/160/160' },
          },
          {
            id: 'home-innovation-card-2',
            category: 'Wellness',
            title: 'Designing for people first',
            format: 'vertical',
            mediaType: 'image',
            mediaUrl: 'https://picsum.photos/seed/home-innovation-2/900/1200',
            href: '#',
            column: 1,
            locationTag: {
              label: 'Morocco',
              x: 47,
              y: 46,
              thumbnailUrl: 'https://picsum.photos/seed/loc-morocco/160/160',
            },
          },
          {
            id: 'home-innovation-card-3',
            category: 'Sustainability',
            title: 'Fuelling a cleaner future',
            format: 'horizontal',
            mediaType: 'image',
            mediaUrl: 'https://picsum.photos/seed/home-innovation-3/1200/900',
            href: '#',
            column: 2,
            locationTag: {
              label: 'Denmark',
              x: 51,
              y: 30,
              thumbnailUrl: 'https://picsum.photos/seed/loc-denmark/160/160',
            },
          },
          {
            id: 'home-innovation-card-4',
            category: 'Technology',
            title: 'From data to decisions',
            format: 'vertical',
            mediaType: 'image',
            mediaUrl: 'https://picsum.photos/seed/home-innovation-4/900/1200',
            href: '#',
            column: 0,
            locationTag: {
              label: 'Australia',
              x: 85,
              y: 72,
              thumbnailUrl: 'https://picsum.photos/seed/loc-australia/160/160',
            },
          },
          {
            id: 'home-innovation-card-5',
            category: 'Community',
            title: 'Building where it matters most',
            format: 'horizontal',
            mediaType: 'video',
            mediaUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4',
            href: '#',
            column: 1,
            locationTag: {
              label: 'Malaysia',
              x: 76,
              y: 52,
              thumbnailUrl: 'https://picsum.photos/seed/loc-malaysia/160/160',
            },
          },
        ],
      },
      style: { backgroundColor: 'bg-[#0a0a0a]', textColor: 'text-white', padding: 'py-0' },
    },
    configSchema: {},
  },
];
