/**
 * PLATFORM_CAPABILITIES_TEMPLATES
 * Grouped by visual similarity and kept behavior-compatible with legacy registry order.
 */

import {
  SECTION_CATEGORIES,
  type SectionTemplate,
} from '../section-registry.types';

export const PLATFORM_CAPABILITIES_TEMPLATES: SectionTemplate[] = [
  {
    id: 'platform-capabilities',
    name: 'Platform Capabilities',
    type: 'platform-capabilities',
    category: SECTION_CATEGORIES.CONTENT,
    description:
      'Header + module dividers + alternating capability feature rows',
    icon: '🧩',
    defaultData: {
      id: '',
      type: 'platform-capabilities',
      order: 0,
      data: {
        eyebrowText: 'Platform capabilities',
        title: 'Every capability your clients need -',
        titleHighlight: 'configured, not built',
        description:
          "Every feature in IVAFLOW is designed to be configured visually by your team - no development required. Here's what you can deliver to any client, in any industry.",
        accentColor: '#4F7FFF',
        accentColor2: '#7B5CFF',
        modules: [
          {
            title: 'Form Builder',
            emoji: '📝',
            dotColor: '#4F7FFF',
            features: [
              {
                moduleTag: 'Form Builder · Master-Detail',
                title: 'Nested forms that mirror how your data actually works',
                body: 'Build Master-Detail relationships directly inside any form. A single parent record - like an invoice or project - can hold an unlimited, dynamic table of child records, each with its own fields, validations, and calculations. No workarounds, no separate screens.',
                badges: [
                  { text: 'Unlimited child rows', variant: 'blue' },
                  { text: 'Per-row field validation', variant: 'blue' },
                  { text: 'Inline calculations', variant: 'purple' },
                  { text: 'Nested form-in-form', variant: 'purple' },
                  { text: 'Auto-totals & aggregations', variant: 'green' },
                ],
                theme: 'blue',
                flip: false,
                visualBadge: 'Master-Detail form',
                visualIcon: '🗂️',
                visualLabel: 'Replace with Master-Detail form screenshot',
              },
              {
                moduleTag: 'Form Builder · Smart Fields',
                title: 'Fields that think - show, hide, and react in real time',
                body: 'Define exactly when each field appears, becomes required, or gets disabled - all based on what the user has already entered or system variables. Build forms that feel tailored without writing a single condition manually. The logic engine handles it all visually.',
                badges: [
                  { text: 'Show / hide conditions', variant: 'purple' },
                  { text: 'Required / optional toggle', variant: 'purple' },
                  { text: 'Enable / disable by value', variant: 'blue' },
                  { text: 'Multi-field dependency chains', variant: 'green' },
                  { text: 'System variable binding', variant: 'amber' },
                ],
                theme: 'purple',
                flip: true,
                visualBadge: 'Conditional logic builder',
                visualIcon: '🔀',
                visualLabel: 'Replace with conditional field logic screenshot',
              },
              {
                moduleTag: 'Form Builder · Data Connection',
                title: 'Fields connected live to any data source',
                body: 'Any field in any form can pull its data from an external system in real time - a database, a REST API, another form in IVAFLOW, or any connected service. Dropdown lists that populate from your HR system. Customer names that auto-fill from your CRM. No copy-paste, no stale data.',
                badges: [
                  { text: 'REST API data sources', variant: 'green' },
                  { text: 'Database direct binding', variant: 'green' },
                  { text: 'Cross-form data pull', variant: 'blue' },
                  { text: 'One-way & two-way sync', variant: 'blue' },
                  { text: 'Live dropdown population', variant: 'purple' },
                ],
                theme: 'green',
                flip: false,
                visualBadge: 'Data source connector',
                visualIcon: '🔌',
                visualLabel:
                  'Replace with data binding configuration screenshot',
              },
              {
                moduleTag: 'Form Builder · Calculated Fields',
                title: 'Let the form do the math - automatically',
                body: 'Define calculated fields that update in real time as users fill in the form. Add totals, apply discount formulas, compute durations, or run complex business logic - all configured visually without any scripting. The result is always accurate, always instant.',
                badges: [
                  { text: 'Real-time calculations', variant: 'amber' },
                  { text: 'Mathematical & logical formulas', variant: 'amber' },
                  { text: 'Date & duration computing', variant: 'blue' },
                  { text: 'Cross-field formula chains', variant: 'green' },
                  { text: 'Currency & numeric formatting', variant: 'purple' },
                ],
                theme: 'amber',
                flip: true,
                visualBadge: 'Formula field builder',
                visualIcon: '🧮',
                visualLabel: 'Replace with calculated field screenshot',
              },
            ],
          },
          {
            title: 'Workflow Orchestrator',
            emoji: '⚡',
            dotColor: '#7B5CFF',
            paddingTop: 40,
            features: [
              {
                moduleTag: 'Workflow · Process Triggers',
                title:
                  'Every process starts exactly when - and how - it should',
                body: "Workflows don't always start the same way. IVAFLOW supports every type of trigger your clients need - a user clicks a button, a scheduled time arrives, an external system fires a webhook, or a condition in another process is met. One platform, every scenario.",
                badges: [
                  { text: 'Manual user-initiated start', variant: 'purple' },
                  {
                    text: 'Scheduled & time-based triggers',
                    variant: 'purple',
                  },
                  {
                    text: 'Event-driven from other processes',
                    variant: 'blue',
                  },
                  { text: 'Incoming webhook / API call', variant: 'green' },
                  { text: 'Document condition triggers', variant: 'amber' },
                ],
                theme: 'purple',
                flip: false,
                visualBadge: 'Process trigger configuration',
                visualIcon: '▶️',
                visualLabel: 'Replace with trigger setup screenshot',
              },
              {
                moduleTag: 'Workflow · Smart Assignment',
                title:
                  'The right person gets the task - every time, automatically',
                body: "Forget manual task routing. IVAFLOW assigns each process stage to the right person dynamically - based on the data in the form, the org chart position, who started the process, or rules you define. When your client's organization changes, the routing updates itself.",
                badges: [
                  { text: 'Org chart position-based routing', variant: 'blue' },
                  { text: 'Form data-driven assignment', variant: 'blue' },
                  {
                    text: 'Previous stage executor carry-over',
                    variant: 'purple',
                  },
                  {
                    text: 'Parallel multi-person assignment',
                    variant: 'green',
                  },
                  { text: 'Runtime task reallocation', variant: 'amber' },
                ],
                theme: 'blue',
                flip: true,
                visualBadge: 'Dynamic executor assignment',
                visualIcon: '👤',
                visualLabel: 'Replace with executor assignment screenshot',
              },
              {
                moduleTag: 'Workflow · Supervision & Control',
                title: 'Every process has an owner who can see everything',
                body: 'Assign a process manager to any workflow - someone who monitors every live instance, can intervene at any stage, and receives alerts when things go off track. No more lost requests, no more "I did not know about it" moments for your clients operations teams.',
                badges: [
                  { text: 'Designated process manager', variant: 'green' },
                  { text: 'Live instance monitoring', variant: 'green' },
                  { text: 'Stage-level supervisor override', variant: 'blue' },
                  { text: 'Audit trail per process step', variant: 'purple' },
                  { text: 'Alert on deviation or delay', variant: 'amber' },
                ],
                theme: 'green',
                flip: false,
                visualBadge: 'Process supervision panel',
                visualIcon: '👁️',
                visualLabel: 'Replace with process monitoring screenshot',
              },
              {
                moduleTag: 'Workflow · Approval Logic',
                title:
                  'Group decisions, consensus voting, and sequential sign-offs',
                body: 'Some decisions need more than one person. Define parallel approval stages where multiple reviewers vote simultaneously - with the outcome determined by majority, unanimous agreement, or a custom threshold. Or run sequential sign-offs where each approver passes the baton to the next. Both patterns, one designer.',
                badges: [
                  { text: 'Parallel multi-approver voting', variant: 'coral' },
                  { text: 'Majority / unanimous thresholds', variant: 'coral' },
                  { text: 'Sequential linear approvals', variant: 'purple' },
                  { text: 'Conditional next approver logic', variant: 'blue' },
                  {
                    text: 'Mixed parallel + sequential flows',
                    variant: 'green',
                  },
                ],
                theme: 'coral',
                flip: true,
                visualBadge: 'Approval stage designer',
                visualIcon: '🗳️',
                visualLabel: 'Replace with multi-approval stage screenshot',
              },
            ],
          },
          {
            title: 'Reports & Analytics',
            emoji: '📊',
            dotColor: '#00D4A8',
            paddingTop: 40,
            features: [
              {
                moduleTag: 'Analytics · KPI Engine',
                title: 'Define what matters - and watch it in real time',
                body: 'Build KPIs with custom formulas and attach them to live dashboards that update automatically. Set alert thresholds so the right people are notified the moment a number crosses a boundary - before a problem becomes a crisis. Color-coded, visual, and always current.',
                badges: [
                  { text: 'Custom KPI formula builder', variant: 'green' },
                  { text: 'Color-coded threshold alerts', variant: 'green' },
                  { text: 'Live real-time refresh', variant: 'blue' },
                  { text: 'Goal progress tracking', variant: 'purple' },
                  { text: 'Multi-level alert notifications', variant: 'amber' },
                ],
                theme: 'green',
                flip: false,
                visualBadge: 'KPI dashboard',
                visualIcon: '📈',
                visualLabel: 'Replace with KPI dashboard screenshot',
              },
              {
                moduleTag: 'Analytics · Data Sources',
                title: 'One dashboard. Data from everywhere.',
                body: 'Connect your dashboards to any data source - IVAFLOW process data, external databases, REST APIs, Excel files, or cloud systems via JDBC/ODBC. Build reports that bring together numbers from across the entire organization onto a single screen, without any data migration.',
                badges: [
                  { text: 'REST API & webhook sources', variant: 'blue' },
                  { text: 'Database direct connection', variant: 'blue' },
                  { text: 'Excel & CSV import', variant: 'green' },
                  { text: 'Cross-process data blending', variant: 'purple' },
                  { text: 'JDBC / ODBC cloud connectivity', variant: 'amber' },
                ],
                theme: 'blue',
                flip: true,
                visualBadge: 'Data source connector',
                visualIcon: '🔗',
                visualLabel: 'Replace with data source setup screenshot',
              },
              {
                moduleTag: 'Analytics · Interactive Reports',
                title: 'Click any number - and go deeper instantly',
                body: 'Dashboards in IVAFLOW are not static pictures of data - they are interactive. Click any chart to drill into the underlying records. Apply dynamic filters and watch every connected chart update instantly. Give managers and executives the power to investigate without waiting for a report to be rebuilt.',
                badges: [
                  { text: 'Drill-down to record level', variant: 'purple' },
                  { text: 'Cross-chart dynamic filtering', variant: 'purple' },
                  { text: 'Date, text & value filter layers', variant: 'blue' },
                  { text: 'Hover tooltips & detail views', variant: 'green' },
                  { text: 'Export to PDF & Excel', variant: 'amber' },
                ],
                theme: 'purple',
                flip: false,
                visualBadge: 'Interactive dashboard',
                visualIcon: '🔍',
                visualLabel: 'Replace with drill-down dashboard screenshot',
              },
            ],
          },
          {
            title: 'Automation Engine',
            emoji: '🤖',
            dotColor: '#7B5CFF',
            paddingTop: 40,
            features: [
              {
                moduleTag: 'Automation · Visual Builder',
                title: 'Build automation flows like drawing a diagram',
                body: "IVAFLOW's node-based automation designer lets business analysts map out complex multi-step automation flows visually - connecting triggers, conditions, actions, and API calls by dragging nodes onto a canvas. No scripting knowledge needed. What you see is exactly what runs.",
                badges: [
                  { text: 'Visual node-based designer', variant: 'purple' },
                  {
                    text: 'Parallel & sequential execution',
                    variant: 'purple',
                  },
                  { text: 'Condition branching nodes', variant: 'blue' },
                  { text: 'Error handling & fallback paths', variant: 'green' },
                  { text: 'Live test & debug mode', variant: 'amber' },
                ],
                theme: 'purple',
                flip: true,
                visualBadge: 'Automation flow designer',
                visualIcon: '⚙️',
                visualLabel: 'Replace with automation node designer screenshot',
              },
              {
                moduleTag: 'Automation · AI Integration',
                title: 'Connect any process to AI - and let it decide',
                body: 'Route process data to any AI model - online or on-premise - and use the response to drive the next step automatically. Classify complaints, detect sentiment, summarize documents, or chain multiple AI models in sequence. IVAFLOW makes AI a working part of operations, not just a demo feature.',
                badges: [
                  {
                    text: 'Online & offline AI model support',
                    variant: 'coral',
                  },
                  { text: 'Auto-classification & routing', variant: 'coral' },
                  { text: 'Multi-model chaining', variant: 'purple' },
                  { text: 'Sentiment & intent detection', variant: 'blue' },
                  { text: 'AI response as workflow trigger', variant: 'green' },
                ],
                theme: 'coral',
                flip: false,
                visualBadge: 'AI agent configuration',
                visualIcon: '🧠',
                visualLabel: 'Replace with AI integration flow screenshot',
              },
            ],
          },
          {
            title: 'SLA Management',
            emoji: '⏱️',
            dotColor: '#F59E0B',
            paddingTop: 40,
            features: [
              {
                moduleTag: 'SLA · Deadline Intelligence',
                title: 'Deadlines that chase people - so you do not have to',
                body: 'Set a time standard for every task and let IVAFLOW handle the follow-up. As deadlines approach, the system sends multi-level alerts - first to the assignee, then their manager, then leadership - escalating automatically until action is taken. Nothing falls through the cracks.',
                badges: [
                  { text: 'Per-task SLA definition', variant: 'amber' },
                  { text: '3-level escalation alerts', variant: 'amber' },
                  { text: 'Overdue auto-detection', variant: 'coral' },
                  { text: 'Corrective workflow activation', variant: 'blue' },
                  { text: 'SLA success rate reporting', variant: 'green' },
                ],
                theme: 'amber',
                flip: true,
                visualBadge: 'SLA monitoring panel',
                visualIcon: '🚨',
                visualLabel: 'Replace with SLA escalation timeline screenshot',
              },
              {
                moduleTag: 'SLA · Performance Analytics',
                title: 'Understand where time is being lost - and fix it',
                body: "Go beyond 'on time or late.' IVAFLOW's SLA analytics show success rates by process, team, and time period - alongside average handling times and the most common causes of delay. Give operations managers the data they need to make informed decisions about staffing, routing, and process design.",
                badges: [
                  { text: 'SLA success & failure matrix', variant: 'blue' },
                  { text: 'Average handling time (AHT)', variant: 'blue' },
                  { text: 'Bottleneck identification', variant: 'purple' },
                  {
                    text: 'Team & stage performance breakdown',
                    variant: 'green',
                  },
                  { text: 'Top delay root cause analysis', variant: 'amber' },
                ],
                theme: 'blue',
                flip: false,
                visualBadge: 'SLA analytics report',
                visualIcon: '📉',
                visualLabel: 'Replace with SLA analytics dashboard screenshot',
              },
            ],
          },
          {
            title: 'Integration Hub',
            emoji: '🔗',
            dotColor: '#00D4A8',
            paddingTop: 40,
            features: [
              {
                moduleTag: 'Integration · API Connections',
                title: 'Connect to any system - without writing a single line',
                body: "IVAFLOW's visual API connector lets your team link any external system to any process - configuring endpoints, headers, request bodies, and response mappings through a clean interface. Connect CRM, ERP, SMS gateways, and legacy platforms without needing a developer on the call.",
                badges: [
                  { text: 'Visual REST API builder', variant: 'green' },
                  {
                    text: 'Request & response field mapping',
                    variant: 'green',
                  },
                  { text: 'Webhook receive & send', variant: 'blue' },
                  { text: 'SSO & directory integration', variant: 'blue' },
                  { text: 'Auth: Bearer, OAuth, API key', variant: 'purple' },
                ],
                theme: 'green',
                flip: true,
                visualBadge: 'API connector interface',
                visualIcon: '🛰️',
                visualLabel:
                  'Replace with API connector configuration screenshot',
              },
              {
                moduleTag: 'Integration · Location & GIS',
                title:
                  'Add location awareness to any process - anywhere in the world',
                body: 'For clients in logistics, municipal services, field operations, or any location-dependent sector - IVAFLOW brings real-time geographic data directly into process workflows. Track assets, trigger steps based on location, and build spatial dashboards that show operations on a live map.',
                badges: [
                  {
                    text: 'Real-time asset & vehicle tracking',
                    variant: 'coral',
                  },
                  { text: 'Geofence-based process triggers', variant: 'coral' },
                  { text: 'Location fields in forms', variant: 'blue' },
                  { text: 'IoT sensor data integration', variant: 'green' },
                  { text: 'Spatial reporting & heatmaps', variant: 'amber' },
                ],
                theme: 'coral',
                flip: false,
                visualBadge: 'GIS integration map',
                visualIcon: '🗺️',
                visualLabel: 'Replace with GIS map integration screenshot',
              },
            ],
          },
        ],
      },
      style: {
        backgroundColor: 'bg-[#07080A]',
        textColor: 'text-white',
        padding: 'py-0',
      },
    },
    configSchema: {},
  },
];
