/**
 * Builder Page API
 * Author: generated by Amazon Q
 * Created: 2024-01-15
 */

import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';
import { verifyToken } from '@/lib/auth';

// GET /api/admin/pages/[id]/builder - Get page for builder
export async function GET(
  request: NextRequest,
  { params }: { params: { id: string } }
) {
  try {
    const authHeader = request.headers.get('authorization');
    const token = authHeader?.replace('Bearer ', '');
    
    if (!token || !verifyToken(token)) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const page = await prisma.page.findUnique({
      where: { id: params.id },
    });

    if (!page) {
      return NextResponse.json({ error: 'Page not found' }, { status: 404 });
    }

    // Parse builder data or create default sections
    let builderData = [];
    if (page.builderData) {
      try {
        const parsed = JSON.parse(page.builderData);
        builderData = parsed.sections || parsed || [];
      } catch (error) {
        console.error('Failed to parse builder data:', error);
      }
    }

    const pageData = {
      id: page.id,
      title: page.title,
      slug: page.slug,
      status: page.status,
      language: page.language,
      builderData,
      isBuilderPage: page.isBuilderPage,
      builderVersion: page.builderVersion,
    };

    return NextResponse.json({ page: pageData });
  } catch (error) {
    console.error('Builder page GET error:', error);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}

// PUT /api/admin/pages/[id]/builder - Save builder page
export async function PUT(
  request: NextRequest,
  { params }: { params: { id: string } }
) {
  try {
    const authHeader = request.headers.get('authorization');
    const token = authHeader?.replace('Bearer ', '');
    
    if (!token || !verifyToken(token)) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const { builderData, isBuilderPage, builderVersion } = await request.json();
    
    const page = await prisma.page.update({
      where: { id: params.id },
      data: {
        builderData: JSON.stringify({ sections: builderData }),
        isBuilderPage: isBuilderPage || true,
        builderVersion: builderVersion || '1.0',
        updatedAt: new Date(),
      },
    });

    return NextResponse.json({ 
      success: true,
      page: {
        id: page.id,
        title: page.title,
        isBuilderPage: page.isBuilderPage,
        builderVersion: page.builderVersion,
      }
    });
  } catch (error) {
    console.error('Builder page PUT error:', error);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}