/**
 * Language-specific Layout
 * Author: generated by Amazon Q
 * Created: 2024-01-15
 */

import { Inter } from 'next/font/google';
import localFont from 'next/font/local';
import { ModernNavbar } from '@/components/ModernNavbar';
import { Footer } from '@/components/Footer';
import { LanguageProvider } from '@/lib/i18n/context';
import { supportedLanguages, languages, SupportedLanguage } from '@/lib/i18n/config';
import { notFound } from 'next/navigation';

const inter = Inter({ subsets: ['latin'] });

const yekanBakh = localFont({
  src: [
    { path: '../../fonts/yekan bakh/woff2/YekanBakhFaNum-Thin.woff2',       weight: '100', style: 'normal' },
    { path: '../../fonts/yekan bakh/woff2/YekanBakhFaNum-Light.woff2',      weight: '300', style: 'normal' },
    { path: '../../fonts/yekan bakh/woff2/YekanBakhFaNum-Regular.woff2',    weight: '400', style: 'normal' },
    { path: '../../fonts/yekan bakh/woff2/YekanBakhFaNum-SemiBold.woff2',   weight: '600', style: 'normal' },
    { path: '../../fonts/yekan bakh/woff2/YekanBakhFaNum-Bold.woff2',       weight: '700', style: 'normal' },
    { path: '../../fonts/yekan bakh/woff2/YekanBakhFaNum-ExtraBold.woff2',  weight: '800', style: 'normal' },
    { path: '../../fonts/yekan bakh/woff2/YekanBakhFaNum-Black.woff2',      weight: '900', style: 'normal' },
    { path: '../../fonts/yekan bakh/woff2/YekanBakhFaNum-ExtraBlack.woff2', weight: '950', style: 'normal' },
  ],
  display: 'swap',
});

interface LangLayoutProps {
  children: React.ReactNode;
  params: { lang: string };
}

export async function generateStaticParams() {
  return supportedLanguages.map((lang) => ({ lang }));
}

export default function LangLayout({ children, params }: LangLayoutProps) {
  const lang = params.lang as SupportedLanguage;
  
  if (!supportedLanguages.includes(lang)) {
    notFound();
  }

  const currentLang = languages[lang];

  const fontClass = currentLang.dir === 'rtl' ? yekanBakh.className : inter.className;

  return (
    <html lang={lang} dir={currentLang.dir} suppressHydrationWarning>
      <body className={fontClass}>
        <LanguageProvider initialLanguage={lang}>
          <div className="min-h-screen flex flex-col">
            <ModernNavbar />
            <main id="main-content" className="flex-1">
              {children}
            </main>
            <Footer />
          </div>
        </LanguageProvider>
      </body>
    </html>
  );
}