/**
 * Page Builder Section Registry
 * Author: generated by Amazon Q
 * Created: 2024-01-15
 */

import { SectionConfig } from './section-schemas';
import { WORKFLOW_SECTION, INTEGRATIONS_SECTION, PROCESS_SECTION } from './section-registry-additions';

export interface SectionTemplate {
  id: string;
  name: string;
  type: string;
  category: string;
  description: string;
  icon: string;
  defaultData: SectionConfig;
  configSchema: any;
}

export const SECTION_CATEGORIES = {
  HEADERS: 'Headers',
  CONTENT: 'Content', 
  ACTIONS: 'Actions',
  SOCIAL: 'Social Proof',
  NAVIGATION: 'Navigation',
} as const;

export const SECTION_TEMPLATES: SectionTemplate[] = [
  {
    id: 'hero-default',
    name: 'Hero Section',
    type: 'hero',
    category: SECTION_CATEGORIES.HEADERS,
    description: 'Large banner with title, subtitle, and call-to-action buttons',
    icon: '🎯',
    defaultData: {
      id: '',
      type: 'hero',
      order: 0,
      data: {
        title: 'Your Amazing Title Here',
        subtitle: 'Compelling Subtitle',
        description: 'Write a compelling description that explains your value proposition and encourages visitors to take action.',
        buttons: [
          {
            text: 'Get Started',
            href: '#',
            variant: 'primary' as const,
            size: 'lg' as const,
          },
          {
            text: 'Learn More',
            href: '#',
            variant: 'secondary' as const,
            size: 'lg' as const,
          },
        ],
        badges: [
          { text: 'Free Trial', variant: 'success' },
          { text: 'No Credit Card', variant: 'info' },
        ],
      },
      style: {
        backgroundColor: 'bg-gradient-to-br from-slate-50 via-white to-slate-100/50',
        textColor: 'text-slate-900',
        padding: 'py-20',
        alignment: 'center',
      },
    },
    configSchema: {},
  },
  {
    id: 'hero-full-gradient',
    name: 'Hero Full Gradient',
    type: 'hero',
    category: SECTION_CATEGORIES.HEADERS,
    description: 'Full-width hero with gradient background, visual elements, and dark mode support',
    icon: '🌟',
    defaultData: {
      id: '',
      type: 'hero',
      order: 0,
      data: {
        title: 'Custom Apps. Zero Heavy Code.',
        subtitle: 'Build complete web apps in days',
        description: 'Design responsive internal tools with pages, workflows, reports, roles, and integrations. AI-assisted builder + enterprise controls = speed with confidence.',
        buttons: [
          {
            text: 'Try the Builder',
            href: '#',
            variant: 'primary' as const,
            size: 'lg' as const,
          },
          {
            text: 'Browse Templates',
            href: '#',
            variant: 'outline' as const,
            size: 'lg' as const,
          },
        ],
        badges: [
          { text: 'No-Code', variant: 'default' },
          { text: 'AI-Assisted', variant: 'info' },
          { text: 'SOC2/GDPR', variant: 'success' },
        ],
      },
      style: {
        backgroundColor: 'bg-gradient-to-br from-violet-50 via-slate-50 to-cyan-50',
        textColor: 'text-slate-900',
        padding: 'py-20 lg:py-32',
        alignment: 'left',
        layout: 'full',
      },
    },
    configSchema: {},
  },
  {
    id: 'features-grid',
    name: 'Features Grid',
    type: 'features',
    category: SECTION_CATEGORIES.CONTENT,
    description: 'Grid layout showcasing key features with icons and descriptions',
    icon: '⭐',
    defaultData: {
      id: '',
      type: 'features',
      order: 0,
      data: {
        title: 'Amazing Features',
        subtitle: 'Everything you need',
        description: 'Discover the powerful features that make our platform unique',
        items: [
          {
            title: 'Fast Performance',
            description: 'Lightning-fast loading times and smooth interactions',
            icon: '⚡',
          },
          {
            title: 'Secure & Reliable',
            description: 'Enterprise-grade security with 99.9% uptime guarantee',
            icon: '🔒',
          },
          {
            title: 'Easy to Use',
            description: 'Intuitive interface designed for users of all skill levels',
            icon: '🎨',
          },
          {
            title: '24/7 Support',
            description: 'Round-the-clock customer support whenever you need help',
            icon: '🛟',
          },
        ],
      },
      style: {
        backgroundColor: 'bg-white',
        textColor: 'text-slate-900',
        padding: 'py-16',
        alignment: 'center',
      },
    },
    configSchema: {},
  },
  {
    id: 'cta-default',
    name: 'Call to Action',
    type: 'cta',
    category: SECTION_CATEGORIES.ACTIONS,
    description: 'Compelling call-to-action section with buttons',
    icon: '🚀',
    defaultData: {
      id: '',
      type: 'cta',
      order: 0,
      data: {
        title: 'Ready to Get Started?',
        description: 'Join thousands of satisfied customers and transform your business today.',
        buttons: [
          {
            text: 'Start Free Trial',
            href: '#',
            variant: 'primary' as const,
            size: 'lg' as const,
          },
        ],
      },
      style: {
        backgroundColor: 'bg-gradient-to-r from-violet-600 to-cyan-500',
        textColor: 'text-white',
        padding: 'py-16',
        alignment: 'center',
      },
    },
    configSchema: {},
  },
  {
    id: 'tabs-interactive',
    name: 'Interactive Tabs',
    type: 'tabs',
    category: SECTION_CATEGORIES.CONTENT,
    description: 'Tabbed content with interactive switching',
    icon: '📑',
    defaultData: {
      id: '',
      type: 'tabs',
      order: 0,
      data: {
        tabs: [
          {
            id: 'tab1',
            label: 'Features',
            title: 'Powerful Features',
            description: 'Discover our comprehensive set of features designed to boost your productivity.',
            features: ['Feature 1', 'Feature 2', 'Feature 3'],
          },
          {
            id: 'tab2',
            label: 'Benefits',
            title: 'Key Benefits',
            description: 'Learn about the benefits you\'ll experience when using our platform.',
            features: ['Benefit 1', 'Benefit 2', 'Benefit 3'],
          },
        ],
      },
      style: {
        backgroundColor: 'bg-slate-50',
        textColor: 'text-slate-900',
        padding: 'py-16',
        alignment: 'left',
      },
    },
    configSchema: {},
  },
  {
    id: 'faq-expandable',
    name: 'FAQ Section',
    type: 'faq',
    category: SECTION_CATEGORIES.CONTENT,
    description: 'Expandable frequently asked questions',
    icon: '❓',
    defaultData: {
      id: '',
      type: 'faq',
      order: 0,
      data: {
        title: 'Frequently Asked Questions',
        subtitle: 'Everything you need to know',
        categories: [
          {
            title: 'Getting Started',
            items: [
              {
                question: 'How do I get started?',
                answer: 'Simply sign up for an account and follow our quick setup guide.',
              },
              {
                question: 'Is there a free trial?',
                answer: 'Yes, we offer a 14-day free trial with full access to all features.',
              },
            ],
          },
          {
            title: 'Billing & Pricing',
            items: [
              {
                question: 'What payment methods do you accept?',
                answer: 'We accept all major credit cards, PayPal, and bank transfers.',
              },
              {
                question: 'Can I cancel anytime?',
                answer: 'Yes, you can cancel your subscription at any time with no penalties.',
              },
            ],
          },
        ],
      },
      style: {
        backgroundColor: 'bg-slate-50',
        textColor: 'text-slate-900',
        padding: 'py-16',
        alignment: 'left',
      },
    },
    configSchema: {},
  },
  {
    id: 'stats-counter',
    name: 'Stats Counter',
    type: 'stats',
    category: SECTION_CATEGORIES.SOCIAL,
    description: 'Display impressive statistics and numbers',
    icon: '📊',
    defaultData: {
      id: '',
      type: 'stats',
      order: 0,
      data: {
        title: 'Our Impact in Numbers',
        stats: [
          { value: '10K+', label: 'Happy Clients', icon: '👥' },
          { value: '50K+', label: 'Properties Sold', icon: '🏠' },
          { value: '$2B+', label: 'Total Value', icon: '💰' },
          { value: '98%', label: 'Satisfaction Rate', icon: '⭐' },
        ],
      },
      style: {
        backgroundColor: 'bg-slate-900',
        textColor: 'text-white',
        padding: 'py-16',
        alignment: 'center',
      },
    },
    configSchema: {},
  },
  {
    id: 'testimonials-carousel',
    name: 'Testimonials',
    type: 'testimonials',
    category: SECTION_CATEGORIES.SOCIAL,
    description: 'Customer testimonials and reviews',
    icon: '💬',
    defaultData: {
      id: '',
      type: 'testimonials',
      order: 0,
      data: {
        title: 'What Our Clients Say',
        subtitle: 'Real stories from real people',
        testimonials: [
          {
            name: 'Sarah Johnson',
            role: 'Property Investor',
            content: 'Outstanding service! They helped me find the perfect investment property.',
            rating: 5,
            avatar: '👩',
          },
          {
            name: 'Michael Chen',
            role: 'First-time Buyer',
            content: 'Professional team that made my first home purchase stress-free.',
            rating: 5,
            avatar: '👨',
          },
          {
            name: 'Emily Davis',
            role: 'Real Estate Developer',
            content: 'Excellent market knowledge and negotiation skills. Highly recommended!',
            rating: 5,
            avatar: '👩‍💼',
          },
        ],
      },
      style: {
        backgroundColor: 'bg-white',
        textColor: 'text-slate-900',
        padding: 'py-16',
        alignment: 'center',
      },
    },
    configSchema: {},
  },
  {
    id: 'property-showcase',
    name: 'Property Showcase',
    type: 'properties',
    category: SECTION_CATEGORIES.CONTENT,
    description: 'Showcase featured properties with images and details',
    icon: '🏘️',
    defaultData: {
      id: '',
      type: 'properties',
      order: 0,
      data: {
        title: 'Featured Properties',
        subtitle: 'Discover your dream home',
        properties: [
          {
            title: 'Modern Downtown Apartment',
            location: 'New York, NY',
            price: '$850,000',
            beds: 3,
            baths: 2,
            sqft: '2,100',
            image: '🏢',
          },
          {
            title: 'Luxury Beach Villa',
            location: 'Miami, FL',
            price: '$2,500,000',
            beds: 5,
            baths: 4,
            sqft: '4,500',
            image: '🏖️',
          },
          {
            title: 'Suburban Family Home',
            location: 'Austin, TX',
            price: '$650,000',
            beds: 4,
            baths: 3,
            sqft: '3,200',
            image: '🏡',
          },
        ],
      },
      style: {
        backgroundColor: 'bg-slate-50',
        textColor: 'text-slate-900',
        padding: 'py-16',
        alignment: 'left',
      },
    },
    configSchema: {},
  },
  {
    id: 'location-map',
    name: 'Location Map',
    type: 'location',
    category: SECTION_CATEGORIES.CONTENT,
    description: 'Display location with map and contact information',
    icon: '📍',
    defaultData: {
      id: '',
      type: 'location',
      order: 0,
      data: {
        title: 'Visit Our Office',
        subtitle: 'We\'re here to help',
        address: '123 Main Street, Suite 100',
        city: 'New York, NY 10001',
        phone: '+1 (555) 123-4567',
        email: 'info@realestate.com',
        hours: 'Mon-Fri: 9AM-6PM',
      },
      style: {
        backgroundColor: 'bg-white',
        textColor: 'text-slate-900',
        padding: 'py-16',
        alignment: 'left',
      },
    },
    configSchema: {},
  },
  WORKFLOW_SECTION,
  INTEGRATIONS_SECTION,
  PROCESS_SECTION,
  {
    id: 'compliance-badges',
    name: 'Compliance Badges',
    type: 'compliance',
    category: SECTION_CATEGORIES.SOCIAL,
    description: 'Display compliance certifications and security badges',
    icon: '🛡️',
    defaultData: {
      id: '',
      type: 'compliance',
      order: 0,
      data: {
        title: 'Enterprise-Grade Security & Compliance',
        description: 'Your data is protected with bank-level encryption and comprehensive compliance certifications.',
        badges: [
          {
            icon: '🔒',
            title: 'HIPAA Compliant'
          },
          {
            icon: '✓',
            title: 'SOC 2 Type II'
          },
          {
            icon: '🛡️',
            title: 'ISO 27001'
          },
          {
            icon: '🔐',
            title: 'AES-256 Encryption'
          }
        ],
        backgroundGradient: 'from-cyan-600 to-blue-600'
      },
      style: {
        backgroundColor: 'bg-gradient-to-br from-cyan-600 to-blue-600',
        textColor: 'text-white',
        padding: 'py-20',
        alignment: 'center',
      },
    },
    configSchema: {},
  },
  {
    id: 'industry-hero',
    name: 'Industry Hero',
    type: 'industry-hero',
    category: SECTION_CATEGORIES.HEADERS,
    description: 'Specialized hero section for industry pages with customizable content',
    icon: '🏭',
    defaultData: {
      id: '',
      type: 'industry-hero',
      order: 0,
      data: {
        title: 'Built for Your Industry',
        subtitle: 'Transform Operations with AI-Native Automation',
        description: 'See how teams in fleet, construction, healthcare, government and more transform operations with AI-native no-code automation.',
        icon: '🏭',
        buttons: [
          {
            text: 'Explore Solutions',
            href: '#solutions',
            variant: 'primary' as const,
            size: 'lg' as const,
          },
          {
            text: 'Book Demo',
            href: '/contact',
            variant: 'outline' as const,
            size: 'lg' as const,
          },
        ],
        textAlign: 'center' as const,
      },
      style: {
        backgroundColor: 'bg-gradient-to-br from-slate-900 via-blue-900 to-indigo-900',
        textColor: 'text-white',
        padding: 'py-20',
      },
    },
    configSchema: {},
  },
];

export function getSectionTemplate(type: string): SectionTemplate | undefined {
  return SECTION_TEMPLATES.find(template => template.type === type);
}

export function getSectionsByCategory(category: string): SectionTemplate[] {
  return SECTION_TEMPLATES.filter(template => template.category === category);
}

export function getAllSectionTypes(): string[] {
  return Array.from(new Set(SECTION_TEMPLATES.map(template => template.type)));
}