/**
 * WhyIvaFlowNewVersion Section Data Types
 * Author: generated by Amazon Q
 * Created: 2024-12-19
 */

export interface WhyIvaFlowNewVersionData {
  header: {
    badge: string;
    badgeTextColor: string;
    badgeIconColor: string;
    title: string;
    titleColor: string;
    description: string;
    descriptionColor: string;
  };
  unifiedOS: {
    borderColor: string;
    backgroundColor: string;
    shadowClass: string;
    edgeHighlight: string;
    badge: {
      text: string;
      borderColor: string;
      backgroundColor: string;
      textColor: string;
      iconColor: string;
    };
    description: string;
    descriptionColor: string;
    systemItems: Array<{
      icon: string;
      label: string;
      iconBg: string;
      iconColor: string;
    }>;
    itemBorderColor: string;
    itemBackgroundColor: string;
    itemTextColor: string;
    integrationIcon: string;
    integrationLabel: string;
    integrationSubtext: string;
    integrationGradient: string;
    integrationIconBg: string;
    integrationIconColor: string;
    integrationSubtextColor: string;
    connectionLineGradient: string;
    valueChips: Array<{
      text: string;
      iconColor: string;
    }>;
    chipBorderColor: string;
    chipBackgroundColor: string;
    chipTextColor: string;
  };
  cards: Array<{
    icon: string;
    iconBackground: string;
    iconColor: string;
    title: string;
    titleColor: string;
    subtitle: string;
    subtitleColor: string;
    badge?: {
      text: string;
      borderColor: string;
      backgroundColor: string;
      textColor: string;
    };
    description: string;
    descriptionColor: string;
    features?: string[];
    featuresTextColor: string;
    featureBulletColor: string;
    grid?: Array<{
      label: string;
      value: string;
    }>;
    gridItemBorderColor: string;
    gridItemBackgroundColor: string;
    gridItemLabelColor: string;
    gridItemValueColor: string;
    borderColor: string;
    backgroundColor: string;
    shadowClass: string;
    hoverShadowClass: string;
    glowColor: string;
    edgeShine: string;
    separatorGradient: string;
    outcomeLabel: {
      text: string;
      color: string;
    };
    outcomeValue: {
      text: string;
      color: string;
    };
  }>;
  styling: {
    backgroundColor: string;
    gradientBackground: string;
    topGlow: string;
    bottomGlow: string;
    gridOpacity: string;
    gridColor: string;
    noiseOpacity: string;
    customStyles?: React.CSSProperties;
  };
}

export const defaultWhyIvaFlowNewVersionData: WhyIvaFlowNewVersionData = {
  header: {
    badge: "Why IvaFlow",
    badgeTextColor: "text-slate-600 dark:text-slate-400",
    badgeIconColor: "bg-cyan-500",
    title: "What makes IvaFlow different?",
    titleColor: "text-slate-900 dark:text-white",
    description: "A truly no-code operating system for serious organizations — designed to deliver outcomes, not just software.",
    descriptionColor: "text-slate-700 dark:text-slate-300"
  },
  unifiedOS: {
    borderColor: "border-slate-200/70 dark:border-slate-800/70",
    backgroundColor: "bg-white/90 dark:bg-slate-900/40",
    shadowClass: "shadow-[0_18px_55px_-25px_rgba(15,23,42,0.35)] dark:shadow-[0_18px_55px_-25px_rgba(0,0,0,0.75)]",
    edgeHighlight: "bg-gradient-to-br from-white/60 to-transparent dark:from-white/10",
    badge: {
      text: "One Unified OS",
      borderColor: "border-slate-200/70 dark:border-slate-700/60",
      backgroundColor: "bg-white/90 dark:bg-slate-950/40",
      textColor: "text-slate-700 dark:text-slate-300",
      iconColor: "bg-violet-500"
    },
    description: "Intake → Orchestration → Insights → Integrations — all inside one composable core.",
    descriptionColor: "text-slate-700 dark:text-slate-300",
    systemItems: [
      {
        icon: "fas fa-file-alt",
        label: "Forms",
        iconBg: "bg-cyan-500/12 dark:bg-cyan-400/10",
        iconColor: "text-cyan-600 dark:text-cyan-300"
      },
      {
        icon: "fas fa-bolt",
        label: "Workflows",
        iconBg: "bg-violet-500/12 dark:bg-violet-400/10",
        iconColor: "text-violet-600 dark:text-violet-300"
      },
      {
        icon: "fas fa-chart-bar",
        label: "Dashboards",
        iconBg: "bg-slate-500/10 dark:bg-slate-400/10",
        iconColor: "text-slate-700 dark:text-slate-200"
      }
    ],
    itemBorderColor: "border-slate-200/70 dark:border-slate-700/60",
    itemBackgroundColor: "bg-white/90 dark:bg-slate-950/35",
    itemTextColor: "text-slate-700 dark:text-slate-300",
    integrationIcon: "fas fa-plug",
    integrationLabel: "Integrations & Channels",
    integrationSubtext: "API · Webhook · SMS · WhatsApp · Email",
    integrationGradient: "bg-gradient-to-r from-cyan-500/0 via-cyan-500/8 to-violet-500/0 dark:via-cyan-400/10",
    integrationIconBg: "bg-emerald-500/10 dark:bg-emerald-400/10",
    integrationIconColor: "text-emerald-700 dark:text-emerald-300",
    integrationSubtextColor: "text-slate-500 dark:text-slate-400",
    connectionLineGradient: "bg-gradient-to-r from-transparent via-slate-200 to-transparent dark:via-slate-800",
    valueChips: [
      { text: "Faster go-live", iconColor: "bg-cyan-500" },
      { text: "Lower change-cost", iconColor: "bg-violet-500" },
      { text: "Full audit trail", iconColor: "bg-emerald-500" }
    ],
    chipBorderColor: "border-slate-200/70 dark:border-slate-700/60",
    chipBackgroundColor: "bg-white/90 dark:bg-slate-950/35",
    chipTextColor: "text-slate-700 dark:text-slate-300"
  },
  cards: [
    {
      icon: "fas fa-cogs",
      iconBackground: "bg-cyan-500/12 dark:bg-cyan-400/10",
      iconColor: "text-cyan-700 dark:text-cyan-300",
      title: "True no-code, end-to-end",
      titleColor: "text-slate-900 dark:text-white",
      subtitle: "Build systems, not prototypes",
      subtitleColor: "text-slate-500 dark:text-slate-400",
      badge: {
        text: "0 code",
        borderColor: "border-slate-200/70 dark:border-slate-700/60",
        backgroundColor: "bg-white/90 dark:bg-slate-950/35",
        textColor: "text-slate-700 dark:text-slate-300"
      },
      description: "Design forms, workflows, dashboards and SLAs through a visual designer — no scripting, no hidden low-code.",
      descriptionColor: "text-slate-700 dark:text-slate-300",
      features: [
        "Drag-and-drop forms & processes",
        "Instant publishing & versioning",
        "Owned by business teams"
      ],
      featuresTextColor: "text-slate-700 dark:text-slate-300",
      featureBulletColor: "bg-cyan-500",
      gridItemBorderColor: "border-slate-200/70 dark:border-slate-700/60",
      gridItemBackgroundColor: "bg-white/90 dark:bg-slate-950/35",
      gridItemLabelColor: "text-slate-500 dark:text-slate-400",
      gridItemValueColor: "text-slate-900 dark:text-white",
      borderColor: "border-slate-200/70 dark:border-slate-800/70",
      backgroundColor: "bg-white/90 dark:bg-slate-900/45",
      shadowClass: "shadow-[0_18px_55px_-25px_rgba(15,23,42,0.35)] dark:shadow-[0_18px_55px_-25px_rgba(0,0,0,0.75)]",
      hoverShadowClass: "hover:shadow-[0_26px_70px_-28px_rgba(6,182,212,0.35)] dark:hover:shadow-[0_26px_70px_-28px_rgba(34,211,238,0.25)]",
      glowColor: "bg-cyan-500/15",
      edgeShine: "bg-gradient-to-br from-white/70 via-white/0 to-white/0 dark:from-white/10",
      separatorGradient: "bg-gradient-to-r from-transparent via-slate-200 to-transparent dark:via-slate-800",
      outcomeLabel: {
        text: "Typical outcome",
        color: "text-slate-500 dark:text-slate-400"
      },
      outcomeValue: {
        text: "Go-live in weeks",
        color: "text-slate-900 dark:text-white"
      }
    },
    {
      icon: "fas fa-puzzle-piece",
      iconBackground: "bg-violet-500/12 dark:bg-violet-400/10",
      iconColor: "text-violet-700 dark:text-violet-300",
      title: "Unified platform, multi-concept",
      titleColor: "text-slate-900 dark:text-white",
      subtitle: "No glued-on modules",
      subtitleColor: "text-slate-500 dark:text-slate-400",
      description: "CRM, omni-channel communication, GIS and automation — baked into the core with one shared data model.",
      descriptionColor: "text-slate-700 dark:text-slate-300",
      grid: [
        { label: "Unified", value: "Data model" },
        { label: "Native", value: "Omni-channel" },
        { label: "Smart", value: "Routing & SLAs" },
        { label: "Aware", value: "GIS workflows" }
      ],
      featuresTextColor: "text-slate-700 dark:text-slate-300",
      featureBulletColor: "bg-violet-500",
      gridItemBorderColor: "border-slate-200/70 dark:border-slate-700/60",
      gridItemBackgroundColor: "bg-white/90 dark:bg-slate-950/35",
      gridItemLabelColor: "text-slate-500 dark:text-slate-400",
      gridItemValueColor: "text-slate-900 dark:text-white",
      borderColor: "border-slate-200/70 dark:border-slate-800/70",
      backgroundColor: "bg-white/90 dark:bg-slate-900/45",
      shadowClass: "shadow-[0_18px_55px_-25px_rgba(15,23,42,0.35)] dark:shadow-[0_18px_55px_-25px_rgba(0,0,0,0.75)]",
      hoverShadowClass: "hover:shadow-[0_26px_70px_-28px_rgba(139,92,246,0.28)] dark:hover:shadow-[0_26px_70px_-28px_rgba(167,139,250,0.22)]",
      glowColor: "bg-violet-500/15",
      edgeShine: "bg-gradient-to-br from-white/70 via-white/0 to-white/0 dark:from-white/10",
      separatorGradient: "bg-gradient-to-r from-transparent via-slate-200 to-transparent dark:via-slate-800",
      outcomeLabel: {
        text: "Typical outcome",
        color: "text-slate-500 dark:text-slate-400"
      },
      outcomeValue: {
        text: "One OS, many apps",
        color: "text-slate-900 dark:text-white"
      }
    },
    {
      icon: "fas fa-lightbulb",
      iconBackground: "bg-emerald-500/12 dark:bg-emerald-400/10",
      iconColor: "text-emerald-700 dark:text-emerald-300",
      title: "AI-Native & Future-Ready",
      titleColor: "text-slate-900 dark:text-white",
      subtitle: "Built for tomorrow's challenges",
      subtitleColor: "text-slate-500 dark:text-slate-400",
      description: "Native AI integration, IoT connectivity, and modern architecture that evolves with your business needs.",
      descriptionColor: "text-slate-700 dark:text-slate-300",
      features: [
        "Built-in AI & machine learning",
        "IoT device connectivity",
        "Cloud-native architecture"
      ],
      featuresTextColor: "text-slate-700 dark:text-slate-300",
      featureBulletColor: "bg-emerald-500",
      gridItemBorderColor: "border-slate-200/70 dark:border-slate-700/60",
      gridItemBackgroundColor: "bg-white/90 dark:bg-slate-950/35",
      gridItemLabelColor: "text-slate-500 dark:text-slate-400",
      gridItemValueColor: "text-slate-900 dark:text-white",
      borderColor: "border-slate-200/70 dark:border-slate-800/70",
      backgroundColor: "bg-white/90 dark:bg-slate-900/45",
      shadowClass: "shadow-[0_18px_55px_-25px_rgba(15,23,42,0.35)] dark:shadow-[0_18px_55px_-25px_rgba(0,0,0,0.75)]",
      hoverShadowClass: "hover:shadow-[0_26px_70px_-28px_rgba(16,185,129,0.22)] dark:hover:shadow-[0_26px_70px_-28px_rgba(52,211,153,0.18)]",
      glowColor: "bg-emerald-500/12",
      edgeShine: "bg-gradient-to-br from-white/70 via-white/0 to-white/0 dark:from-white/10",
      separatorGradient: "bg-gradient-to-r from-transparent via-slate-200 to-transparent dark:via-slate-800",
      outcomeLabel: {
        text: "Typical outcome",
        color: "text-slate-500 dark:text-slate-400"
      },
      outcomeValue: {
        text: "Future-proof platform",
        color: "text-slate-900 dark:text-white"
      }
    }
  ],
  styling: {
    backgroundColor: "bg-gray-50 dark:bg-slate-950",
    gradientBackground: "bg-gradient-to-b from-white via-gray-50 to-gray-100 dark:from-slate-950 dark:via-slate-950 dark:to-slate-950",
    topGlow: "bg-violet-500/15",
    bottomGlow: "bg-cyan-500/15",
    gridOpacity: "opacity-[0.06] dark:opacity-[0.09]",
    gridColor: "rgba(15,23,42,1)",
    noiseOpacity: "opacity-[0.08] dark:opacity-[0.10]"
  }
};