/**
 * Site Settings API
 * Author: generated by Amazon Q
 * Created: 2024-12-20
 */

import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';

export async function GET() {
  try {
    const settings = await prisma.siteSettings.findFirst();
    
    if (!settings) {
      // Return default settings if none exist
      const defaultSettings = {
        logo: {
          url: '',
          alt: 'English Website',
          width: 120,
          height: 40
        },
        languages: {
          showInHeader: true,
          defaultLanguage: 'en',
          enabledLanguages: ['en', 'ar']
        },
        contactSales: {
          show: true,
          text: 'Contact Sales',
          url: '/contact-sales'
        },
        theme: {
          defaultTheme: 'light',
          autoSwitchByTime: false,
          darkModeStart: '18:00',
          darkModeEnd: '06:00'
        },
        favicon: {
          url: '/favicon.ico',
          appleTouchIcon: '/apple-touch-icon.png',
          manifest: '/site.webmanifest'
        }
      };
      
      const response = NextResponse.json(defaultSettings);
      response.cookies.set('defaultLanguage', defaultSettings.languages.defaultLanguage, {
        path: '/',
        maxAge: 60 * 60 * 24 * 365 // 1 year
      });
      return response;
    }

    const saved = JSON.parse(settings.data);

    const merged = {
      ...saved,
      footer: {
        companyName: 'English Website',
        tagline: '',
        description: '',
        columns: [],
        bottomBar: { show: true, copyrightText: '© {year} English Website. All rights reserved.', showSocialLinks: true, socialLinks: [] },
        style: { backgroundColor: '', textColor: '', linkColor: '', borderColor: '', padding: 'py-12' },
        ...saved.footer,
        contactInfo: {
          show: true,
          email: '',
          phone: '',
          address: '',
          ...(saved.footer?.contactInfo || {})
        }
      }
    };

    const response = NextResponse.json(merged);
    response.cookies.set('defaultLanguage', merged.languages?.defaultLanguage || 'en', {
      path: '/',
      maxAge: 60 * 60 * 24 * 365 // 1 year
    });
    return response;
  } catch (error) {
    console.error('Failed to fetch settings:', error);
    return NextResponse.json(
      { error: 'Failed to fetch settings' },
      { status: 500 }
    );
  }
}

export async function POST(request: NextRequest) {
  try {
    const settingsData = await request.json();

    // Validate required fields
    if (!settingsData.logo || !settingsData.languages || !settingsData.contactSales || !settingsData.theme) {
      return NextResponse.json(
        { error: 'Missing required settings data' },
        { status: 400 }
      );
    }

    // Check if settings already exist
    const existingSettings = await prisma.siteSettings.findFirst();

    if (existingSettings) {
      // Update existing settings
      await prisma.siteSettings.update({
        where: { id: existingSettings.id },
        data: {
          data: JSON.stringify(settingsData),
          updatedAt: new Date()
        }
      });
    } else {
      // Create new settings
      await prisma.siteSettings.create({
        data: {
          data: JSON.stringify(settingsData)
        }
      });
    }

    const response = NextResponse.json({ success: true });
    response.cookies.set('defaultLanguage', settingsData.languages.defaultLanguage, {
      path: '/',
      maxAge: 60 * 60 * 24 * 365 // 1 year
    });
    return response;
  } catch (error) {
    console.error('Failed to save settings:', error);
    return NextResponse.json(
      { error: 'Failed to save settings' },
      { status: 500 }
    );
  }
}