/**
 * Admin Settings Page
 * Author: generated by Amazon Q
 * Created: 2024-12-20
 */

'use client';

import { useState, useEffect } from 'react';
import { Button } from '@/components/ui/Button';
import { Card } from '@/components/ui/Card';
import { Input } from '@/components/ui/Input';
import { Label } from '@/components/ui/Label';
import { Switch } from '@/components/ui/Switch';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/Select';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/Tabs';
import { Upload, Save, RotateCcw, Settings, Image, Globe, Phone, Palette, Star, Layout, Plus, Trash2, GripVertical, ExternalLink } from 'lucide-react';
import { useImageUpload } from '@/hooks/useImageUpload';

interface SiteSettings {
  logo: {
    lightUrl: string;
    darkUrl: string;
    alt: string;
    width: number;
    height: number;
  };
  languages: {
    showInHeader: boolean;
    defaultLanguage: string;
    enabledLanguages: string[];
  };
  contactSales: {
    show: boolean;
    text: string;
    url: string;
  };
  theme: {
    defaultTheme: 'light' | 'dark' | 'system';
    autoSwitchByTime: boolean;
    darkModeStart: string;
    darkModeEnd: string;
  };
  favicon: {
    url: string;
    appleTouchIcon: string;
    manifest: string;
  };
  footer: {
    companyName: string;
    tagline: string;
    description: string;
    contactInfo: {
      show: boolean;
      email: string;
      phone: string;
      address: string;
    };
    columns: FooterColumn[];
    bottomBar: {
      show: boolean;
      copyrightText: string;
      showSocialLinks: boolean;
      socialLinks: SocialLink[];
    };
    style: {
      backgroundColor: string;
      textColor: string;
      linkColor: string;
      borderColor: string;
      padding: string;
    };
  };
}

interface FooterLink {
  label: string;
  url: string;
}

interface FooterColumn {
  id: string;
  title: string;
  links: FooterLink[];
}

interface SocialLink {
  platform: 'twitter' | 'linkedin' | 'facebook' | 'instagram' | 'youtube' | 'github';
  url: string;
}

const defaultSettings: SiteSettings = {
  logo: {
    lightUrl: '',
    darkUrl: '',
    alt: 'English Website',
    width: 120,
    height: 40
  },
  languages: {
    showInHeader: true,
    defaultLanguage: 'en',
    enabledLanguages: ['en', 'ar', 'tr', 'fr', 'de', 'es']
  },
  contactSales: {
    show: true,
    text: 'Contact Sales',
    url: '/contact-sales'
  },
  theme: {
    defaultTheme: 'light',
    autoSwitchByTime: false,
    darkModeStart: '18:00',
    darkModeEnd: '06:00'
  },
  favicon: {
    url: '/favicon.ico',
    appleTouchIcon: '/apple-touch-icon.png',
    manifest: '/site.webmanifest'
  },
  footer: {
    companyName: 'English Website',
    tagline: 'Modern English Learning Platform',
    description: 'A comprehensive platform for English learning and business automation solutions.',
    contactInfo: {
      show: true,
      email: '',
      phone: '',
      address: ''
    },
    columns: [
      {
        id: 'product',
        title: 'Product',
        links: [
          { label: 'Home', url: '/' },
          { label: 'Features', url: '/features' },
          { label: 'Pricing', url: '/pricing' },
          { label: 'Contact', url: '/contact' }
        ]
      },
      {
        id: 'company',
        title: 'Company',
        links: [
          { label: 'About Us', url: '/about' },
          { label: 'Blog', url: '/blog' },
          { label: 'Careers', url: '/careers' }
        ]
      }
    ],
    bottomBar: {
      show: true,
      copyrightText: '© {year} English Website. All rights reserved.',
      showSocialLinks: true,
      socialLinks: []
    },
    style: {
      backgroundColor: '',
      textColor: '',
      linkColor: '',
      borderColor: '',
      padding: 'py-12'
    }
  }
};

export default function SettingsPage() {
  const [settings, setSettings] = useState<SiteSettings>(defaultSettings);
  const [isLoading, setIsLoading] = useState(true);
  const [isSaving, setIsSaving] = useState(false);

  const lightLogoUpload = useImageUpload({
    type: 'logo-light',
    onSuccess: (url) => {
      setSettings(prev => ({
        ...prev,
        logo: { ...prev.logo, lightUrl: url }
      }));
    },
    onError: (error) => {
      console.error('Light logo upload failed:', error);
      alert(`Failed to upload light logo: ${error}`);
    }
  });

  const darkLogoUpload = useImageUpload({
    type: 'logo-dark',
    onSuccess: (url) => {
      setSettings(prev => ({
        ...prev,
        logo: { ...prev.logo, darkUrl: url }
      }));
    },
    onError: (error) => {
      console.error('Dark logo upload failed:', error);
      alert(`Failed to upload dark logo: ${error}`);
    }
  });

  const faviconUpload = useImageUpload({
    type: 'favicon',
    onSuccess: (url) => {
      setSettings(prev => ({
        ...prev,
        favicon: { ...prev.favicon, url }
      }));
    },
    onError: (error) => {
      console.error('Favicon upload failed:', error);
      alert(`Failed to upload favicon: ${error}`);
    }
  });

  useEffect(() => {
    loadSettings();
  }, []);

  const loadSettings = async () => {
    try {
      const response = await fetch('/api/admin/settings');
      if (response.ok) {
        const data = await response.json();
        const mergedSettings = { ...defaultSettings, ...data };
        setSettings(mergedSettings);
        
        // Set previews for existing images without cache busting initially
        if (mergedSettings.logo?.lightUrl) {
          lightLogoUpload.setPreview(mergedSettings.logo.lightUrl);
        }
        
        if (mergedSettings.logo?.darkUrl) {
          darkLogoUpload.setPreview(mergedSettings.logo.darkUrl);
        }
        
        if (mergedSettings.favicon?.url) {
          faviconUpload.setPreview(mergedSettings.favicon.url);
        }
      } else {
        console.error('Failed to load settings:', response.statusText);
      }
    } catch (error) {
      console.error('Failed to load settings:', error);
    } finally {
      setIsLoading(false);
    }
  };

  const saveSettings = async () => {
    setIsSaving(true);
    try {
      const response = await fetch('/api/admin/settings', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(settings)
      });

      if (response.ok) {
        // Show success message
        alert('Settings saved successfully!');
      } else {
        throw new Error('Failed to save settings');
      }
    } catch (error) {
      console.error('Failed to save settings:', error);
      alert('Failed to save settings. Please try again.');
    } finally {
      setIsSaving(false);
    }
  };

  const resetSettings = () => {
    if (confirm('Are you sure you want to reset all settings to default?')) {
      setSettings(defaultSettings);
      lightLogoUpload.clearPreview();
      darkLogoUpload.clearPreview();
      faviconUpload.clearPreview();
      // Also clear the URLs in settings
      setSettings(prev => ({
        ...prev,
        logo: { ...prev.logo, lightUrl: '', darkUrl: '' },
        favicon: { ...prev.favicon, url: '/favicon.ico' }
      }));
    }
  };

  const handleLightLogoUpload = async (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (file) {
      try {
        await lightLogoUpload.uploadImage(file);
        event.target.value = '';
      } catch (error) {
        console.error('Light logo upload error:', error);
        event.target.value = '';
      }
    }
  };

  const handleDarkLogoUpload = async (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (file) {
      try {
        await darkLogoUpload.uploadImage(file);
        event.target.value = '';
      } catch (error) {
        console.error('Dark logo upload error:', error);
        event.target.value = '';
      }
    }
  };

  const handleFaviconUpload = async (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (file) {
      try {
        await faviconUpload.uploadImage(file);
        // Clear the input so the same file can be selected again if needed
        event.target.value = '';
      } catch (error) {
        console.error('Favicon upload error:', error);
        event.target.value = '';
      }
    }
  };

  if (isLoading) {
    return (
      <div className="flex items-center justify-center min-h-screen">
        <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600"></div>
      </div>
    );
  }

  return (
    <div className="container mx-auto px-4 py-8 max-w-4xl">
      <div className="flex items-center justify-between mb-8">
        <div className="flex items-center gap-3">
          <Settings className="h-8 w-8 text-blue-600" />
          <h1 className="text-3xl font-bold text-gray-900 dark:text-white">Site Settings</h1>
        </div>
        <div className="flex gap-3">
          <Button variant="outline" onClick={resetSettings}>
            <RotateCcw className="h-4 w-4 mr-2" />
            Reset to Default
          </Button>
          <Button onClick={saveSettings} disabled={isSaving}>
            <Save className="h-4 w-4 mr-2" />
            {isSaving ? 'Saving...' : 'Save Settings'}
          </Button>
        </div>
      </div>

      <Tabs defaultValue="logo" className="space-y-6">
        <TabsList className="grid w-full grid-cols-6">
          <TabsTrigger value="logo" className="flex items-center gap-2">
            <Image className="h-4 w-4" />
            Logo
          </TabsTrigger>
          <TabsTrigger value="languages" className="flex items-center gap-2">
            <Globe className="h-4 w-4" />
            Languages
          </TabsTrigger>
          <TabsTrigger value="contact" className="flex items-center gap-2">
            <Phone className="h-4 w-4" />
            Contact Sales
          </TabsTrigger>
          <TabsTrigger value="theme" className="flex items-center gap-2">
            <Palette className="h-4 w-4" />
            Theme
          </TabsTrigger>
          <TabsTrigger value="favicon" className="flex items-center gap-2">
            <Star className="h-4 w-4" />
            Favicon
          </TabsTrigger>
          <TabsTrigger value="footer" className="flex items-center gap-2">
            <Layout className="h-4 w-4" />
            Footer
          </TabsTrigger>
        </TabsList>

        {/* Logo Settings */}
        <TabsContent value="logo">
          <Card className="p-6">
            <h2 className="text-xl font-semibold mb-4">Logo Configuration</h2>
            <div className="space-y-8">
              {/* Light Theme Logo */}
              <div>
                <h3 className="text-lg font-medium mb-4 flex items-center gap-2">
                  <div className="w-4 h-4 bg-white border border-gray-300 rounded"></div>
                  Light Theme Logo
                </h3>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                  <div className="space-y-4">
                    <div>
                      <Label htmlFor="light-logo-upload">Upload Light Logo</Label>
                      <div className="mt-2">
                        <input
                          id="light-logo-upload"
                          type="file"
                          accept="image/*,.webp"
                          onChange={handleLightLogoUpload}
                          className="hidden"
                        />
                        <Button
                          variant="outline"
                          onClick={() => document.getElementById('light-logo-upload')?.click()}
                          className="w-full"
                        >
                          <Upload className="h-4 w-4 mr-2" />
                          Choose Light Logo
                        </Button>
                      </div>
                    </div>
                  </div>
                  <div className="flex items-center justify-center">
                    {(lightLogoUpload.preview || settings.logo.lightUrl) ? (
                      <div className="border-2 border-dashed border-gray-300 rounded-lg p-4 bg-white">
                        <img
                          key={`light-logo-${Date.now()}`}
                          src={lightLogoUpload.preview || `${settings.logo.lightUrl}?v=${Date.now()}`}
                          alt={settings.logo.alt || 'Light logo preview'}
                          className="max-w-full h-auto"
                          style={{
                            maxWidth: `${settings.logo.width}px`,
                            maxHeight: `${settings.logo.height}px`
                          }}
                          onLoad={() => {
                            // Force re-render after image loads
                            console.log('Light logo loaded successfully');
                          }}
                        />
                        {lightLogoUpload.isUploading && (
                          <div className="mt-2 text-center text-sm text-blue-600">Uploading...</div>
                        )}
                      </div>
                    ) : (
                      <div className="border-2 border-dashed border-gray-300 rounded-lg p-8 text-center text-gray-500 bg-white">
                        <Image className="h-12 w-12 mx-auto mb-2" />
                        <p>No light logo uploaded</p>
                      </div>
                    )}
                  </div>
                </div>
              </div>

              {/* Dark Theme Logo */}
              <div>
                <h3 className="text-lg font-medium mb-4 flex items-center gap-2">
                  <div className="w-4 h-4 bg-gray-800 rounded"></div>
                  Dark Theme Logo
                </h3>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                  <div className="space-y-4">
                    <div>
                      <Label htmlFor="dark-logo-upload">Upload Dark Logo</Label>
                      <div className="mt-2">
                        <input
                          id="dark-logo-upload"
                          type="file"
                          accept="image/*,.webp"
                          onChange={handleDarkLogoUpload}
                          className="hidden"
                        />
                        <Button
                          variant="outline"
                          onClick={() => document.getElementById('dark-logo-upload')?.click()}
                          className="w-full"
                        >
                          <Upload className="h-4 w-4 mr-2" />
                          Choose Dark Logo
                        </Button>
                      </div>
                    </div>
                  </div>
                  <div className="flex items-center justify-center">
                    {(darkLogoUpload.preview || settings.logo.darkUrl) ? (
                      <div className="border-2 border-dashed border-gray-300 rounded-lg p-4 bg-gray-800">
                        <img
                          key={`dark-logo-${Date.now()}`}
                          src={darkLogoUpload.preview || `${settings.logo.darkUrl}?v=${Date.now()}`}
                          alt={settings.logo.alt || 'Dark logo preview'}
                          className="max-w-full h-auto"
                          style={{
                            maxWidth: `${settings.logo.width}px`,
                            maxHeight: `${settings.logo.height}px`
                          }}
                          onLoad={() => {
                            // Force re-render after image loads
                            console.log('Dark logo loaded successfully');
                          }}
                        />
                        {darkLogoUpload.isUploading && (
                          <div className="mt-2 text-center text-sm text-blue-600">Uploading...</div>
                        )}
                      </div>
                    ) : (
                      <div className="border-2 border-dashed border-gray-300 rounded-lg p-8 text-center text-gray-500 bg-gray-800">
                        <Image className="h-12 w-12 mx-auto mb-2 text-white" />
                        <p className="text-white">No dark logo uploaded</p>
                      </div>
                    )}
                  </div>
                </div>
              </div>

              {/* Common Settings */}
              <div>
                <h3 className="text-lg font-medium mb-4">Common Settings</h3>
                <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                  <div>
                    <Label htmlFor="logo-alt">Alt Text</Label>
                    <Input
                      id="logo-alt"
                      value={settings.logo.alt}
                      onChange={(e) => setSettings(prev => ({
                        ...prev,
                        logo: { ...prev.logo, alt: e.target.value }
                      }))}
                    />
                  </div>
                  <div>
                    <Label htmlFor="logo-width">Width (px)</Label>
                    <Input
                      id="logo-width"
                      type="number"
                      value={settings.logo.width}
                      onChange={(e) => setSettings(prev => ({
                        ...prev,
                        logo: { ...prev.logo, width: parseInt(e.target.value) || 120 }
                      }))}
                    />
                  </div>
                  <div>
                    <Label htmlFor="logo-height">Height (px)</Label>
                    <Input
                      id="logo-height"
                      type="number"
                      value={settings.logo.height}
                      onChange={(e) => setSettings(prev => ({
                        ...prev,
                        logo: { ...prev.logo, height: parseInt(e.target.value) || 40 }
                      }))}
                    />
                  </div>
                </div>
              </div>
            </div>
          </Card>
        </TabsContent>

        {/* Languages Settings */}
        <TabsContent value="languages">
          <Card className="p-6">
            <h2 className="text-xl font-semibold mb-4">Language Configuration</h2>
            <div className="space-y-6">
              <div className="flex items-center justify-between">
                <div>
                  <Label>Show Language Selector in Header</Label>
                  <p className="text-sm text-gray-600 mt-1">Display language switcher in the main navigation</p>
                </div>
                <Switch
                  checked={settings.languages.showInHeader}
                  onCheckedChange={(checked) => setSettings(prev => ({
                    ...prev,
                    languages: { ...prev.languages, showInHeader: checked }
                  }))}
                />
              </div>

              <div>
                <Label htmlFor="default-language">Default Language</Label>
                <Select
                  value={settings.languages.defaultLanguage}
                  onValueChange={(value) => setSettings(prev => ({
                    ...prev,
                    languages: { ...prev.languages, defaultLanguage: value }
                  }))}
                >
                  <SelectTrigger>
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="en">🇺🇸 English</SelectItem>
                    <SelectItem value="ar">🇸🇦 العربية (Arabic)</SelectItem>
                    <SelectItem value="tr">🇹🇷 Türkçe (Turkish)</SelectItem>
                    <SelectItem value="fr">🇫🇷 Français (French)</SelectItem>
                    <SelectItem value="de">🇩🇪 Deutsch (German)</SelectItem>
                    <SelectItem value="es">🇪🇸 Español (Spanish)</SelectItem>
                    <SelectItem value="fa">🇮🇷 فارسی (Persian)</SelectItem>
                  </SelectContent>
                </Select>
              </div>

              <div>
                <Label>Enabled Languages</Label>
                <p className="text-sm text-gray-500 dark:text-gray-400 mt-1 mb-3">
                  Select which languages should be available on your website. Disabled languages will not appear in the language switcher.
                </p>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                  {[
                    { code: 'en', name: 'English', flag: '🇺🇸' },
                    { code: 'ar', name: 'العربية (Arabic)', flag: '🇸🇦' },
                    { code: 'tr', name: 'Türkçe (Turkish)', flag: '🇹🇷' },
                    { code: 'fr', name: 'Français (French)', flag: '🇫🇷' },
                    { code: 'de', name: 'Deutsch (German)', flag: '🇩🇪' },
                    { code: 'es', name: 'Español (Spanish)', flag: '🇪🇸' },
                    { code: 'fa', name: 'فارسی (Persian)', flag: '🇮🇷' }
                  ].map((lang) => (
                    <label
                      key={lang.code}
                      className={`flex items-center gap-3 p-3 border rounded-lg cursor-pointer transition-all ${
                        settings.languages.enabledLanguages.includes(lang.code)
                          ? 'border-indigo-500 bg-indigo-50 dark:bg-indigo-900/20'
                          : 'border-gray-300 dark:border-gray-600 hover:border-indigo-300 dark:hover:border-indigo-700'
                      }`}
                    >
                      <input
                        type="checkbox"
                        checked={settings.languages.enabledLanguages.includes(lang.code)}
                        onChange={(e) => {
                          const enabled = settings.languages.enabledLanguages;
                          if (e.target.checked) {
                            setSettings(prev => ({
                              ...prev,
                              languages: {
                                ...prev.languages,
                                enabledLanguages: [...enabled, lang.code]
                              }
                            }));
                          } else {
                            // جلوگیری از غیرفعال کردن زبان پیشفرض
                            if (lang.code === settings.languages.defaultLanguage) {
                              alert('Cannot disable the default language. Please change the default language first.');
                              return;
                            }
                            setSettings(prev => ({
                              ...prev,
                              languages: {
                                ...prev.languages,
                                enabledLanguages: enabled.filter(l => l !== lang.code)
                              }
                            }));
                          }
                        }}
                        className="w-4 h-4 text-indigo-600 border-gray-300 rounded focus:ring-indigo-500"
                      />
                      <span className="text-2xl">{lang.flag}</span>
                      <div className="flex-1">
                        <div className="font-medium text-sm text-gray-900 dark:text-white">
                          {lang.name}
                        </div>
                        <div className="text-xs text-gray-500 dark:text-gray-400">
                          {lang.code.toUpperCase()}
                        </div>
                      </div>
                    </label>
                  ))}
                </div>
              </div>
            </div>
          </Card>
        </TabsContent>

        {/* Contact Sales Settings */}
        <TabsContent value="contact">
          <Card className="p-6">
            <h2 className="text-xl font-semibold mb-4">Contact Sales Configuration</h2>
            <div className="space-y-6">
              <div className="flex items-center justify-between">
                <div>
                  <Label>Show Contact Sales Button</Label>
                  <p className="text-sm text-gray-600 mt-1">Display contact sales button in the header</p>
                </div>
                <Switch
                  checked={settings.contactSales.show}
                  onCheckedChange={(checked) => setSettings(prev => ({
                    ...prev,
                    contactSales: { ...prev.contactSales, show: checked }
                  }))}
                />
              </div>

              <div>
                <Label htmlFor="contact-text">Button Text</Label>
                <Input
                  id="contact-text"
                  value={settings.contactSales.text}
                  onChange={(e) => setSettings(prev => ({
                    ...prev,
                    contactSales: { ...prev.contactSales, text: e.target.value }
                  }))}
                />
              </div>

              <div>
                <Label htmlFor="contact-url">Button URL</Label>
                <Input
                  id="contact-url"
                  value={settings.contactSales.url}
                  onChange={(e) => setSettings(prev => ({
                    ...prev,
                    contactSales: { ...prev.contactSales, url: e.target.value }
                  }))}
                />
              </div>
            </div>
          </Card>
        </TabsContent>

        {/* Theme Settings */}
        <TabsContent value="theme">
          <Card className="p-6">
            <h2 className="text-xl font-semibold mb-4">Theme Configuration</h2>
            <div className="space-y-6">
              <div>
                <Label htmlFor="default-theme">Default Theme</Label>
                <Select
                  value={settings.theme.defaultTheme}
                  onValueChange={(value) => setSettings(prev => ({
                    ...prev,
                    theme: { ...prev.theme, defaultTheme: value as 'light' | 'dark' | 'system' }
                  }))}
                >
                  <SelectTrigger>
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="light">Light</SelectItem>
                    <SelectItem value="dark">Dark</SelectItem>
                    <SelectItem value="system">System</SelectItem>
                  </SelectContent>
                </Select>
              </div>

              <div className="flex items-center justify-between">
                <div>
                  <Label>Auto Switch by Time</Label>
                  <p className="text-sm text-gray-600 mt-1">Automatically switch theme based on time</p>
                </div>
                <Switch
                  checked={settings.theme.autoSwitchByTime}
                  onCheckedChange={(checked) => setSettings(prev => ({
                    ...prev,
                    theme: { ...prev.theme, autoSwitchByTime: checked }
                  }))}
                />
              </div>

              {settings.theme.autoSwitchByTime && (
                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <Label htmlFor="dark-start">Dark Mode Start</Label>
                    <Input
                      id="dark-start"
                      type="time"
                      value={settings.theme.darkModeStart}
                      onChange={(e) => setSettings(prev => ({
                        ...prev,
                        theme: { ...prev.theme, darkModeStart: e.target.value }
                      }))}
                    />
                  </div>
                  <div>
                    <Label htmlFor="dark-end">Dark Mode End</Label>
                    <Input
                      id="dark-end"
                      type="time"
                      value={settings.theme.darkModeEnd}
                      onChange={(e) => setSettings(prev => ({
                        ...prev,
                        theme: { ...prev.theme, darkModeEnd: e.target.value }
                      }))}
                    />
                  </div>
                </div>
              )}
            </div>
          </Card>
        </TabsContent>

        {/* Favicon Settings */}
        <TabsContent value="favicon">
          <Card className="p-6">
            <h2 className="text-xl font-semibold mb-4">Favicon Configuration</h2>
            <div className="space-y-6">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div className="space-y-4">
                  <div>
                    <Label htmlFor="favicon-upload">Upload Favicon</Label>
                    <p className="text-sm text-gray-600 mt-1">Recommended: 32x32 or 16x16 pixels, ICO or PNG format</p>
                    <div className="mt-2">
                      <input
                        id="favicon-upload"
                        type="file"
                        accept=".ico,.png,.svg,.webp"
                        onChange={handleFaviconUpload}
                        className="hidden"
                      />
                      <Button
                        variant="outline"
                        onClick={() => document.getElementById('favicon-upload')?.click()}
                        className="w-full"
                      >
                        <Upload className="h-4 w-4 mr-2" />
                        Choose Favicon File
                      </Button>
                    </div>
                  </div>

                  <div>
                    <Label htmlFor="favicon-url">Favicon URL</Label>
                    <Input
                      id="favicon-url"
                      value={settings.favicon.url}
                      onChange={(e) => setSettings(prev => ({
                        ...prev,
                        favicon: { ...prev.favicon, url: e.target.value }
                      }))}
                      placeholder="/favicon.ico"
                    />
                  </div>

                  <div>
                    <Label htmlFor="apple-touch-icon">Apple Touch Icon</Label>
                    <Input
                      id="apple-touch-icon"
                      value={settings.favicon.appleTouchIcon}
                      onChange={(e) => setSettings(prev => ({
                        ...prev,
                        favicon: { ...prev.favicon, appleTouchIcon: e.target.value }
                      }))}
                      placeholder="/apple-touch-icon.png"
                    />
                  </div>

                  <div>
                    <Label htmlFor="manifest">Web App Manifest</Label>
                    <Input
                      id="manifest"
                      value={settings.favicon.manifest}
                      onChange={(e) => setSettings(prev => ({
                        ...prev,
                        favicon: { ...prev.favicon, manifest: e.target.value }
                      }))}
                      placeholder="/site.webmanifest"
                    />
                  </div>
                </div>

                <div className="flex items-center justify-center">
                  {(faviconUpload.preview || settings.favicon.url) ? (
                    <div className="border-2 border-dashed border-gray-300 rounded-lg p-4">
                      <img
                        key={`favicon-${Date.now()}`}
                        src={faviconUpload.preview || `${settings.favicon.url}?v=${Date.now()}`}
                        alt="Favicon preview"
                        className="w-8 h-8 mx-auto"
                        onLoad={() => {
                          console.log('Favicon loaded successfully');
                        }}
                        onError={(e) => {
                          const target = e.target as HTMLImageElement;
                          target.style.display = 'none';
                          const parent = target.parentElement;
                          if (parent && !parent.querySelector('.error-message')) {
                            const errorDiv = document.createElement('div');
                            errorDiv.className = 'error-message text-red-500 text-sm text-center';
                            errorDiv.textContent = 'Failed to load favicon';
                            parent.appendChild(errorDiv);
                          }
                        }}
                      />
                      <p className="text-sm text-gray-600 mt-2 text-center">Favicon Preview</p>
                      {faviconUpload.isUploading && (
                        <div className="mt-2 text-center text-sm text-blue-600">Uploading...</div>
                      )}
                    </div>
                  ) : (
                    <div className="border-2 border-dashed border-gray-300 rounded-lg p-8 text-center text-gray-500">
                      <Star className="h-12 w-12 mx-auto mb-2" />
                      <p>No favicon uploaded</p>
                    </div>
                  )}
                </div>
              </div>
            </div>
          </Card>
        </TabsContent>
        {/* Footer Settings */}
        <TabsContent value="footer">
          <div className="space-y-6">
            {/* Brand Info */}
            <Card className="p-6">
              <h2 className="text-xl font-semibold mb-4">Brand Information</h2>
              <div className="space-y-4">
                <div>
                  <Label htmlFor="footer-company">Company Name</Label>
                  <Input
                    id="footer-company"
                    value={settings.footer?.companyName || ''}
                    onChange={(e) => setSettings(prev => ({
                      ...prev,
                      footer: { ...prev.footer, companyName: e.target.value }
                    }))}
                    placeholder="Your Company Name"
                  />
                </div>
                <div>
                  <Label htmlFor="footer-tagline">Tagline</Label>
                  <Input
                    id="footer-tagline"
                    value={settings.footer?.tagline || ''}
                    onChange={(e) => setSettings(prev => ({
                      ...prev,
                      footer: { ...prev.footer, tagline: e.target.value }
                    }))}
                    placeholder="Short tagline under company name"
                  />
                </div>
                <div>
                  <Label htmlFor="footer-desc">Description</Label>
                  <textarea
                    id="footer-desc"
                    value={settings.footer?.description || ''}
                    onChange={(e) => setSettings(prev => ({
                      ...prev,
                      footer: { ...prev.footer, description: e.target.value }
                    }))}
                    rows={3}
                    className="w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"
                    placeholder="Brief description shown in footer"
                  />
                </div>
              </div>
            </Card>

            {/* Contact Info */}
            <Card className="p-6">
              <div className="flex items-center justify-between mb-4">
                <h2 className="text-xl font-semibold">Contact Information</h2>
                <Switch
                  checked={settings.footer?.contactInfo?.show ?? true}
                  onCheckedChange={(checked) => setSettings(prev => ({
                    ...prev,
                    footer: { ...prev.footer, contactInfo: { ...prev.footer?.contactInfo, show: checked } }
                  }))}
                />
              </div>
              <div className="space-y-4">
                <div>
                  <Label htmlFor="footer-phone">Phone Number</Label>
                  <Input
                    id="footer-phone"
                    value={settings.footer?.contactInfo?.phone || ''}
                    onChange={(e) => setSettings(prev => ({
                      ...prev,
                      footer: { ...prev.footer, contactInfo: { ...prev.footer?.contactInfo, phone: e.target.value } }
                    }))}
                    placeholder="+1 (555) 123-4567"
                  />
                </div>
                <div>
                  <Label htmlFor="footer-email">Email Address</Label>
                  <Input
                    id="footer-email"
                    type="email"
                    value={settings.footer?.contactInfo?.email || ''}
                    onChange={(e) => setSettings(prev => ({
                      ...prev,
                      footer: { ...prev.footer, contactInfo: { ...prev.footer?.contactInfo, email: e.target.value } }
                    }))}
                    placeholder="hello@company.com"
                  />
                </div>
                <div>
                  <Label htmlFor="footer-address">Address</Label>
                  <textarea
                    id="footer-address"
                    value={settings.footer?.contactInfo?.address || ''}
                    onChange={(e) => setSettings(prev => ({
                      ...prev,
                      footer: { ...prev.footer, contactInfo: { ...prev.footer?.contactInfo, address: e.target.value } }
                    }))}
                    rows={2}
                    className="w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"
                    placeholder="123 Main St, City, Country"
                  />
                </div>
              </div>
            </Card>

            {/* Link Columns */}
            <Card className="p-6">
              <div className="flex items-center justify-between mb-4">
                <h2 className="text-xl font-semibold">Link Columns</h2>
                <Button
                  variant="outline"
                  size="sm"
                  onClick={() => {
                    const newCol: FooterColumn = {
                      id: `col-${Date.now()}`,
                      title: 'New Column',
                      links: []
                    };
                    setSettings(prev => ({
                      ...prev,
                      footer: { ...prev.footer, columns: [...(prev.footer?.columns || []), newCol] }
                    }));
                  }}
                >
                  <Plus className="h-4 w-4 mr-1" /> Add Column
                </Button>
              </div>
              <div className="space-y-6">
                {(settings.footer?.columns || []).map((col, colIdx) => (
                  <div key={col.id} className="border border-gray-200 dark:border-gray-700 rounded-lg p-4">
                    <div className="flex items-center gap-2 mb-3">
                      <GripVertical className="h-4 w-4 text-gray-400" />
                      <Input
                        value={col.title}
                        onChange={(e) => {
                          const cols = [...settings.footer.columns];
                          cols[colIdx] = { ...cols[colIdx], title: e.target.value };
                          setSettings(prev => ({ ...prev, footer: { ...prev.footer, columns: cols } }));
                        }}
                        className="font-medium"
                        placeholder="Column Title"
                      />
                      <Button
                        variant="outline"
                        size="sm"
                        onClick={() => {
                          const cols = settings.footer.columns.filter((_, i) => i !== colIdx);
                          setSettings(prev => ({ ...prev, footer: { ...prev.footer, columns: cols } }));
                        }}
                      >
                        <Trash2 className="h-4 w-4 text-red-500" />
                      </Button>
                    </div>
                    <div className="space-y-2 ml-6">
                      {col.links.map((link, linkIdx) => (
                        <div key={linkIdx} className="flex items-center gap-2">
                          <Input
                            value={link.label}
                            onChange={(e) => {
                              const cols = [...settings.footer.columns];
                              cols[colIdx].links[linkIdx] = { ...link, label: e.target.value };
                              setSettings(prev => ({ ...prev, footer: { ...prev.footer, columns: cols } }));
                            }}
                            placeholder="Link Label"
                            className="flex-1"
                          />
                          <Input
                            value={link.url}
                            onChange={(e) => {
                              const cols = [...settings.footer.columns];
                              cols[colIdx].links[linkIdx] = { ...link, url: e.target.value };
                              setSettings(prev => ({ ...prev, footer: { ...prev.footer, columns: cols } }));
                            }}
                            placeholder="/url or https://..."
                            className="flex-1"
                          />
                          <Button
                            variant="outline"
                            size="sm"
                            onClick={() => {
                              const cols = [...settings.footer.columns];
                              cols[colIdx].links = cols[colIdx].links.filter((_, i) => i !== linkIdx);
                              setSettings(prev => ({ ...prev, footer: { ...prev.footer, columns: cols } }));
                            }}
                          >
                            <Trash2 className="h-3 w-3 text-red-400" />
                          </Button>
                        </div>
                      ))}
                      <Button
                        variant="outline"
                        size="sm"
                        className="w-full mt-1"
                        onClick={() => {
                          const cols = [...settings.footer.columns];
                          cols[colIdx].links = [...cols[colIdx].links, { label: '', url: '' }];
                          setSettings(prev => ({ ...prev, footer: { ...prev.footer, columns: cols } }));
                        }}
                      >
                        <Plus className="h-3 w-3 mr-1" /> Add Link
                      </Button>
                    </div>
                  </div>
                ))}
              </div>
            </Card>

            {/* Bottom Bar */}
            <Card className="p-6">
              <h2 className="text-xl font-semibold mb-4">Bottom Bar</h2>
              <div className="space-y-4">
                <div className="flex items-center justify-between">
                  <div>
                    <Label>Show Bottom Bar</Label>
                    <p className="text-sm text-gray-500">Display copyright bar at the bottom of footer</p>
                  </div>
                  <Switch
                    checked={settings.footer?.bottomBar?.show ?? true}
                    onCheckedChange={(checked) => setSettings(prev => ({
                      ...prev,
                      footer: { ...prev.footer, bottomBar: { ...prev.footer.bottomBar, show: checked } }
                    }))}
                  />
                </div>
                <div>
                  <Label htmlFor="copyright-text">Copyright Text</Label>
                  <Input
                    id="copyright-text"
                    value={settings.footer?.bottomBar?.copyrightText || ''}
                    onChange={(e) => setSettings(prev => ({
                      ...prev,
                      footer: { ...prev.footer, bottomBar: { ...prev.footer.bottomBar, copyrightText: e.target.value } }
                    }))}
                    placeholder="© {year} Company. All rights reserved."
                  />
                  <p className="text-xs text-gray-500 mt-1">Use <code className="bg-gray-100 dark:bg-gray-800 px-1 rounded">{'{year}'}</code> for dynamic year</p>
                </div>
                <div className="flex items-center justify-between">
                  <div>
                    <Label>Show Social Links</Label>
                    <p className="text-sm text-gray-500">Display social media icons in bottom bar</p>
                  </div>
                  <Switch
                    checked={settings.footer?.bottomBar?.showSocialLinks ?? true}
                    onCheckedChange={(checked) => setSettings(prev => ({
                      ...prev,
                      footer: { ...prev.footer, bottomBar: { ...prev.footer.bottomBar, showSocialLinks: checked } }
                    }))}
                  />
                </div>
                {settings.footer?.bottomBar?.showSocialLinks && (
                  <div>
                    <div className="flex items-center justify-between mb-2">
                      <Label>Social Links</Label>
                      <Button
                        variant="outline"
                        size="sm"
                        onClick={() => {
                          const newLink: SocialLink = { platform: 'linkedin', url: '' };
                          setSettings(prev => ({
                            ...prev,
                            footer: {
                              ...prev.footer,
                              bottomBar: {
                                ...prev.footer.bottomBar,
                                socialLinks: [...(prev.footer.bottomBar.socialLinks || []), newLink]
                              }
                            }
                          }));
                        }}
                      >
                        <Plus className="h-3 w-3 mr-1" /> Add
                      </Button>
                    </div>
                    <div className="space-y-2">
                      {(settings.footer?.bottomBar?.socialLinks || []).map((social, idx) => (
                        <div key={idx} className="flex items-center gap-2">
                          <select
                            value={social.platform}
                            onChange={(e) => {
                              const links = [...settings.footer.bottomBar.socialLinks];
                              links[idx] = { ...social, platform: e.target.value as SocialLink['platform'] };
                              setSettings(prev => ({
                                ...prev,
                                footer: { ...prev.footer, bottomBar: { ...prev.footer.bottomBar, socialLinks: links } }
                              }));
                            }}
                            className="rounded-md border border-input bg-background px-3 py-2 text-sm"
                          >
                            {['twitter', 'linkedin', 'facebook', 'instagram', 'youtube', 'github'].map(p => (
                              <option key={p} value={p}>{p.charAt(0).toUpperCase() + p.slice(1)}</option>
                            ))}
                          </select>
                          <Input
                            value={social.url}
                            onChange={(e) => {
                              const links = [...settings.footer.bottomBar.socialLinks];
                              links[idx] = { ...social, url: e.target.value };
                              setSettings(prev => ({
                                ...prev,
                                footer: { ...prev.footer, bottomBar: { ...prev.footer.bottomBar, socialLinks: links } }
                              }));
                            }}
                            placeholder="https://..."
                            className="flex-1"
                          />
                          <Button
                            variant="outline"
                            size="sm"
                            onClick={() => {
                              const links = settings.footer.bottomBar.socialLinks.filter((_, i) => i !== idx);
                              setSettings(prev => ({
                                ...prev,
                                footer: { ...prev.footer, bottomBar: { ...prev.footer.bottomBar, socialLinks: links } }
                              }));
                            }}
                          >
                            <Trash2 className="h-3 w-3 text-red-400" />
                          </Button>
                        </div>
                      ))}
                    </div>
                  </div>
                )}
              </div>
            </Card>

            {/* Style Customization */}
            <Card className="p-6">
              <h2 className="text-xl font-semibold mb-4">Style Customization</h2>
              <p className="text-sm text-gray-500 mb-4">Leave empty to use default theme colors</p>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div>
                  <Label htmlFor="footer-bg">Background Color</Label>
                  <div className="flex gap-2 mt-1">
                    <input
                      type="color"
                      value={settings.footer?.style?.backgroundColor || '#f1f5f9'}
                      onChange={(e) => setSettings(prev => ({
                        ...prev,
                        footer: { ...prev.footer, style: { ...prev.footer.style, backgroundColor: e.target.value } }
                      }))}
                      className="h-9 w-12 rounded border border-input cursor-pointer"
                    />
                    <Input
                      id="footer-bg"
                      value={settings.footer?.style?.backgroundColor || ''}
                      onChange={(e) => setSettings(prev => ({
                        ...prev,
                        footer: { ...prev.footer, style: { ...prev.footer.style, backgroundColor: e.target.value } }
                      }))}
                      placeholder="#f1f5f9 or transparent"
                    />
                  </div>
                </div>
                <div>
                  <Label htmlFor="footer-text">Text Color</Label>
                  <div className="flex gap-2 mt-1">
                    <input
                      type="color"
                      value={settings.footer?.style?.textColor || '#475569'}
                      onChange={(e) => setSettings(prev => ({
                        ...prev,
                        footer: { ...prev.footer, style: { ...prev.footer.style, textColor: e.target.value } }
                      }))}
                      className="h-9 w-12 rounded border border-input cursor-pointer"
                    />
                    <Input
                      id="footer-text"
                      value={settings.footer?.style?.textColor || ''}
                      onChange={(e) => setSettings(prev => ({
                        ...prev,
                        footer: { ...prev.footer, style: { ...prev.footer.style, textColor: e.target.value } }
                      }))}
                      placeholder="#475569"
                    />
                  </div>
                </div>
                <div>
                  <Label htmlFor="footer-link">Link Color</Label>
                  <div className="flex gap-2 mt-1">
                    <input
                      type="color"
                      value={settings.footer?.style?.linkColor || '#0f172a'}
                      onChange={(e) => setSettings(prev => ({
                        ...prev,
                        footer: { ...prev.footer, style: { ...prev.footer.style, linkColor: e.target.value } }
                      }))}
                      className="h-9 w-12 rounded border border-input cursor-pointer"
                    />
                    <Input
                      id="footer-link"
                      value={settings.footer?.style?.linkColor || ''}
                      onChange={(e) => setSettings(prev => ({
                        ...prev,
                        footer: { ...prev.footer, style: { ...prev.footer.style, linkColor: e.target.value } }
                      }))}
                      placeholder="#0f172a"
                    />
                  </div>
                </div>
                <div>
                  <Label htmlFor="footer-border">Border Color</Label>
                  <div className="flex gap-2 mt-1">
                    <input
                      type="color"
                      value={settings.footer?.style?.borderColor || '#e2e8f0'}
                      onChange={(e) => setSettings(prev => ({
                        ...prev,
                        footer: { ...prev.footer, style: { ...prev.footer.style, borderColor: e.target.value } }
                      }))}
                      className="h-9 w-12 rounded border border-input cursor-pointer"
                    />
                    <Input
                      id="footer-border"
                      value={settings.footer?.style?.borderColor || ''}
                      onChange={(e) => setSettings(prev => ({
                        ...prev,
                        footer: { ...prev.footer, style: { ...prev.footer.style, borderColor: e.target.value } }
                      }))}
                      placeholder="#e2e8f0"
                    />
                  </div>
                </div>
                <div className="md:col-span-2">
                  <Label htmlFor="footer-padding">Vertical Padding</Label>
                  <Select
                    value={settings.footer?.style?.padding || 'py-12'}
                    onValueChange={(value) => setSettings(prev => ({
                      ...prev,
                      footer: { ...prev.footer, style: { ...prev.footer.style, padding: value } }
                    }))}
                  >
                    <SelectTrigger>
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="py-6">Small (py-6)</SelectItem>
                      <SelectItem value="py-8">Medium (py-8)</SelectItem>
                      <SelectItem value="py-12">Large (py-12) — Default</SelectItem>
                      <SelectItem value="py-16">Extra Large (py-16)</SelectItem>
                      <SelectItem value="py-20">2XL (py-20)</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
              </div>
            </Card>
          </div>
        </TabsContent>
      </Tabs>
    </div>
  );
}