/**
 * Database Seed Script
 * Author: generated by Amazon Q
 * Created: 2024-01-15
 */

import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

async function main() {
  console.log('🌱 Seeding database...');

  // Create admin user
  const hashedPassword = await bcrypt.hash('admin123', 10);
  const adminUser = await prisma.user.upsert({
    where: { email: 'admin@example.com' },
    update: {},
    create: {
      email: 'admin@example.com',
      name: 'Admin User',
      password: hashedPassword,
      role: 'admin',
    },
  });

  console.log('👤 Created admin user:', adminUser.email);

  // Create pages
  const pages = [
    {
      title: 'Home',
      slug: '/en',
      status: 'published',
      language: 'en',
      metaTitle: 'English Website - Home',
      metaDescription: 'Welcome to our English learning platform',
      sections: JSON.stringify([
        {
          id: '1',
          type: 'hero',
          title: 'English Website',
          description: 'Transform your English skills with our comprehensive learning platform',
          order: 1,
        },
      ]),
    },
    {
      title: 'الرئيسية',
      slug: '/ar',
      status: 'published',
      language: 'ar',
      metaTitle: 'موقع اللغة الإنجليزية - الرئيسية',
      metaDescription: 'مرحباً بكم في منصة تعلم اللغة الإنجليزية',
      sections: JSON.stringify([
        {
          id: '1',
          type: 'hero',
          title: 'موقع اللغة الإنجليزية',
          description: 'حوّل مهاراتك في اللغة الإنجليزية مع منصة التعلم الشاملة',
          order: 1,
        },
      ]),
    },
    {
      title: 'App Builder',
      slug: '/en/app-builder',
      status: 'published',
      language: 'en',
      metaTitle: 'App Builder - Build Custom Applications',
      metaDescription: 'Create applications without coding',
      sections: JSON.stringify([
        {
          id: '1',
          type: 'hero',
          title: 'Custom Apps. Zero Heavy Code.',
          description: 'Design responsive internal tools with pages, workflows, reports, roles, and integrations.',
          order: 1,
        },
        {
          id: '2',
          type: 'features',
          title: 'Why App Builder vs. Custom Dev?',
          description: 'Replace ad-hoc spreadsheets and one-off scripts with purpose-built apps.',
          order: 2,
        },
        {
          id: '3',
          type: 'cta',
          title: 'Ready to Build?',
          description: 'Start creating powerful applications today with our intuitive builder.',
          order: 3,
        },
      ]),
    },
  ];

  for (const pageData of pages) {
    const page = await prisma.page.upsert({
      where: { slug: pageData.slug },
      update: pageData,
      create: pageData,
    });
    console.log('📄 Created page:', page.title);
  }

  // Create section templates
  const sectionTemplates = [
    {
      name: 'Hero Section',
      type: 'hero',
      category: 'Headers',
      description: 'Large banner with title, subtitle, and CTA buttons',
      defaultData: JSON.stringify({
        title: 'Your Hero Title',
        subtitle: 'Your Hero Subtitle',
        description: 'Your hero description goes here',
        buttons: [
          { text: 'Get Started', href: '#', variant: 'primary' },
          { text: 'Learn More', href: '#', variant: 'secondary' },
        ],
      }),
    },
    {
      name: 'Feature Grid',
      type: 'features',
      category: 'Content',
      description: 'Grid layout showcasing key features with icons',
      defaultData: JSON.stringify({
        title: 'Our Features',
        description: 'Discover what makes us different',
        items: [
          { title: 'Feature 1', description: 'Feature description', icon: '⭐' },
          { title: 'Feature 2', description: 'Feature description', icon: '🚀' },
          { title: 'Feature 3', description: 'Feature description', icon: '💡' },
        ],
      }),
    },
    {
      name: 'CTA Section',
      type: 'cta',
      category: 'Actions',
      description: 'Call-to-action with form or buttons',
      defaultData: JSON.stringify({
        title: 'Ready to Get Started?',
        description: 'Join thousands of satisfied customers',
        buttons: [
          { text: 'Get Started', href: '#', variant: 'primary' },
        ],
      }),
    },
  ];

  for (const templateData of sectionTemplates) {
    const template = await prisma.sectionTemplate.upsert({
      where: { id: templateData.name.toLowerCase().replace(/\s+/g, '-') },
      update: templateData,
      create: {
        id: templateData.name.toLowerCase().replace(/\s+/g, '-'),
        ...templateData,
      },
    });
    console.log('🧩 Created section template:', template.name);
  }

  console.log('✅ Database seeded successfully!');
}

main()
  .catch((e) => {
    console.error('❌ Error seeding database:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });