/**
 * Dynamic Forms Content Section - Smart Logic Features
 * Author: generated by Amazon Q
 * Created: 2024-12-21
 */

'use client';

import React from 'react';

interface DynamicFormsContentProps {
  data: {
    title: string;
    description: string;
    features: Array<{
      title: string;
      description: string;
    }>;
  };
  style?: any;
}

export default function DynamicFormsContentSection({ data }: DynamicFormsContentProps) {
  return (
    <section className="bg-gradient-to-b from-purple-500/8 to-transparent">
      <div className="mx-auto max-w-7xl px-6 py-16">
        <div className="text-center max-w-3xl mx-auto">
          <h2 className="text-3xl md:text-4xl font-bold text-slate-900 dark:text-white">{data.title}</h2>
          <p className="mt-3 text-slate-600 dark:text-slate-300">{data.description}</p>
        </div>
        <ul className="mt-8 grid md:grid-cols-3 gap-5 text-sm">
          {data.features.map((feature, index) => (
            <li key={index} className="rounded-2xl bg-white dark:bg-white/5 border border-slate-200 dark:border-white/10 p-5 hover:transform hover:-translate-y-1 transition-all duration-300 hover:shadow-lg shadow-sm">
              <h3 className="font-semibold text-slate-900 dark:text-white">{feature.title}</h3>
              <p className="mt-2 text-slate-600 dark:text-slate-300">{feature.description}</p>
            </li>
          ))}
        </ul>
      </div>
    </section>
  );
}