/**
 * Form Builder Why Section - Enterprise Benefits
 * Author: generated by Amazon Q
 * Created: 2024-12-21
 */

'use client';

import React from 'react';

interface FormBuilderWhyProps {
  data: {
    title: string;
    description: string;
    benefits: string[];
  };
  style?: any;
}

export default function FormBuilderWhySection({ data }: FormBuilderWhyProps) {
  return (
    <section className="mx-auto max-w-7xl px-6 py-16">
      <div className="text-center max-w-3xl mx-auto">
        <h2 className="text-3xl md:text-4xl font-bold text-slate-900 dark:text-white">{data.title}</h2>
        <p className="mt-3 text-slate-600 dark:text-slate-300">{data.description}</p>
      </div>
      <ul className="mt-6 text-sm max-w-3xl mx-auto grid sm:grid-cols-2 lg:grid-cols-3 gap-3">
        {data.benefits.map((benefit, index) => {
          const colors = [
            'bg-blue-50 border-blue-200 text-blue-800 dark:bg-white/5 dark:border-white/10 dark:text-slate-300',
            'bg-emerald-50 border-emerald-200 text-emerald-800 dark:bg-white/5 dark:border-white/10 dark:text-slate-300',
            'bg-violet-50 border-violet-200 text-violet-800 dark:bg-white/5 dark:border-white/10 dark:text-slate-300',
            'bg-cyan-50 border-cyan-200 text-cyan-800 dark:bg-white/5 dark:border-white/10 dark:text-slate-300',
            'bg-amber-50 border-amber-200 text-amber-800 dark:bg-white/5 dark:border-white/10 dark:text-slate-300',
            'bg-rose-50 border-rose-200 text-rose-800 dark:bg-white/5 dark:border-white/10 dark:text-slate-300'
          ];
          return (
            <li key={index} className={`p-3 rounded-xl border hover:shadow-sm transition-all ${colors[index % colors.length]}`}>
              {benefit}
            </li>
          );
        })}
      </ul>
    </section>
  );
}