/**
 * Form Builder Governance Section - Security & Compliance
 * Author: generated by Amazon Q
 * Created: 2024-12-21
 */

'use client';

import React from 'react';

interface FormBuilderGovernanceProps {
  data: {
    title: string;
    description: string;
    features: Array<{
      title: string;
      description: string;
    }>;
  };
  style?: any;
}

export default function FormBuilderGovernanceSection({ data }: FormBuilderGovernanceProps) {
  return (
    <section className="mx-auto max-w-7xl px-6 py-16">
      <div className="text-center max-w-3xl mx-auto mb-10">
        <h2 className="text-3xl md:text-4xl font-bold text-slate-900 dark:text-white">{data.title}</h2>
        <p className="mt-3 text-slate-600 dark:text-slate-300">{data.description}</p>
      </div>
      
      <div className="grid md:grid-cols-3 gap-5">
        {data.features.map((feature, index) => {
          const gradients = [
            'bg-gradient-to-br from-red-50 to-red-100 border-red-200 text-red-900',
            'bg-gradient-to-br from-yellow-50 to-yellow-100 border-yellow-200 text-yellow-900',
            'bg-gradient-to-br from-green-50 to-green-100 border-green-200 text-green-900'
          ];
          const textColors = [
            'text-red-700',
            'text-yellow-700',
            'text-green-700'
          ];
          return (
            <div 
              key={index} 
              className={`rounded-2xl border p-5 hover:transform hover:-translate-y-1 transition-all duration-300 hover:shadow-lg shadow-sm lift dark:bg-white/5 dark:border-white/10 ${gradients[index % gradients.length]}`}
            >
              <h3 className="font-semibold mb-2 dark:text-white">{feature.title}</h3>
              <p className={`text-sm mt-2 dark:text-slate-300 ${textColors[index % textColors.length]}`}>{feature.description}</p>
            </div>
          );
        })}
      </div>
    </section>
  );
}