/**
 * IndustriesGridSection
 * Author: generated by Amazon Q
 * Created: 2025-01-01
 * Purpose: 3-column grid of industry cards with emoji, name, description, link.
 *          Optional "more industries" footer row. Supports dark/light mode.
 */

'use client';

import React from 'react';

/* ─── Types ─── */
interface IndustryCard {
  emoji: string;
  iconFaConfig?: { name: string; type: string; size: string; color?: string };
  name: string;
  description: string;
  linkText: string;
  linkHref: string;
}

interface MoreIndustry {
  name: string;
  href: string;
}

interface IndustriesGridData {
  eyebrow?: string;
  title?: string;
  titleHighlight?: string;
  description?: string;
  industries?: IndustryCard[];
  moreLabel?: string;
  moreIndustries?: MoreIndustry[];
  accentColor?: string;
  accentColor2?: string;
}

interface IndustriesGridSectionProps {
  data: IndustriesGridData;
  style?: { backgroundColor?: string; textColor?: string; padding?: string };
  isBuilder?: boolean;
}

const DEFAULT_INDUSTRIES: IndustryCard[] = [
  {
    emoji: '⚡',
    name: 'Oil & Gas',
    description: 'Production operations, maintenance workflows, HSE compliance, and permit-to-work automation for energy sector clients.',
    linkText: 'See solutions',
    linkHref: '#',
  },
  {
    emoji: '🔗',
    name: 'IoT Integration',
    description: 'Connect physical devices and sensors directly to automated workflows. Turn real-world events into process triggers and dashboard data.',
    linkText: 'See solutions',
    linkHref: '#',
  },
  {
    emoji: '🏢',
    name: 'Real Estate',
    description: 'Lease management, property inspection workflows, tenant communication portals, and document management — all in one platform.',
    linkText: 'See solutions',
    linkHref: '#',
  },
  {
    emoji: '🏗️',
    name: 'Construction',
    description: 'Project management, field reporting, subcontractor coordination, and safety compliance workflows for construction operations.',
    linkText: 'See solutions',
    linkHref: '#',
  },
  {
    emoji: '🏥',
    name: 'Healthcare',
    description: 'Patient intake, referral management, care coordination, and administrative workflow automation for healthcare providers.',
    linkText: 'See solutions',
    linkHref: '#',
  },
  {
    emoji: '🚛',
    name: 'Fleet Management',
    description: 'Dispatch management, real-time vehicle tracking, maintenance scheduling, and route optimization for fleet-dependent businesses.',
    linkText: 'See solutions',
    linkHref: '#',
  },
];

const DEFAULT_MORE: MoreIndustry[] = [
  { name: 'Government', href: '#' },
  { name: 'Banking & Finance', href: '#' },
  { name: 'Telecom', href: '#' },
  { name: 'Education', href: '#' },
  { name: 'Manufacturing', href: '#' },
];

export default function IndustriesGridSection({
  data,
  style,
  isBuilder = false,
}: IndustriesGridSectionProps) {
  const {
    eyebrow = 'Industries',
    title = 'Walk into any sector and',
    titleHighlight = 'deliver',
    description = 'IVAFLOW\'s modular architecture adapts to the way any industry operates. One platform covers them all — so your team doesn\'t need industry-specific software for every client.',
    industries = DEFAULT_INDUSTRIES,
    moreLabel = 'Also serving:',
    moreIndustries = DEFAULT_MORE,
    accentColor = '#4F7FFF',
    accentColor2 = '#7B5CFF',
  } = data;

  const gradientLine = `linear-gradient(90deg, transparent, ${accentColor}, ${accentColor2}, transparent)`;

  return (
    <section className="py-[110px] bg-white dark:bg-[rgb(15,23,42)]">
      <div className="max-w-[1180px] mx-auto px-5 md:px-10">

        {/* Header */}
        <div className="text-center mb-14">
          <div
            className="inline-flex items-center gap-2 rounded-full px-4 py-1.5 mb-6 border"
            style={{ background: `rgba(79,127,255,0.08)`, borderColor: `rgba(79,127,255,0.20)` }}
          >
            <span className="w-1.5 h-1.5 rounded-full animate-pulse" style={{ background: accentColor }} />
            <span className="text-[11px] font-semibold tracking-[0.16em] uppercase" style={{ color: accentColor }}>
              {eyebrow}
            </span>
          </div>

          <h2
            className="font-extrabold leading-[1.15] tracking-tight text-slate-900 dark:text-[#F0F2F8] mb-3"
            style={{ fontSize: 'clamp(28px, 4vw, 44px)' }}
          >
            {title}{' '}
            <em
              className="not-italic"
              style={{
                background: `linear-gradient(120deg, ${accentColor}, ${accentColor2})`,
                WebkitBackgroundClip: 'text',
                WebkitTextFillColor: 'transparent',
                backgroundClip: 'text',
              }}
            >
              {titleHighlight}
            </em>{' '}
            — on day one
          </h2>

          <p className="text-[16px] font-light text-slate-500 dark:text-[#C4C9D9] leading-[1.7] max-w-[560px] mx-auto mt-3">
            {description}
          </p>
        </div>

        {/* Grid */}
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3.5 mb-8">
          {industries.map((ind, i) => (
            <div
              key={i}
              className="group relative flex flex-col overflow-hidden rounded-[22px] cursor-pointer transition-all duration-300
                bg-slate-50 dark:bg-[#1A1D24]
                border border-slate-200 dark:border-white/[0.07]
                hover:border-white/[0.14] hover:-translate-y-1
                hover:shadow-[0_16px_44px_rgba(0,0,0,0.35)]
                px-7 py-8"
            >
              {/* Top gradient line on hover */}
              <div
                className="absolute top-0 left-0 right-0 h-[2px] opacity-0 group-hover:opacity-100 transition-opacity duration-300"
                style={{ background: gradientLine }}
              />

              <span className="text-[32px] mb-4 block">
                {ind.iconFaConfig?.name ? (
                  <i
                    className={`${({ solid: 'fas', regular: 'far', light: 'fal', thin: 'fat', duotone: 'fad', brands: 'fab' }[ind.iconFaConfig.type] || 'fas')} fa-${ind.iconFaConfig.name}`}
                    style={{ color: ind.iconFaConfig.color, fontSize: '28px' }}
                    aria-hidden="true"
                  />
                ) : ind.emoji}
              </span>
              <h3 className="font-bold text-[17px] text-slate-900 dark:text-[#F0F2F8] mb-2">
                {ind.name}
              </h3>
              <p className="text-[13px] font-light text-slate-500 dark:text-[#C4C9D9] leading-[1.6] mb-auto pb-5">
                {ind.description}
              </p>
              <a
                href={ind.linkHref}
                className="inline-flex items-center gap-1.5 text-[11.5px] font-semibold transition-all duration-200 group-hover:gap-2.5"
                style={{ color: accentColor }}
                onClick={e => e.stopPropagation()}
              >
                {ind.linkText} <span>→</span>
              </a>
            </div>
          ))}
        </div>

        {/* More industries */}
        {moreIndustries.length > 0 && (
          <p className="text-center text-[13px] text-[#4A4F65]">
            {moreLabel}{' '}
            {moreIndustries.map((m, i) => (
              <React.Fragment key={i}>
                <a
                  href={m.href}
                  className="transition-opacity duration-200 hover:opacity-70"
                  style={{ color: accentColor }}
                >
                  {m.name}
                </a>
                {i < moreIndustries.length - 1 && <span className="mx-1.5 text-[#4A4F65]">·</span>}
              </React.Fragment>
            ))}
            <span className="mx-1.5 text-[#4A4F65]">·</span>
            <a href="#" className="transition-opacity duration-200 hover:opacity-70" style={{ color: accentColor }}>
              View all industries →
            </a>
          </p>
        )}
      </div>
    </section>
  );
}
