/**
 * PlatformModulesBentoSection
 * Author: generated by Amazon Q
 * Created: 2025-01-01
 * Purpose: Bento-grid layout of 6 platform modules — 2 large cards + 4 small cards.
 *          Hover glow, top gradient line, link arrow animation. Dark/light mode.
 */

'use client';

import React from 'react';

/* ─── Types ─── */
interface Module {
  icon: string;
  tag: string;
  title: string;
  description: string;
  linkText: string;
  linkHref: string;
  size: 'large' | 'small';
}

interface PlatformModulesBentoData {
  eyebrow?: string;
  title?: string;
  titleHighlight?: string;
  description?: string;
  modules?: Module[];
  accentColor?: string;
  accentColor2?: string;
}

interface PlatformModulesBentoSectionProps {
  data: PlatformModulesBentoData;
  style?: { backgroundColor?: string; textColor?: string; padding?: string };
  isBuilder?: boolean;
}

const DEFAULT_MODULES: Module[] = [
  {
    size: 'large',
    icon: '⚡',
    tag: 'Workflow Orchestrator',
    title: 'Automate any business process — visually',
    description: 'Map workflows, assign roles, set conditions, and launch automated processes through a drag-and-drop designer. From simple approvals to complex multi-department flows — if your client can describe it, IVAFLOW can run it.',
    linkText: 'Explore Workflows',
    linkHref: '#',
  },
  {
    size: 'large',
    icon: '📝',
    tag: 'Form Builder',
    title: 'Every form your clients will ever need',
    description: 'Design dynamic, multi-step forms with conditional logic, calculated fields, external data connections, and role-based visibility — all from a visual builder. No technical skills required, no limitations on what you can build.',
    linkText: 'Explore Form Builder',
    linkHref: '#',
  },
  {
    size: 'small',
    icon: '🎉',
    tag: 'App Builder',
    title: 'Custom workspaces for every audience',
    description: 'Build dedicated environments for internal teams, external partners, or citizens — each with its own layout, forms, and workflows.',
    linkText: 'Explore',
    linkHref: '#',
  },
  {
    size: 'small',
    icon: '📊',
    tag: 'Reports & Analytics',
    title: 'Real-time visibility for every stakeholder',
    description: 'Live dashboards, KPI tracking, SLA monitoring, and custom reports — built in minutes through a visual designer. No BI specialist needed.',
    linkText: 'Explore',
    linkHref: '#',
  },
  {
    size: 'small',
    icon: '🤖',
    tag: 'AI Agent',
    title: 'Intelligent automation, built in',
    description: 'Connect workflows to AI models for auto-classification, smart responses, and decision support — configured visually, no setup complexity.',
    linkText: 'Explore',
    linkHref: '#',
  },
  {
    size: 'small',
    icon: '🌐',
    tag: 'External Portal',
    title: 'Give the outside world a front door',
    description: 'Citizens, customers, and suppliers get their own branded portal to submit requests, track progress, and interact with your processes in real time.',
    linkText: 'Explore',
    linkHref: '#',
  },
];

/* ─── Single module card ─── */
function ModuleCard({
  mod,
  accentColor,
  accentColor2,
}: {
  mod: Module;
  accentColor: string;
  accentColor2: string;
}) {
  const isLarge = mod.size === 'large';
  const gradientLine = `linear-gradient(90deg, transparent, ${accentColor}, ${accentColor2}, transparent)`;

  return (
    <div
      className={`group relative flex flex-col overflow-hidden rounded-[28px] cursor-pointer transition-all duration-300
        bg-[#1A1D24] dark:bg-[#1A1D24] light:bg-slate-50
        border border-white/[0.07] dark:border-white/[0.07] light:border-slate-200
        hover:border-white/[0.14] hover:-translate-y-1
        hover:shadow-[0_20px_50px_rgba(0,0,0,0.40)]
        ${isLarge ? 'p-9' : 'p-7'}`}
    >
      {/* Top gradient line on hover */}
      <div
        className="absolute top-0 left-0 right-0 h-[2px] opacity-0 group-hover:opacity-100 transition-opacity duration-300"
        style={{ background: gradientLine }}
      />
      {/* Glow orb */}
      <div
        className="pointer-events-none absolute -top-20 -right-20 w-60 h-60 rounded-full opacity-0 group-hover:opacity-100 transition-opacity duration-400"
        style={{ background: `radial-gradient(circle, rgba(79,127,255,0.10) 0%, transparent 70%)` }}
      />

      {/* Icon */}
      <div
        className={`flex items-center justify-center rounded-[15px] bg-[#13151A] border border-white/[0.07] mb-5 flex-shrink-0
          ${isLarge ? 'w-[52px] h-[52px] text-[22px]' : 'w-[42px] h-[42px] text-[18px]'}`}
      >
        {mod.icon}
      </div>

      {/* Tag */}
      <div
        className="text-[10px] font-bold tracking-[0.16em] uppercase mb-2.5"
        style={{ color: accentColor }}
      >
        {mod.tag}
      </div>

      {/* Title */}
      <h3
        className={`font-bold leading-[1.25] tracking-tight text-[#F0F2F8] dark:text-[#F0F2F8] light:text-slate-900 mb-2.5
          ${isLarge ? 'text-[20px]' : 'text-[15px]'}`}
      >
        {mod.title}
      </h3>

      {/* Description */}
      <p
        className={`font-light text-[#8A8FA8] leading-[1.7] mb-auto pb-6
          ${isLarge ? 'text-[13.5px]' : 'text-[12.5px]'}`}
      >
        {mod.description}
      </p>

      {/* Link */}
      <a
        href={mod.linkHref}
        className="inline-flex items-center gap-1.5 text-[12px] font-semibold tracking-[0.04em] transition-all duration-200 group-hover:gap-2.5"
        style={{ color: accentColor }}
        onClick={e => e.stopPropagation()}
      >
        {mod.linkText} <span>→</span>
      </a>
    </div>
  );
}

export default function PlatformModulesBentoSection({
  data,
  style,
  isBuilder = false,
}: PlatformModulesBentoSectionProps) {
  const {
    eyebrow = 'Platform modules',
    title = 'Six powerful modules.',
    titleHighlight = 'Infinite',
    description = 'Each module solves a real business problem on its own. Together, they give your clients a complete operational platform — and give you more to sell on every project.',
    modules = DEFAULT_MODULES,
    accentColor = '#4F7FFF',
    accentColor2 = '#7B5CFF',
  } = data;

  const largeModules = modules.filter(m => m.size === 'large');
  const smallModules = modules.filter(m => m.size === 'small');

  return (
    <section className="pb-[110px] bg-[#07080A] dark:bg-[#07080A] light:bg-white">
      <div className="max-w-[1180px] mx-auto px-5 md:px-10">

        {/* Header */}
        <div className="text-center mb-14">
          <div
            className="inline-flex items-center gap-2 rounded-full px-4 py-1.5 mb-6 border"
            style={{ background: `rgba(79,127,255,0.08)`, borderColor: `rgba(79,127,255,0.20)` }}
          >
            <span className="w-1.5 h-1.5 rounded-full animate-pulse" style={{ background: accentColor }} />
            <span className="text-[11px] font-semibold tracking-[0.16em] uppercase" style={{ color: accentColor }}>
              {eyebrow}
            </span>
          </div>

          <h2
            className="font-extrabold leading-[1.15] tracking-tight text-[#F0F2F8] dark:text-[#F0F2F8] light:text-slate-900 mb-3"
            style={{ fontSize: 'clamp(28px, 4vw, 44px)' }}
          >
            {title}
            <br />
            <em
              className="not-italic"
              style={{
                background: `linear-gradient(120deg, ${accentColor}, ${accentColor2})`,
                WebkitBackgroundClip: 'text',
                WebkitTextFillColor: 'transparent',
                backgroundClip: 'text',
              }}
            >
              {titleHighlight}
            </em>{' '}
            ways to use them.
          </h2>

          <p className="text-[16px] font-light text-[#8A8FA8] leading-[1.7] max-w-[560px] mx-auto mt-3">
            {description}
          </p>
        </div>

        {/* Bento grid */}
        <div className="flex flex-col gap-4">
          {/* Large cards row */}
          {largeModules.length > 0 && (
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {largeModules.map((mod, i) => (
                <ModuleCard key={i} mod={mod} accentColor={accentColor} accentColor2={accentColor2} />
              ))}
            </div>
          )}

          {/* Small cards row */}
          {smallModules.length > 0 && (
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
              {smallModules.map((mod, i) => (
                <ModuleCard key={i} mod={mod} accentColor={accentColor} accentColor2={accentColor2} />
              ))}
            </div>
          )}
        </div>
      </div>
    </section>
  );
}
