/**
 * Product Hero Section - Unified hero with theme support and Font Awesome icons
 * Author: generated by Amazon Q
 * Created: 2024-01-15
 */

'use client';

import { SectionConfig } from '@/lib/page-builder/section-schemas';
import { IconConfig, IconDisplay } from '@/components/ui/IconPicker';
import { getThemeById } from '@/lib/themes/product-hero-themes';
import Image from 'next/image';

interface CardItem {
  icon?: string;
  iconConfig?: IconConfig;
  title: string;
  description: string;
}

interface FeatureItem {
  icon?: string;
  iconConfig?: IconConfig;
  label: string;
}

interface ProductHeroData {
  badge?: string;
  title: string;
  titleHighlight?: string;
  description: string;
  primaryButton: { text: string; href: string };
  secondaryButton: { text: string; href: string };
  footerText?: string;
  badges?: string[];

  // Typography
  titleFontSize?: string;
  descriptionFontSize?: string;

  // Theme
  themeId?: string;
  customBackground?: string;
  customTitleGradientFrom?: string;
  customTitleGradientTo?: string;

  // Section background (image or video covering the whole section)
  sectionBackgroundType?: 'tailwind' | 'image' | 'video';
  sectionBackgroundUrl?: string;
  overlayEnabled?: boolean;
  overlayColor?: string;   // hex color e.g. '#000000'
  overlayOpacity?: number; // 0-100

  rightContentType: 'cards' | 'image' | 'video' | 'placeholder';
  cards?: CardItem[];
  mediaUrl?: string;
  mediaAlt?: string;
  mediaFit?: 'cover' | 'contain' | 'fill' | 'none' | 'scale-down';
  mediaAspectRatio?: string;
  placeholderIcon?: string;
  placeholderIconConfig?: IconConfig;
  placeholderText?: string;
  features?: FeatureItem[];

  // New options
  showMediaBackground?: boolean;
  mediaContainerPadding?: string;

  // Element color overrides when media background is active
  sectionTextColorOverride?: string;
  descriptionColorOverride?: string;
  primaryButtonOverride?: string;
  secondaryButtonOverride?: string;
  badgeColorOverride?: string;

  // Layout options
  leftColumnWidth?: string;
  rightColumnWidth?: string;
  columnGap?: string;
  mediaScale?: string;
}

interface ProductHeroSectionProps {
  section: SectionConfig;
}

export function ProductHeroSection({ section }: ProductHeroSectionProps) {
  const data = section.data as ProductHeroData;
  const style = section.style || {};

  const theme = data.themeId ? getThemeById(data.themeId) : null;
  
  const {
    badge,
    title,
    titleHighlight,
    description,
    primaryButton,
    secondaryButton,
    footerText,
    badges = [],
    titleFontSize = 'text-4xl md:text-5xl lg:text-6xl',
    descriptionFontSize = 'text-lg',
    customBackground,
    customTitleGradientFrom,
    customTitleGradientTo,
    sectionBackgroundType = 'tailwind',
    sectionBackgroundUrl = '',
    overlayEnabled = true,
    overlayColor = '#000000',
    overlayOpacity = 40,
    sectionTextColorOverride = '',
    descriptionColorOverride = '',
    primaryButtonOverride = '',
    secondaryButtonOverride = '',
    badgeColorOverride = '',
    rightContentType = 'cards',
    cards = [],
    mediaUrl,
    mediaAlt = 'Product showcase',
    mediaFit = 'cover',
    mediaAspectRatio = '16/9',
    placeholderIcon,
    placeholderIconConfig,
    placeholderText = 'Product Preview',
    features = [],
    showMediaBackground = true,
    mediaContainerPadding = 'p-6',
    leftColumnWidth = 'lg:w-1/2',
    rightColumnWidth = 'lg:w-1/2',
    columnGap = 'gap-12',
    mediaScale = 'scale-100'
  } = data;

  const hasMediaBackground = (sectionBackgroundType === 'image' || sectionBackgroundType === 'video') && sectionBackgroundUrl;
  const backgroundColor = hasMediaBackground
    ? ''
    : (customBackground || theme?.background || style.backgroundColor || 'bg-gradient-to-br from-indigo-50 via-slate-50 to-cyan-50 dark:from-indigo-950 dark:via-slate-900 dark:to-cyan-950');
  const gradientFrom = customTitleGradientFrom || theme?.titleGradient.from || 'from-indigo-400';
  const gradientTo = customTitleGradientTo || theme?.titleGradient.to || 'to-cyan-400';
  const textColor = hasMediaBackground && sectionTextColorOverride
    ? sectionTextColorOverride
    : (style.textColor || 'text-slate-900 dark:text-white');
  const padding = style.padding || 'py-20 lg:py-32';

  const renderIcon = (icon?: string, iconConfig?: IconConfig) => {
    if (iconConfig) {
      return <IconDisplay icon={iconConfig} className="text-xl" />;
    }
    return <span className="text-xl">{icon || '🎨'}</span>;
  };

  const renderRightContent = () => {
    switch (rightContentType) {
      case 'cards':
        return (
          <div className="rounded-3xl bg-gradient-to-br from-indigo-600/20 to-cyan-500/20 dark:from-indigo-600/20 dark:to-cyan-500/20 p-6 border border-white/10 dark:border-white/10 backdrop-blur-sm">
            <div className="grid sm:grid-cols-2 gap-4">
              {cards.map((item, index) => (
                <div 
                  key={index}
                  className="bg-white/5 dark:bg-white/5 border border-white/10 dark:border-white/10 rounded-2xl p-4 hover:-translate-y-1 transition-transform"
                >
                  <div className="mb-2">{renderIcon(item.icon, item.iconConfig)}</div>
                  <div className="font-semibold text-slate-900 dark:text-white mb-1">{item.title}</div>
                  <p className="text-xs text-slate-600 dark:text-slate-300">{item.description}</p>
                </div>
              ))}
            </div>
          </div>
        );

      case 'image':
        const containerClasses = showMediaBackground 
          ? `rounded-3xl bg-gradient-to-br from-indigo-600/20 to-cyan-500/20 dark:from-indigo-600/20 dark:to-cyan-500/20 ${mediaContainerPadding} border border-white/10 dark:border-white/10 backdrop-blur-sm`
          : '';
        
        return (
          <div className={containerClasses}>
            <div className="relative rounded-2xl overflow-hidden" style={{ aspectRatio: mediaAspectRatio }}>
              {mediaUrl ? (
                <Image src={mediaUrl} alt={mediaAlt} fill className={`object-${mediaFit}`} priority />
              ) : (
                <div className="w-full h-full bg-slate-200 dark:bg-slate-800 flex items-center justify-center">
                  <span className="text-slate-400 dark:text-slate-500">No image</span>
                </div>
              )}
            </div>
            {features.length > 0 && (
              <div className="grid grid-cols-3 gap-3 mt-4">
                {features.map((feature, index) => (
                  <div key={index} className="bg-white/5 dark:bg-white/5 border border-white/10 dark:border-white/10 rounded-xl p-3 text-center hover:-translate-y-1 transition-transform">
                    <div className="mb-1">{renderIcon(feature.icon, feature.iconConfig)}</div>
                    <div className="text-xs text-slate-600 dark:text-slate-300">{feature.label}</div>
                  </div>
                ))}
              </div>
            )}
          </div>
        );

      case 'video':
        return (
          <div className="rounded-3xl bg-gradient-to-br from-indigo-600/20 to-cyan-500/20 dark:from-indigo-600/20 dark:to-cyan-500/20 p-6 border border-white/10 dark:border-white/10 backdrop-blur-sm">
            <div className="relative rounded-2xl overflow-hidden" style={{ aspectRatio: mediaAspectRatio }}>
              {mediaUrl ? (
                <video src={mediaUrl} className={`w-full h-full object-${mediaFit}`} controls autoPlay muted loop />
              ) : (
                <div className="w-full h-full bg-slate-200 dark:bg-slate-800 flex items-center justify-center">
                  <span className="text-slate-400 dark:text-slate-500">No video</span>
                </div>
              )}
            </div>
            {features.length > 0 && (
              <div className="grid grid-cols-3 gap-3 mt-4">
                {features.map((feature, index) => (
                  <div key={index} className="bg-white/5 dark:bg-white/5 border border-white/10 dark:border-white/10 rounded-xl p-3 text-center hover:-translate-y-1 transition-transform">
                    <div className="mb-1">{renderIcon(feature.icon, feature.iconConfig)}</div>
                    <div className="text-xs text-slate-600 dark:text-slate-300">{feature.label}</div>
                  </div>
                ))}
              </div>
            )}
          </div>
        );

      case 'placeholder':
        return (
          <div className="rounded-3xl bg-gradient-to-br from-indigo-600/20 to-cyan-500/20 dark:from-indigo-600/20 dark:to-cyan-500/20 p-6 border border-white/10 dark:border-white/10 backdrop-blur-sm">
            <div className="bg-white/80 dark:bg-slate-800/50 rounded-2xl border border-white/10 dark:border-white/10 flex items-center justify-center mb-4" style={{ aspectRatio: mediaAspectRatio }}>
              <div className="text-center text-slate-600 dark:text-slate-400">
                <div className="text-4xl mb-2">{renderIcon(placeholderIcon, placeholderIconConfig)}</div>
                <p className="text-sm">{placeholderText}</p>
              </div>
            </div>
            {features.length > 0 && (
              <div className="grid grid-cols-3 gap-3">
                {features.map((feature, index) => (
                  <div key={index} className="bg-white/5 dark:bg-white/5 border border-white/10 dark:border-white/10 rounded-xl p-3 text-center hover:-translate-y-1 transition-transform">
                    <div className="mb-1">{renderIcon(feature.icon, feature.iconConfig)}</div>
                    <div className="text-xs text-slate-600 dark:text-slate-300">{feature.label}</div>
                  </div>
                ))}
              </div>
            )}
          </div>
        );

      default:
        return null;
    }
  };

  return (
    <section className={`relative ${backgroundColor} ${textColor} overflow-hidden`}>
      {/* Full-section video background */}
      {sectionBackgroundType === 'video' && sectionBackgroundUrl && (
        <video
          className="absolute inset-0 w-full h-full object-cover"
          src={sectionBackgroundUrl}
          autoPlay
          muted
          loop
          playsInline
        />
      )}

      {/* Full-section image background */}
      {sectionBackgroundType === 'image' && sectionBackgroundUrl && (
        <div
          className="absolute inset-0 bg-cover bg-center bg-no-repeat"
          style={{ backgroundImage: `url(${sectionBackgroundUrl})` }}
        />
      )}

      {/* Color overlay for image/video backgrounds */}
      {hasMediaBackground && overlayEnabled && (
        <div
          className="absolute inset-0"
          style={{
            backgroundColor: overlayColor,
            opacity: overlayOpacity / 100,
          }}
        />
      )}

      <div className="absolute inset-0 bg-gradient-to-r from-indigo-200/30 via-transparent to-cyan-200/30 dark:from-indigo-600/20 dark:via-transparent dark:to-cyan-500/20" />
      
      <div className={`relative max-w-7xl mx-auto px-6 ${padding}`}>
        <div className={`flex flex-col lg:flex-row ${columnGap} items-center`}>
          <div className={`space-y-8 w-full ${leftColumnWidth}`}>
            {badge && (
              <div className={`inline-flex items-center gap-2 px-3 py-1 rounded-full text-xs ${
                hasMediaBackground && badgeColorOverride
                  ? badgeColorOverride
                  : 'bg-white/10 dark:bg-white/10 border border-white/10 dark:border-white/10'
              }`}>
                <span className="w-2 h-2 rounded-full bg-emerald-400 animate-pulse" />
                {badge}
              </div>
            )}
            
            <h1 className={`${titleFontSize} font-extrabold leading-tight`}>
              {title}{titleHighlight && ' '}
              {titleHighlight && (
                <span className={`bg-gradient-to-r ${gradientFrom} ${gradientTo} bg-clip-text text-transparent`}>
                  {titleHighlight}
                </span>
              )}
            </h1>
            
            <p className={`${descriptionFontSize} max-w-xl leading-relaxed ${
              hasMediaBackground && descriptionColorOverride
                ? descriptionColorOverride
                : 'text-slate-600 dark:text-slate-300'
            }`}>
              {description}
            </p>
            
            <div className="flex flex-wrap gap-4">
              <a href={primaryButton.href} className={`px-6 py-3 text-base font-semibold rounded-lg transition-all ${
                hasMediaBackground && primaryButtonOverride
                  ? primaryButtonOverride
                  : 'bg-gradient-to-r from-indigo-600 to-cyan-500 hover:from-indigo-700 hover:to-cyan-600 text-white border-0'
              }`}>
                {primaryButton.text}
              </a>
              <a href={secondaryButton.href} className={`px-6 py-3 text-base font-semibold rounded-lg transition-all ${
                hasMediaBackground && secondaryButtonOverride
                  ? secondaryButtonOverride
                  : 'border border-slate-300 dark:border-slate-600 text-slate-900 dark:text-white hover:bg-slate-100 dark:hover:bg-slate-800'
              }`}>
                {secondaryButton.text}
              </a>
            </div>
            
            {badges.length > 0 && (
              <div className="flex gap-3 flex-wrap">
                {badges.map((badgeText, index) => (
                  <span key={index} className={`px-3 py-1 text-xs rounded-full ${
                    hasMediaBackground && badgeColorOverride
                      ? badgeColorOverride
                      : 'bg-white/10 dark:bg-white/10 border border-white/15 dark:border-white/15 text-slate-600 dark:text-slate-300'
                  }`}>
                    {badgeText}
                  </span>
                ))}
              </div>
            )}
            
            {footerText && (
              <div className={`text-xs ${
                hasMediaBackground && descriptionColorOverride
                  ? descriptionColorOverride
                  : 'text-slate-500 dark:text-slate-400'
              }`}>
                {footerText}
              </div>
            )}
          </div>
          
          <div className={`relative w-full ${rightColumnWidth} transition-transform duration-300 ${mediaScale}`}>
            {renderRightContent()}
          </div>
        </div>
      </div>
    </section>
  );
}
