/**
 * ReportsTableSection
 * Author: generated by Amazon Q
 * Created: 2025-01-01
 */
'use client';
import React from 'react';

interface TableRow { process: string; assignee: string; dueDate: string; sla: string; status: string; statusType: 'green' | 'amber' | 'red' | 'blue'; }

interface ReportsTableSectionData {
  eyebrow?: string;
  title?: string;
  titleGradient?: string;
  description?: string;
  tableTitle?: string;
  rows?: TableRow[];
  mediaUrl?: string;
  mediaObjectFit?: 'cover' | 'contain' | 'fill';
  accentColor?: string;
  accentColor2?: string;
}

interface Props {
  data: ReportsTableSectionData;
  style?: { backgroundColor?: string; textColor?: string; padding?: string };
  isBuilder?: boolean;
}

const DEFAULT_ROWS: TableRow[] = [
  { process: 'Invoice approval', assignee: 'Sara M.', dueDate: 'Today', sla: '4h left', status: 'In progress', statusType: 'amber' },
  { process: 'Customer onboarding', assignee: 'Ali K.', dueDate: 'Tomorrow', sla: 'On track', status: 'On track', statusType: 'green' },
  { process: 'Compliance review', assignee: 'Nour R.', dueDate: 'Yesterday', sla: 'Overdue', status: 'Overdue', statusType: 'red' },
  { process: 'IT access request', assignee: 'Dina H.', dueDate: 'In 3 days', sla: 'On track', status: 'Pending', statusType: 'blue' },
  { process: 'Contract renewal', assignee: 'Omar S.', dueDate: 'Today', sla: '2h left', status: 'In progress', statusType: 'amber' },
];

const STATUS_STYLES = {
  green: 'bg-emerald-100 dark:bg-emerald-500/15 text-emerald-600 dark:text-emerald-400',
  amber: 'bg-amber-100 dark:bg-amber-500/15 text-amber-600 dark:text-amber-400',
  red: 'bg-red-100 dark:bg-red-500/15 text-red-600 dark:text-red-400',
  blue: 'bg-indigo-100 dark:bg-indigo-500/15 text-indigo-600 dark:text-indigo-400',
};

export default function ReportsTableSection({ data, isBuilder = false }: Props) {
  const {
    eyebrow = 'Interactive tables',
    title = 'Rich data —',
    titleGradient = 'instantly actionable',
    description = 'Sort, filter, group, and edit records inline. Conditional formatting highlights what needs attention.',
    tableTitle = 'Active Workflows',
    rows = DEFAULT_ROWS,
    mediaUrl = '',
    mediaObjectFit = 'contain',
    accentColor = '#6366f1',
    accentColor2 = '#818cf8',
  } = data;

  const grad = `linear-gradient(135deg, ${accentColor}, #8b5cf6, #06b6d4)`;
  const isVideo = (url: string) => ['.mp4', '.webm', '.ogg', '.mov'].some(e => url.toLowerCase().includes(e));

  const renderVisual = () => {
    if (mediaUrl) {
      if (isVideo(mediaUrl)) {
        return <video src={mediaUrl} className="w-full rounded-2xl" style={{ maxHeight: 360, objectFit: mediaObjectFit }} autoPlay muted loop playsInline />;
      }
      return <img src={mediaUrl} alt="Table preview" className="w-full rounded-2xl" style={{ maxHeight: 360, objectFit: mediaObjectFit }} />;
    }

    return (
      <div className="rounded-2xl overflow-hidden border border-slate-200 dark:border-white/[0.11] bg-white dark:bg-[#12121e]">
        <div className="flex items-center justify-between px-4 py-3 border-b border-slate-200 dark:border-white/[0.06]">
          <span className="text-[13px] font-semibold text-slate-800 dark:text-white">{tableTitle}</span>
          <span className="text-[11px] text-slate-400 dark:text-[#404060] bg-slate-100 dark:bg-[#0e0e1a] border border-slate-200 dark:border-white/[0.06] rounded px-2 py-1">🔍 Search...</span>
        </div>
        <div className="overflow-x-auto">
          <table className="w-full text-[12px]">
            <thead>
              <tr className="bg-slate-50 dark:bg-[#0e0e1a]">
                {['Process', 'Assignee', 'Due date', 'SLA', 'Status'].map(h => (
                  <th key={h} className="px-3 py-2 text-left font-semibold text-[11px] tracking-[0.04em] uppercase text-slate-400 dark:text-[#404060]">{h}</th>
                ))}
              </tr>
            </thead>
            <tbody>
              {rows.map((r, i) => (
                <tr key={i} className="border-t border-slate-100 dark:border-white/[0.04] hover:bg-slate-50 dark:hover:bg-[#181828] transition-colors">
                  <td className="px-3 py-2.5 text-slate-700 dark:text-[#8080a8]">{r.process}</td>
                  <td className="px-3 py-2.5 text-slate-500 dark:text-[#8080a8]">{r.assignee}</td>
                  <td className="px-3 py-2.5 text-slate-500 dark:text-[#8080a8]">{r.dueDate}</td>
                  <td className="px-3 py-2.5 text-slate-500 dark:text-[#8080a8]">{r.sla}</td>
                  <td className="px-3 py-2.5">
                    <span className={`text-[10px] font-semibold px-2 py-0.5 rounded-full ${STATUS_STYLES[r.statusType]}`}>{r.status}</span>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    );
  };

  return (
    <section className="py-20 md:py-24 bg-white dark:bg-[#080810] border-t border-slate-200 dark:border-white/[0.06]">
      <div className="max-w-[1000px] mx-auto px-5 md:px-8">
        <p className="text-[11px] font-semibold tracking-[0.1em] uppercase mb-3" style={{ color: accentColor2 }}>{eyebrow}</p>
        <h2 className="font-extrabold leading-[1.12] tracking-tight mb-3 text-slate-900 dark:text-white" style={{ fontSize: 'clamp(1.7rem, 3.5vw, 2.5rem)' }}>
          {title}{' '}
          <span style={{ background: grad, WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent', backgroundClip: 'text' }}>{titleGradient}</span>
        </h2>
        <p className="text-[15px] leading-[1.7] text-slate-500 dark:text-[#8080a8] mb-8 max-w-[520px]">{description}</p>
        {renderVisual()}
      </div>
    </section>
  );
}
