/**
 * ReportsIntegrationSection
 * Author: generated by Amazon Q
 * Created: 2025-01-01
 */
'use client';
import React from 'react';

interface IntegrationChip { icon: string; text: string; }

interface ReportsIntegrationSectionData {
  eyebrow?: string;
  title?: string;
  titleGradient?: string;
  description?: string;
  chips?: IntegrationChip[];
  accentColor?: string;
  accentColor2?: string;
}

interface Props {
  data: ReportsIntegrationSectionData;
  style?: { backgroundColor?: string; textColor?: string; padding?: string };
  isBuilder?: boolean;
}

const DEFAULT_CHIPS: IntegrationChip[] = [
  { icon: '⚡', text: 'Forms & Apps' },
  { icon: '⚙', text: 'Workflow engine' },
  { icon: '📋', text: 'SLA tracking' },
  { icon: '🤖', text: 'Script Manager' },
  { icon: '💬', text: 'Communication records' },
  { icon: '✦', text: 'AI insights' },
  { icon: '👥', text: 'Customer portals' },
  { icon: '🔗', text: 'Embedded views' },
];

export default function ReportsIntegrationSection({ data, isBuilder = false }: Props) {
  const {
    eyebrow = 'Seamless integration',
    title = 'Works with',
    titleGradient = 'everything in Ivaflow',
    description = 'Dashboards refresh instantly across every module — no manual syncing, no data silos.',
    chips = DEFAULT_CHIPS,
    accentColor = '#6366f1',
    accentColor2 = '#818cf8',
  } = data;

  const grad = `linear-gradient(135deg, ${accentColor}, #8b5cf6, #06b6d4)`;

  return (
    <section className="py-20 md:py-24 text-center bg-slate-50 dark:bg-[#0e0e1a] border-t border-b border-slate-200 dark:border-white/[0.06]">
      <div className="max-w-[1000px] mx-auto px-5 md:px-8">
        <p className="text-[11px] font-semibold tracking-[0.1em] uppercase mb-3" style={{ color: accentColor2 }}>{eyebrow}</p>
        <h2 className="font-extrabold leading-[1.12] tracking-tight mb-3 text-slate-900 dark:text-white" style={{ fontSize: 'clamp(1.7rem, 3.5vw, 2.5rem)' }}>
          {title}{' '}
          <span style={{ background: grad, WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent', backgroundClip: 'text' }}>{titleGradient}</span>
        </h2>
        <p className="text-[15px] leading-[1.7] text-slate-500 dark:text-[#8080a8] mb-8 max-w-[520px] mx-auto">{description}</p>

        <div className="flex flex-wrap gap-2.5 justify-center">
          {chips.map((c, i) => (
            <div
              key={i}
              className="inline-flex items-center gap-1.5 px-4 py-2 rounded-full text-[12px] font-medium
                bg-white dark:bg-[#12121e]
                border border-slate-200 dark:border-white/[0.11]
                text-slate-600 dark:text-[#8080a8]"
            >
              <span>{c.icon}</span>
              {c.text}
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}
