/**
 * ReportsHeroSection - Reports & Analytics Hero
 * Author: generated by Amazon Q
 * Created: 2025-01-01
 * Purpose: Full-screen hero with animated orbs, grid bg, badge, headline,
 *          CTA buttons, and a media frame (upload/URL/default dashboard preview).
 *          Dark/light mode + fully responsive.
 */

'use client';

import React, { useState, useRef } from 'react';

interface ReportsHeroSectionData {
  badge?: string;
  title?: string;
  titleGradient?: string;
  subtitle?: string;
  primaryButtonText?: string;
  primaryButtonHref?: string;
  secondaryButtonText?: string;
  secondaryButtonHref?: string;
  /* media frame */
  mediaUrl?: string;          // uploaded image/video or embed URL
  mediaType?: 'image' | 'video' | 'embed' | 'default';
  mediaObjectFit?: 'cover' | 'contain' | 'fill';
  /* default dashboard KPIs */
  kpis?: { value: string; label: string; color: string }[];
  accentColor?: string;
  accentColor2?: string;
  cyanColor?: string;
}

interface ReportsHeroSectionProps {
  data: ReportsHeroSectionData;
  style?: { backgroundColor?: string; textColor?: string; padding?: string };
  isBuilder?: boolean;
}

const DEFAULT_KPIS = [
  { value: '94%', label: 'SLA rate', color: '#818cf8' },
  { value: '1.2k', label: 'Tasks done', color: '#06b6d4' },
  { value: '↑18%', label: 'Growth', color: '#10b981' },
  { value: '42', label: 'Alerts', color: '#f59e0b' },
];

const DEFAULT_BARS = [55, 72, 88, 63, 91, 78, 65];

export default function ReportsHeroSection({ data, isBuilder = false }: ReportsHeroSectionProps) {
  const {
    badge = 'Reports & Analytics — Ivaflow',
    title = 'Your data tells a story.',
    titleGradient = 'Start reading it.',
    subtitle = 'Real-time dashboards, automated reports, and AI-powered insights — built visually, with zero code.',
    primaryButtonText = 'Explore demo',
    primaryButtonHref = '#',
    secondaryButtonText = 'Request a demo',
    secondaryButtonHref = '#',
    mediaUrl = '',
    mediaType = 'default',
    mediaObjectFit = 'contain',
    kpis = DEFAULT_KPIS,
    accentColor = '#6366f1',
    accentColor2 = '#818cf8',
    cyanColor = '#06b6d4',
  } = data;

  const grad = `linear-gradient(135deg, ${accentColor}, #8b5cf6, ${cyanColor})`;

  const isVideo = (url: string) =>
    ['.mp4', '.webm', '.ogg', '.mov'].some(e => url.toLowerCase().includes(e));

  const renderMedia = () => {
    if (mediaUrl && mediaType !== 'default') {
      if (mediaType === 'embed') {
        return (
          <iframe
            src={mediaUrl}
            className="w-full h-[280px] md:h-[340px] rounded-b-[18px]"
            frameBorder="0"
            allowFullScreen
          />
        );
      }
      if (isVideo(mediaUrl)) {
        return (
          <video
            src={mediaUrl}
            className="w-full rounded-b-[18px]"
            style={{ maxHeight: 340, objectFit: mediaObjectFit }}
            autoPlay muted loop playsInline
          />
        );
      }
      return (
        <img
          src={mediaUrl}
          alt="Dashboard preview"
          className="w-full rounded-b-[18px]"
          style={{ maxHeight: 340, objectFit: mediaObjectFit }}
        />
      );
    }

    /* Default animated dashboard mock */
    return (
      <div className="p-4 md:p-5">
        <div className="rounded-xl p-4 bg-slate-100 dark:bg-[#0e0e1a] border border-slate-200 dark:border-transparent">
          <div className="flex items-center justify-between mb-4">
            <span className="text-[13px] font-bold text-slate-800 dark:text-white">Analytics Overview</span>
            <span className="text-[10px] font-semibold px-2.5 py-1 rounded-full bg-emerald-100 dark:bg-emerald-500/15 text-emerald-600 dark:text-emerald-400">● Live</span>
          </div>
          <div className="grid grid-cols-4 gap-2 mb-4">
            {kpis.map((k, i) => (
              <div key={i} className="rounded-lg p-2.5 text-center bg-white dark:bg-[#12121e]">
                <div className="text-[15px] md:text-[18px] font-extrabold" style={{ color: k.color }}>{k.value}</div>
                <div className="text-[9px] mt-0.5 text-slate-400 dark:text-[#404060]">{k.label}</div>
              </div>
            ))}
          </div>
          <div className="flex items-end gap-1.5 h-16">
            {DEFAULT_BARS.map((h, i) => (
              <div
                key={i}
                className="flex-1 rounded-t"
                style={{
                  height: `${h}%`,
                  background: i === 2 || i === 4 ? grad : 'rgba(99,102,241,0.2)',
                }}
              />
            ))}
          </div>
        </div>
      </div>
    );
  };

  return (
    <section className="relative min-h-screen flex flex-col overflow-hidden bg-slate-50 dark:bg-[#020617]">
      {/* Orbs */}
      <div className="pointer-events-none absolute inset-0 overflow-hidden">
        <div className="absolute w-[400px] h-[400px] md:w-[500px] md:h-[500px] rounded-full -top-24 -left-24 animate-[drift_8s_ease-in-out_infinite_alternate]"
          style={{ background: `rgba(99,102,241,0.18)`, filter: 'blur(80px)' }} />
        <div className="absolute w-[300px] h-[300px] md:w-[400px] md:h-[400px] rounded-full top-24 -right-16 animate-[drift_8s_ease-in-out_infinite_alternate_-3s]"
          style={{ background: `rgba(6,182,212,0.12)`, filter: 'blur(80px)' }} />
        <div className="absolute w-[250px] h-[250px] md:w-[300px] md:h-[300px] rounded-full bottom-0 left-[40%] animate-[drift_8s_ease-in-out_infinite_alternate_-5s]"
          style={{ background: `rgba(139,92,246,0.1)`, filter: 'blur(80px)' }} />
      </div>

      {/* Grid */}
      <div className="pointer-events-none absolute inset-0"
        style={{
          backgroundImage: `linear-gradient(rgba(99,102,241,0.04) 1px, transparent 1px), linear-gradient(90deg, rgba(99,102,241,0.04) 1px, transparent 1px)`,
          backgroundSize: '60px 60px',
          maskImage: 'radial-gradient(ellipse 80% 80% at 50% 0%, black 40%, transparent 100%)',
        }}
      />

      {/* Content */}
      <div className="relative z-10 flex flex-col items-center justify-center text-center px-5 pt-12 pb-6 flex-1">
        {/* Badge */}
        <div
          className="inline-flex items-center gap-1.5 text-[11px] font-semibold tracking-[0.1em] uppercase rounded-full px-3.5 py-1.5 mb-5"
          style={{ background: 'rgba(99,102,241,0.1)', border: '1px solid rgba(99,102,241,0.25)', color: accentColor }}
        >
          <span className="w-1.5 h-1.5 rounded-full flex-shrink-0" style={{ background: accentColor2, animation: 'rh-pulse 2s infinite' }} />
          {badge}
        </div>

        {/* Headline */}
        <h1 className="font-black leading-[1.06] tracking-[-0.04em] mb-4 text-slate-900 dark:text-white" style={{ fontSize: 'clamp(2rem, 6vw, 4.2rem)', maxWidth: 800 }}>
          {title}
          <span className="block" style={{ background: grad, WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent', backgroundClip: 'text' }}>
            {titleGradient}
          </span>
        </h1>

        <p className="text-[15px] md:text-[16px] leading-[1.7] mb-6 max-w-[500px] text-slate-500 dark:text-[#8080a8]">
          {subtitle}
        </p>

        {/* Buttons */}
        <div className="flex flex-wrap gap-3 justify-center mb-6">
          <a
            href={primaryButtonHref}
            className="inline-flex items-center gap-2 px-6 py-3 rounded-xl text-[14px] font-semibold text-white transition-all duration-200 hover:-translate-y-0.5"
            style={{ background: grad, boxShadow: '0 0 40px rgba(99,102,241,0.35)' }}
          >
            <svg width="12" height="12" viewBox="0 0 24 24" fill="currentColor"><polygon points="5,3 19,12 5,21" /></svg>
            {primaryButtonText}
          </a>
          <a
            href={secondaryButtonHref}
            className="inline-flex items-center gap-2 px-6 py-3 rounded-xl text-[14px] font-medium transition-all duration-200
              text-slate-700 dark:text-white bg-slate-200/60 dark:bg-white/[0.04] border border-slate-300 dark:border-white/[0.12] hover:bg-slate-200 dark:hover:bg-white/[0.08]"
          >
            <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><rect x="3" y="4" width="18" height="18" rx="2" /><line x1="16" y1="2" x2="16" y2="6" /><line x1="8" y1="2" x2="8" y2="6" /><line x1="3" y1="10" x2="21" y2="10" /></svg>
            {secondaryButtonText}
          </a>
        </div>
      </div>

      {/* Media Frame */}
      <div className="relative z-10 w-full max-w-[860px] mx-auto px-4 md:px-8 pb-8">
        <div
          className="rounded-[20px] overflow-hidden bg-white dark:bg-[#12121e] border border-slate-200 dark:border-white/[0.11]"
          style={{ boxShadow: '0 40px 100px rgba(0,0,0,0.12), 0 0 0 1px rgba(99,102,241,0.08)' }}
        >
          {/* Browser bar */}
          <div className="flex items-center gap-2 px-4 py-2.5 border-b border-slate-200 dark:border-white/[0.06] bg-slate-50 dark:bg-white/[0.03]">
            <div className="w-2.5 h-2.5 rounded-full bg-red-500" />
            <div className="w-2.5 h-2.5 rounded-full bg-amber-500" />
            <div className="w-2.5 h-2.5 rounded-full bg-emerald-500" />
            <div className="flex-1 mx-3 h-5 rounded flex items-center px-2.5 text-[10px] bg-slate-100 dark:bg-white/[0.04] border border-slate-200 dark:border-white/[0.06] text-slate-400 dark:text-[#404060]">
              ivaflow.com/dashboard/analytics
            </div>
          </div>
          {renderMedia()}
        </div>
      </div>

      <style>{`
        @keyframes rh-pulse { 0%,100%{opacity:1;transform:scale(1);} 50%{opacity:.5;transform:scale(.8);} }
        @keyframes drift { from{transform:translate(0,0) scale(1);} to{transform:translate(30px,20px) scale(1.08);} }
      `}</style>
    </section>
  );
}
