/**
 * Wall of Features – Full & Customizable Version
 * ClickUp-style Feature Wall (Primary + Secondary)
 * Author: generated by Amazon Q
 * Created: 2024-12-22
 */

'use client';

import React from 'react';
import { WallOfFeaturesConfig } from '@/lib/page-builder/section-schemas';
import { IconDisplay, type IconConfig } from '@/components/ui/IconPicker';

interface Props {
  data: WallOfFeaturesConfig['data'];
  isBuilder?: boolean;
  onEdit?: () => void;
}

type FeatureItem = {
  id: string;
  title: string;
  icon?: string; // Legacy emoji support
  faIcon?: IconConfig; // FontAwesome icon
  kind: 'primary' | 'secondary';
  previewImage?: string;
  imageObjectFit?: string;
  activeColor?: string;
  col: number;
  row: number;
  w?: number;
  h?: number;
};

// Transform schema features to FeatureItem format
function transformFeatures(schemaFeatures: WallOfFeaturesConfig['data']['features']): FeatureItem[] {
  return schemaFeatures.map(feature => ({
    id: feature.id,
    title: feature.title,
    icon: feature.icon,
    faIcon: feature.faIcon,
    kind: feature.size === 'large' ? 'primary' : 'secondary',
    previewImage: feature.image,
    imageObjectFit: feature.imageObjectFit,
    activeColor: feature.activeColor,
    col: feature.position.column,
    row: feature.position.row,
    w: feature.size === 'large' ? 2 : (feature.position.columnSpan || 1),
    h: feature.size === 'large' ? 2 : (feature.position.rowSpan || 1),
  }));
}

// Check if a position is occupied by a large feature
function isPositionOccupied(features: FeatureItem[], row: number, col: number): boolean {
  return features.some(feature => {
    if (feature.w && feature.h && feature.w > 1 && feature.h > 1) {
      // Check if this position falls within the large feature's area
      return (
        row >= feature.row && row < feature.row + feature.h &&
        col >= feature.col && col < feature.col + feature.w
      );
    }
    return false;
  });
}

export function WallOfFeaturesSection({
  data,
  isBuilder = false,
  onEdit,
}: Props) {
  const {
    title = 'Everything you need in one platform',
    subtitle = 'Explore dozens of features working together.',
    features = [],
    backgroundColor = '#e8e8e8',
    tileBackgroundColor = '#ffffff',
    textColor = '#838383',
  } = data;

  /* ---------- Default FULL Feature Set ---------- */
  const defaultFeatures: FeatureItem[] = [
    // Primary features (for preview only - no tiles)
    {
      id: 'tasks',
      title: 'Tasks',
      faIcon: { name: 'list-check', type: 'solid', size: 'lg', color: '#3B82F6' },
      kind: 'primary',
      previewImage: '/images/features/tasks.png',
      col: 1, // Hidden position
      row: 1,
      w: 1,
      h: 1,
    },
    {
      id: 'docs',
      title: 'Docs',
      faIcon: { name: 'file-lines', type: 'solid', size: 'lg', color: '#10B981' },
      kind: 'primary',
      previewImage: '/images/features/docs.png',
      col: 1,
      row: 1,
      w: 1,
      h: 1,
    },
    {
      id: 'goals',
      title: 'Goals',
      faIcon: { name: 'bullseye', type: 'solid', size: 'lg', color: '#F59E0B' },
      kind: 'primary',
      previewImage: '/images/features/goals.png',
      col: 1,
      row: 1,
      w: 1,
      h: 1,
    },
    {
      id: 'chat',
      title: 'Chat',
      faIcon: { name: 'comment', type: 'solid', size: 'lg', color: '#EF4444' },
      kind: 'primary',
      previewImage: '/images/features/chat.png',
      col: 1,
      row: 1,
      w: 1,
      h: 1,
    },

    // Secondary tiles (visible grid) - Complete 10x8 grid
    // Row 1
    { id: 'calendar', title: 'Calendar', faIcon: { name: 'calendar', type: 'solid', size: 'lg', color: '#6B7280', hoverColor: '#3B82F6' }, kind: 'secondary', col: 1, row: 1 },
    { id: 'dashboards', title: 'Dashboards', faIcon: { name: 'chart-line', type: 'solid', size: 'lg', color: '#6B7280', hoverColor: '#10B981' }, kind: 'secondary', col: 2, row: 1 },
    { id: 'whiteboards', title: 'Whiteboards', faIcon: { name: 'chalkboard', type: 'solid', size: 'lg', color: '#6B7280', hoverColor: '#F59E0B' }, kind: 'secondary', col: 3, row: 1 },
    { id: 'forms', title: 'Forms', faIcon: { name: 'wpforms', type: 'brands', size: 'lg', color: '#6B7280', hoverColor: '#8B5CF6' }, kind: 'secondary', col: 4, row: 1 },
    { id: 'automation', title: 'Automation', faIcon: { name: 'robot', type: 'solid', size: 'lg', color: '#6B7280', hoverColor: '#EF4444' }, kind: 'secondary', col: 5, row: 1 },
    { id: 'integrations', title: 'Integrations', faIcon: { name: 'plug', type: 'solid', size: 'lg', color: '#6B7280', hoverColor: '#06B6D4' }, kind: 'secondary', col: 6, row: 1 },
    { id: 'reports', title: 'Reports', faIcon: { name: 'chart-bar', type: 'solid', size: 'lg', color: '#6B7280', hoverColor: '#84CC16' }, kind: 'secondary', col: 7, row: 1 },
    { id: 'analytics', title: 'Analytics', faIcon: { name: 'chart-pie', type: 'solid', size: 'lg', color: '#6B7280', hoverColor: '#F97316' }, kind: 'secondary', col: 8, row: 1 },
    { id: 'ai-assistant', title: 'AI Assistant', faIcon: { name: 'brain', type: 'solid', size: 'lg', color: '#6B7280', hoverColor: '#A855F7' }, kind: 'secondary', col: 9, row: 1 },
    { id: 'notifications', title: 'Notifications', faIcon: { name: 'bell', type: 'solid', size: 'lg', color: '#6B7280', hoverColor: '#EC4899' }, kind: 'secondary', col: 10, row: 1 },

    // Row 2
    { id: 'time-tracking', title: 'Time Tracking', faIcon: { name: 'clock', type: 'solid', size: 'lg', color: '#6B7280', hoverColor: '#3B82F6' }, kind: 'secondary', col: 1, row: 2 },
    { id: 'gantt', title: 'Gantt Charts', faIcon: { name: 'chart-gantt', type: 'solid', size: 'lg', color: '#6B7280', hoverColor: '#10B981' }, kind: 'secondary', col: 2, row: 2 },
    { id: 'kanban', title: 'Kanban', faIcon: { name: 'columns', type: 'solid', size: 'lg', color: '#6B7280', hoverColor: '#F59E0B' }, kind: 'secondary', col: 3, row: 2 },
    { id: 'team-calendar', title: 'Team Calendar', faIcon: { name: 'calendar-days', type: 'solid', size: 'lg', color: '#6B7280', hoverColor: '#8B5CF6' }, kind: 'secondary', col: 4, row: 2 },
    { id: 'workflows', title: 'Workflows', faIcon: { name: 'diagram-project', type: 'solid', size: 'lg', color: '#6B7280', hoverColor: '#EF4444' }, kind: 'secondary', col: 5, row: 2 },
    { id: 'approvals', title: 'Approvals', faIcon: { name: 'check-circle', type: 'solid', size: 'lg', color: '#6B7280', hoverColor: '#06B6D4' }, kind: 'secondary', col: 6, row: 2 },
    { id: 'search', title: 'Search', faIcon: { name: 'magnifying-glass', type: 'solid', size: 'lg', color: '#6B7280', hoverColor: '#84CC16' }, kind: 'secondary', col: 7, row: 2 },
    { id: 'templates', title: 'Templates', faIcon: { name: 'file-lines', type: 'solid', size: 'lg', color: '#6B7280', hoverColor: '#F97316' }, kind: 'secondary', col: 8, row: 2 },
    { id: 'custom-fields', title: 'Custom Fields', faIcon: { name: 'tags', type: 'solid', size: 'lg', color: '#6B7280', hoverColor: '#A855F7' }, kind: 'secondary', col: 9, row: 2 },
    { id: 'permissions', title: 'Permissions', faIcon: { name: 'shield-halved', type: 'solid', size: 'lg', color: '#6B7280', hoverColor: '#EC4899' }, kind: 'secondary', col: 10, row: 2 },

    // Row 3 (center area empty for preview)
    { id: 'workload', title: 'Workload', faIcon: { name: 'scale-balanced', type: 'solid', size: 'lg', color: '#6B7280', hoverColor: '#3B82F6' }, kind: 'secondary', col: 1, row: 3 },
    { id: 'timeline', title: 'Timeline', faIcon: { name: 'timeline', type: 'solid', size: 'lg', color: '#6B7280', hoverColor: '#10B981' }, kind: 'secondary', col: 2, row: 3 },
    { id: 'milestones', title: 'Milestones', faIcon: { name: 'flag-checkered', type: 'solid', size: 'lg', color: '#6B7280', hoverColor: '#F59E0B' }, kind: 'secondary', col: 3, row: 3 },
    // Columns 4-7 empty for preview
    { id: 'dependencies', title: 'Dependencies', faIcon: { name: 'link', type: 'solid', size: 'lg', color: '#6B7280', hoverColor: '#8B5CF6' }, kind: 'secondary', col: 8, row: 3 },
    { id: 'resources', title: 'Resources', faIcon: { name: 'users', type: 'solid', size: 'lg', color: '#6B7280', hoverColor: '#EF4444' }, kind: 'secondary', col: 9, row: 3 },
    { id: 'api', title: 'API', faIcon: { name: 'code', type: 'solid', size: 'lg', color: '#6B7280', hoverColor: '#06B6D4' }, kind: 'secondary', col: 10, row: 3 },

    // Row 4 (center area empty for preview)
    { id: 'goals-okrs', title: 'OKRs', faIcon: { name: 'bullseye', type: 'solid', size: 'lg', color: '#6B7280', hoverColor: '#84CC16' }, kind: 'secondary', col: 1, row: 4 },
    { id: 'sprints', title: 'Sprints', faIcon: { name: 'person-running', type: 'solid', size: 'lg', color: '#6B7280', hoverColor: '#F97316' }, kind: 'secondary', col: 2, row: 4 },
    { id: 'backlogs', title: 'Backlogs', faIcon: { name: 'list-ul', type: 'solid', size: 'lg', color: '#6B7280', hoverColor: '#A855F7' }, kind: 'secondary', col: 3, row: 4 },
    // Columns 4-7 empty for preview
    { id: 'portfolios', title: 'Portfolios', faIcon: { name: 'briefcase', type: 'solid', size: 'lg', color: '#6B7280', hoverColor: '#EC4899' }, kind: 'secondary', col: 8, row: 4 },
    { id: 'budgets', title: 'Budgets', faIcon: { name: 'dollar-sign', type: 'solid', size: 'lg', color: '#6B7280', hoverColor: '#3B82F6' }, kind: 'secondary', col: 9, row: 4 },
    { id: 'invoicing', title: 'Invoicing', faIcon: { name: 'file-invoice', type: 'solid', size: 'lg', color: '#6B7280', hoverColor: '#10B981' }, kind: 'secondary', col: 10, row: 4 },

    // Row 5 (center area empty for preview)
    { id: 'clients', title: 'Clients', faIcon: { name: 'building', type: 'solid', size: 'lg', color: '#6B7280', hoverColor: '#F59E0B' }, kind: 'secondary', col: 1, row: 5 },
    { id: 'projects', title: 'Projects', faIcon: { name: 'folder', type: 'solid', size: 'lg', color: '#6B7280', hoverColor: '#8B5CF6' }, kind: 'secondary', col: 2, row: 5 },
    { id: 'task-lists', title: 'Task Lists', faIcon: { name: 'list-check', type: 'solid', size: 'lg', color: '#6B7280', hoverColor: '#EF4444' }, kind: 'secondary', col: 3, row: 5 },
    // Columns 4-7 empty for preview
    { id: 'files', title: 'Files', faIcon: { name: 'paperclip', type: 'solid', size: 'lg', color: '#6B7280', hoverColor: '#06B6D4' }, kind: 'secondary', col: 8, row: 5 },
    { id: 'comments', title: 'Comments', faIcon: { name: 'comment', type: 'solid', size: 'lg', color: '#6B7280', hoverColor: '#84CC16' }, kind: 'secondary', col: 9, row: 5 },
    { id: 'mentions', title: 'Mentions', faIcon: { name: 'at', type: 'solid', size: 'lg', color: '#6B7280', hoverColor: '#F97316' }, kind: 'secondary', col: 10, row: 5 },

    // Row 6 (center area empty for preview)
    { id: 'email', title: 'Email', faIcon: { name: 'envelope', type: 'solid', size: 'lg', color: '#6B7280', hoverColor: '#A855F7' }, kind: 'secondary', col: 1, row: 6 },
    { id: 'slack', title: 'Slack', faIcon: { name: 'slack', type: 'brands', size: 'lg', color: '#6B7280', hoverColor: '#EC4899' }, kind: 'secondary', col: 2, row: 6 },
    { id: 'zoom', title: 'Zoom', faIcon: { name: 'video', type: 'solid', size: 'lg', color: '#6B7280', hoverColor: '#3B82F6' }, kind: 'secondary', col: 3, row: 6 },
    // Columns 4-7 empty for preview
    { id: 'github', title: 'GitHub', faIcon: { name: 'github', type: 'brands', size: 'lg', color: '#6B7280', hoverColor: '#10B981' }, kind: 'secondary', col: 8, row: 6 },
    { id: 'jira', title: 'Jira', faIcon: { name: 'jira', type: 'brands', size: 'lg', color: '#6B7280', hoverColor: '#F59E0B' }, kind: 'secondary', col: 9, row: 6 },
    { id: 'figma', title: 'Figma', faIcon: { name: 'figma', type: 'brands', size: 'lg', color: '#6B7280', hoverColor: '#8B5CF6' }, kind: 'secondary', col: 10, row: 6 },

    // Row 7
    { id: 'mobile', title: 'Mobile App', faIcon: { name: 'mobile-screen', type: 'solid', size: 'lg', color: '#6B7280', hoverColor: '#EF4444' }, kind: 'secondary', col: 1, row: 7 },
    { id: 'offline', title: 'Offline Mode', faIcon: { name: 'wifi-slash', type: 'solid', size: 'lg', color: '#6B7280', hoverColor: '#06B6D4' }, kind: 'secondary', col: 2, row: 7 },
    { id: 'security', title: 'Security', faIcon: { name: 'shield', type: 'solid', size: 'lg', color: '#6B7280', hoverColor: '#84CC16' }, kind: 'secondary', col: 3, row: 7 },
    { id: 'sso', title: 'SSO', faIcon: { name: 'key', type: 'solid', size: 'lg', color: '#6B7280', hoverColor: '#F97316' }, kind: 'secondary', col: 4, row: 7 },
    { id: 'audit-logs', title: 'Audit Logs', faIcon: { name: 'clipboard-list', type: 'solid', size: 'lg', color: '#6B7280', hoverColor: '#A855F7' }, kind: 'secondary', col: 5, row: 7 },
    { id: 'compliance', title: 'Compliance', faIcon: { name: 'certificate', type: 'solid', size: 'lg', color: '#6B7280', hoverColor: '#EC4899' }, kind: 'secondary', col: 6, row: 7 },
    { id: 'backup', title: 'Backup', faIcon: { name: 'hard-drive', type: 'solid', size: 'lg', color: '#6B7280', hoverColor: '#3B82F6' }, kind: 'secondary', col: 7, row: 7 },
    { id: 'export', title: 'Export', faIcon: { name: 'file-export', type: 'solid', size: 'lg', color: '#6B7280', hoverColor: '#10B981' }, kind: 'secondary', col: 8, row: 7 },
    { id: 'import', title: 'Import', faIcon: { name: 'file-import', type: 'solid', size: 'lg', color: '#6B7280', hoverColor: '#F59E0B' }, kind: 'secondary', col: 9, row: 7 },
    { id: 'support', title: 'Support', faIcon: { name: 'headset', type: 'solid', size: 'lg', color: '#6B7280', hoverColor: '#8B5CF6' }, kind: 'secondary', col: 10, row: 7 },

    // Row 8
    { id: 'training', title: 'Training', faIcon: { name: 'graduation-cap', type: 'solid', size: 'lg', color: '#6B7280', hoverColor: '#EF4444' }, kind: 'secondary', col: 1, row: 8 },
    { id: 'onboarding', title: 'Onboarding', faIcon: { name: 'rocket', type: 'solid', size: 'lg', color: '#6B7280', hoverColor: '#06B6D4' }, kind: 'secondary', col: 2, row: 8 },
    { id: 'webinars', title: 'Webinars', faIcon: { name: 'tv', type: 'solid', size: 'lg', color: '#6B7280', hoverColor: '#84CC16' }, kind: 'secondary', col: 3, row: 8 },
    { id: 'documentation', title: 'Documentation', faIcon: { name: 'book', type: 'solid', size: 'lg', color: '#6B7280', hoverColor: '#F97316' }, kind: 'secondary', col: 4, row: 8 },
    { id: 'tutorials', title: 'Tutorials', faIcon: { name: 'play-circle', type: 'solid', size: 'lg', color: '#6B7280', hoverColor: '#A855F7' }, kind: 'secondary', col: 5, row: 8 },
    { id: 'help-center', title: 'Help Center', faIcon: { name: 'circle-question', type: 'solid', size: 'lg', color: '#6B7280', hoverColor: '#EC4899' }, kind: 'secondary', col: 6, row: 8 },
    { id: 'community', title: 'Community', faIcon: { name: 'users-rectangle', type: 'solid', size: 'lg', color: '#6B7280', hoverColor: '#3B82F6' }, kind: 'secondary', col: 7, row: 8 },
    { id: 'updates', title: 'Updates', faIcon: { name: 'arrows-rotate', type: 'solid', size: 'lg', color: '#6B7280', hoverColor: '#10B981' }, kind: 'secondary', col: 8, row: 8 },
    { id: 'roadmap', title: 'Roadmap', faIcon: { name: 'map', type: 'solid', size: 'lg', color: '#6B7280', hoverColor: '#F59E0B' }, kind: 'secondary', col: 9, row: 8 },
    { id: 'feedback', title: 'Feedback', faIcon: { name: 'comment-dots', type: 'solid', size: 'lg', color: '#6B7280', hoverColor: '#8B5CF6' }, kind: 'secondary', col: 10, row: 8 },
  ];

  // Always show default features if no custom features are configured
  const allFeatures: FeatureItem[] = features.length > 0 && features.some(f => f.title && f.title.trim() !== '')
    ? transformFeatures(features) 
    : defaultFeatures;

  const primaryFeatures = allFeatures.filter((f: FeatureItem) => f.kind === 'primary');
  const visibleFeatures = allFeatures.filter((f: FeatureItem) => f.kind === 'secondary');
  
  // Add small features with images to primary features for preview
  const featuresWithImages = allFeatures.filter((f: FeatureItem) => f.previewImage && f.kind === 'secondary');
  const allPrimaryFeatures = [...primaryFeatures, ...featuresWithImages];

  // Only features with images for rotation
  const featuresWithMedia = allFeatures.filter((f: FeatureItem) => f.previewImage);

  const [active, setActive] = React.useState(featuresWithMedia[0]?.id || '');
  const [userInteracted, setUserInteracted] = React.useState(false);
  const activeFeature = featuresWithMedia.find((f: FeatureItem) => f.id === active);

  /* ---------- Auto Demo ---------- */
  const pauseRef = React.useRef(false);

  React.useEffect(() => {
    if (isBuilder || featuresWithMedia.length === 0) return;

    const id = setInterval(() => {
      if (pauseRef.current) return;

      setActive((prev: string) => {
        const currentIdx = featuresWithMedia.findIndex((f: FeatureItem) => f.id === prev);
        const nextIdx = Math.floor(Math.random() * featuresWithMedia.length);
        return featuresWithMedia[nextIdx].id;
      });
    }, 4000);

    return () => clearInterval(id);
  }, [featuresWithMedia, isBuilder]);

  // Resume auto rotation after user interaction
  React.useEffect(() => {
    if (userInteracted) {
      const timeout = setTimeout(() => {
        setUserInteracted(false);
        pauseRef.current = false;
      }, 3000); // Resume after 3 seconds

      return () => clearTimeout(timeout);
    }
  }, [userInteracted]);

  return (
    <section
      className="relative overflow-hidden py-24 bg-white dark:bg-slate-900"
      onClick={isBuilder ? onEdit : undefined}
    >
      <div className="max-w-7xl mx-auto px-6">
        {/* Header */}
        <div className="text-center mb-16">
          <h2 className="text-5xl md:text-6xl font-bold mb-6 text-gray-900 dark:text-white">
            {title}
          </h2>
          <p className="text-lg text-gray-600 dark:text-gray-300">
            {subtitle}
          </p>
        </div>

        {/* Responsive Grid */}
        <div className="relative mx-auto w-full flex items-center justify-center px-4 sm:px-6 lg:px-8">
          <div className="relative w-fit responsive-grid-wrapper">
          {/* Preview - Center Area (4x4 tiles) - Responsive positioning */}
          <div className="absolute z-20 flex items-center justify-center pointer-events-none preview-container">
            <div className="w-full h-full rounded-2xl bg-white dark:bg-slate-800 shadow-2xl dark:shadow-slate-900/50 overflow-hidden border border-gray-200 dark:border-slate-700">
              {activeFeature?.previewImage && (
                (() => {
                  const isVideo = activeFeature.previewImage.includes('.mp4') || 
                                  activeFeature.previewImage.includes('.webm') || 
                                  activeFeature.previewImage.includes('video/');
                  const objectFit = activeFeature.imageObjectFit || 'fill';
                  
                  if (isVideo) {
                    return (
                      <video
                        key={active}
                        src={activeFeature.previewImage}
                        className={`w-full h-full object-${objectFit} animate-fade`}
                        autoPlay
                        muted
                        loop
                        playsInline
                      />
                    );
                  } else {
                    return (
                      <img
                        key={active}
                        src={activeFeature.previewImage}
                        className={`w-full h-full object-${objectFit} animate-fade`}
                        alt=""
                      />
                    );
                  }
                })()
              )}
            </div>
          </div>

          {/* Grid - Responsive columns/rows */}
          <div
            className="grid relative responsive-feature-grid"
            style={{
              backgroundSize: '138px 127px',
            }}
            data-theme-grid="true"
          >
            {visibleFeatures.map((feature: FeatureItem) => {
              const isLargeFeature = feature.w && feature.w > 1;
              const isActiveFeature = active === feature.id;
              const activeColor = feature.activeColor || '#3B82F6';
              
              // Skip rendering if this position is occupied by a large feature
              if (!isLargeFeature && isPositionOccupied(visibleFeatures, feature.row, feature.col)) {
                return null;
              }
              
              // Responsive column visibility
              // Mobile (< 640px): 6 cols (3-8)
              // Tablet (640-768px): 8 cols (2-9)
              // Desktop (>= 768px): 10 cols (all)
              const isMobileVisible = feature.col >= 3 && feature.col <= 8; // 6 cols
              const isTabletVisible = feature.col >= 2 && feature.col <= 9; // 8 cols
              const visibilityClass = !isMobileVisible ? 'hidden sm:block' : !isTabletVisible ? 'hidden md:block' : '';
              
              return (
                <button
                  key={feature.id}
                  style={{
                    gridColumn: `${feature.col} / span ${feature.w ?? 1}`,
                    gridRow: `${feature.row} / span ${feature.h ?? 1}`,
                    backgroundColor: 'transparent',
                  }}
                  className={`relative z-30 flex flex-col items-center justify-center text-center
                    transition-all duration-200 ${visibilityClass} ${
                      isLargeFeature
                        ? 'border-2 border-gray-400 dark:border-slate-500 rounded-lg'
                        : 'border border-gray-300 dark:border-slate-600'
                    }
                    hover:bg-gray-100 dark:hover:bg-slate-800 hover:border-gray-400 dark:hover:border-slate-500
                    hover:shadow-sm dark:hover:shadow-slate-900/20`}
                  onClick={e => {
                    e.stopPropagation();
                    if (!isBuilder && feature.previewImage) {
                      pauseRef.current = true;
                      setUserInteracted(true);
                      setActive(feature.id);
                    }
                  }}
                >
                  <div className={`mb-1 transition-all duration-200 feature-icon ${
                    isLargeFeature ? 'text-4xl' : 'text-2xl'
                  } ${
                    isActiveFeature && feature.previewImage ? 'font-bold scale-110' : ''
                  }`}
                  style={{
                    color: isActiveFeature && feature.previewImage ? activeColor : undefined
                  }}>
                    {feature.faIcon ? (
                      <IconDisplay 
                        icon={{
                          ...feature.faIcon,
                          color: isActiveFeature && feature.previewImage ? activeColor : feature.faIcon.color,
                          hoverColor: activeColor
                        }} 
                        enableHover={true} 
                      />
                    ) : (
                      feature.icon || '📋'
                    )}
                  </div>
                  <div className={`font-medium transition-all duration-200 feature-title ${
                    isLargeFeature ? 'text-sm' : 'text-xs'
                  } ${
                    isActiveFeature && feature.previewImage ? 'font-bold' : 'text-gray-700 dark:text-gray-300'
                  }`}
                  style={{
                    color: isActiveFeature && feature.previewImage ? activeColor : undefined
                  }}>
                    {feature.title}
                  </div>
                </button>
              );
            })}
          </div>

          {/* Fade edges */}
          <div
            className="pointer-events-none absolute inset-0 z-40"
            data-theme-fade="true"
          />
          </div>
        </div>
      </div>

      {/* Consolidated Styles */}
      <style jsx>{`
        /* Mobile (< 640px): 6 cols (3-8), scale 70% */
        .responsive-grid-wrapper {
          transform: scale(0.7);
          transform-origin: center;
        }
        .responsive-feature-grid {
          grid-template-columns: repeat(10, 138px);
          grid-template-rows: repeat(8, 127px);
        }
        .preview-container {
          left: 414px;
          top: 254px;
          width: 552px;
          height: 508px;
        }
        
        /* Tablet (640-768px): 8 cols (2-9), scale 80% */
        @media (min-width: 640px) {
          .responsive-grid-wrapper {
            transform: scale(0.8);
          }
        }
        
        /* Medium Desktop (768-1024px): 10 cols, scale 90% */
        @media (min-width: 768px) {
          .responsive-grid-wrapper {
            transform: scale(0.9);
          }
        }
        
        /* Large Desktop (>= 1024px): 10 cols, scale 100% */
        @media (min-width: 1024px) {
          .responsive-grid-wrapper {
            transform: scale(1);
          }
        }
        
        [data-theme-grid="true"] {
          background-image: 
            linear-gradient(to right, rgb(209 213 219) 1px, transparent 1px),
            linear-gradient(to bottom, rgb(209 213 219) 1px, transparent 1px);
        }
        :global(.dark) [data-theme-grid="true"] {
          background-image: 
            linear-gradient(to right, rgb(71 85 105) 1px, transparent 1px),
            linear-gradient(to bottom, rgb(71 85 105) 1px, transparent 1px);
        }
        [data-theme-fade="true"] {
          background: 
            linear-gradient(to right, rgb(255 255 255) 0%, transparent 8%, transparent 92%, rgb(255 255 255) 100%),
            linear-gradient(to bottom, rgb(255 255 255) 0%, transparent 10%, transparent 90%, rgb(255 255 255) 100%);
        }
        :global(.dark) [data-theme-fade="true"] {
          background: 
            linear-gradient(to right, rgb(15 23 42) 0%, transparent 8%, transparent 92%, rgb(15 23 42) 100%),
            linear-gradient(to bottom, rgb(15 23 42) 0%, transparent 10%, transparent 90%, rgb(15 23 42) 100%);
        }
        @keyframes fade {
          from {
            opacity: 0;
            transform: scale(0.98);
          }
          to {
            opacity: 1;
            transform: scale(1);
          }
        }
        .animate-fade {
          animation: fade 0.35s ease-out;
        }
        :global(.hover-icon:hover) {
          color: var(--hover-color) !important;
        }
      `}</style>
    </section>
  );
}

export default WallOfFeaturesSection;
