/**
 * PlatformSnapshotPropertyPanel
 * Author: generated by Amazon Q
 * Created: 2025-01-01
 * Purpose: Full visual editor for PlatformSnapshotSection fields
 */

'use client';

import React, { useState } from 'react';
import { SectionConfig } from '@/lib/page-builder/section-schemas';

interface PlatformSnapshotPropertyPanelProps {
  section: SectionConfig;
  onUpdate: (updates: Partial<SectionConfig>) => void;
}

function Field({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <div>
      <label className="block text-xs font-medium text-gray-600 dark:text-gray-400 mb-1">{label}</label>
      {children}
    </div>
  );
}

const inputCls = 'w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-700 text-gray-900 dark:text-white text-sm';
const textareaCls = inputCls + ' resize-none';

function Collapsible({ title, badge, children, defaultOpen = false }: {
  title: string; badge?: string; children: React.ReactNode; defaultOpen?: boolean;
}) {
  const [open, setOpen] = useState(defaultOpen);
  return (
    <div className="border border-gray-200 dark:border-gray-600 rounded-lg overflow-hidden">
      <button type="button" onClick={() => setOpen(o => !o)}
        className="w-full flex items-center justify-between px-3 py-2.5 bg-gray-50 dark:bg-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 transition-colors text-left">
        <span className="text-sm font-medium text-gray-800 dark:text-white flex items-center gap-2">
          {title}
          {badge && <span className="text-xs bg-blue-100 dark:bg-blue-900/40 text-blue-700 dark:text-blue-300 px-2 py-0.5 rounded-full">{badge}</span>}
        </span>
        <span className={`text-gray-400 text-xs transition-transform ${open ? 'rotate-90' : ''}`}>▶</span>
      </button>
      {open && <div className="p-3 space-y-3 bg-white dark:bg-gray-800">{children}</div>}
    </div>
  );
}

export function PlatformSnapshotPropertyPanel({ section, onUpdate }: PlatformSnapshotPropertyPanelProps) {
  const data = section.data as any;
  const update = (patch: Record<string, any>) => onUpdate({ data: { ...data, ...patch } });
  const cards = data.cards ?? [];

  const updateCard = (idx: number, field: string, val: string) => {
    const next = cards.map((c: any, i: number) => i === idx ? { ...c, [field]: val } : c);
    update({ cards: next });
  };

  return (
    <div className="space-y-4">

      <Collapsible title="Section Header" defaultOpen>
        <Field label="Eyebrow">
          <input className={inputCls} value={data.eyebrow ?? ''} onChange={e => update({ eyebrow: e.target.value })} />
        </Field>
        <Field label="Title">
          <input className={inputCls} value={data.title ?? ''} onChange={e => update({ title: e.target.value })} />
        </Field>
        <Field label="Title Highlight (gradient)">
          <input className={inputCls} value={data.titleHighlight ?? ''} onChange={e => update({ titleHighlight: e.target.value })} />
        </Field>
        <Field label="Description">
          <textarea className={textareaCls} rows={3} value={data.description ?? ''} onChange={e => update({ description: e.target.value })} />
        </Field>
      </Collapsible>

      <Collapsible title="Snapshot Cards" badge={`${cards.length}`} defaultOpen>
        {cards.map((card: any, i: number) => (
          <Collapsible key={i} title={`Card ${i + 1}: ${card.title || '(untitled)'}`}>
            <Field label="Title">
              <input className={inputCls} value={card.title ?? ''} onChange={e => updateCard(i, 'title', e.target.value)} />
            </Field>
            <Field label="Description">
              <textarea className={textareaCls} rows={3} value={card.description ?? ''} onChange={e => updateCard(i, 'description', e.target.value)} />
            </Field>
            <Field label="Icon Color (hex)">
              <div className="flex gap-2 items-center">
                <input type="color" value={card.iconColor ?? '#4F7FFF'} onChange={e => updateCard(i, 'iconColor', e.target.value)}
                  className="w-9 h-9 rounded border border-gray-300 dark:border-gray-600 cursor-pointer p-0.5 bg-white dark:bg-gray-700" />
                <input className={inputCls} value={card.iconColor ?? ''} onChange={e => updateCard(i, 'iconColor', e.target.value)} placeholder="#4F7FFF" />
              </div>
            </Field>
            <Field label="Icon Background (rgba)">
              <input className={inputCls} value={card.iconBg ?? ''} onChange={e => updateCard(i, 'iconBg', e.target.value)} placeholder="rgba(79,127,255,0.08)" />
            </Field>
            <Field label="Icon (emoji or FA class)">
              <input className={inputCls} value={card.iconEmoji ?? card.iconFa ?? ''} onChange={e => {
                const val = e.target.value;
                if (val.startsWith('fa') || val.startsWith('fas ') || val.startsWith('far ')) {
                  updateCard(i, 'iconFa', val);
                  updateCard(i, 'iconEmoji', '');
                } else {
                  updateCard(i, 'iconEmoji', val);
                  updateCard(i, 'iconFa', '');
                }
              }} placeholder="⚡ or fas fa-bolt" />
            </Field>
          </Collapsible>
        ))}
        <button type="button"
          onClick={() => update({ cards: [...cards, { title: 'New Card', description: '', iconColor: '#4F7FFF', iconBg: 'rgba(79,127,255,0.08)', iconSvg: '' }] })}
          className="w-full py-2 border border-dashed border-blue-300 dark:border-blue-700 rounded-md text-sm text-blue-600 dark:text-blue-400 hover:bg-blue-50 dark:hover:bg-blue-900/20 transition-colors">
          + Add Card
        </button>
      </Collapsible>

      <Collapsible title="Accent Colors">
        <div className="grid grid-cols-2 gap-2">
          {(['accentColor', 'accentColor2'] as const).map((key, i) => (
            <Field key={key} label={['Primary', 'Secondary'][i]}>
              <div className="flex gap-1 items-center">
                <input type="color" value={data[key] ?? '#4F7FFF'} onChange={e => update({ [key]: e.target.value })}
                  className="w-9 h-9 rounded border border-gray-300 dark:border-gray-600 cursor-pointer p-0.5 bg-white dark:bg-gray-700" />
                <input className={inputCls} value={data[key] ?? ''} onChange={e => update({ [key]: e.target.value })} />
              </div>
            </Field>
          ))}
        </div>
      </Collapsible>

    </div>
  );
}
