/**
 * Preview Modes - Device Mode Selector
 * Purpose: Switch between desktop/tablet/mobile preview modes
 * Author: generated by Amazon Q
 * Created: 2024-01-15
 */

'use client';

import React from 'react';

interface PreviewModesProps {
  mode: 'desktop' | 'tablet' | 'mobile';
  onModeChange: (mode: 'desktop' | 'tablet' | 'mobile') => void;
}

export function PreviewModes({ mode, onModeChange }: PreviewModesProps) {
  const modes = [
    {
      id: 'desktop' as const,
      label: 'Desktop',
      icon: (
        <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9.75 17L9 20l-1 1h8l-1-1-.75-3M3 13h18M5 17h14a2 2 0 002-2V5a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" />
        </svg>
      ),
      width: 'Full Width',
    },
    {
      id: 'tablet' as const,
      label: 'Tablet',
      icon: (
        <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 18h.01M8 21h8a1 1 0 001-1V4a1 1 0 00-1-1H8a1 1 0 00-1 1v16a1 1 0 001 1z" />
        </svg>
      ),
      width: '768px',
    },
    {
      id: 'mobile' as const,
      label: 'Mobile',
      icon: (
        <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 18h.01M7 21h10a2 2 0 002-2V5a2 2 0 00-2-2H7a2 2 0 00-2 2v14a2 2 0 002 2z" />
        </svg>
      ),
      width: '375px',
    },
  ];

  return (
    <div className="h-12 bg-gray-50 dark:bg-gray-800 border-b border-gray-200 dark:border-gray-700 flex items-center justify-center">
      <div className="flex items-center space-x-1 bg-white dark:bg-gray-700 rounded-lg p-1 shadow-sm">
        {modes.map((modeOption) => (
          <button
            key={modeOption.id}
            onClick={() => onModeChange(modeOption.id)}
            className={`flex items-center space-x-2 px-3 py-1.5 rounded-md text-sm font-medium transition-all ${
              mode === modeOption.id
                ? 'bg-blue-100 dark:bg-blue-900/30 text-blue-700 dark:text-blue-300 shadow-sm'
                : 'text-gray-600 dark:text-gray-400 hover:text-gray-900 dark:hover:text-white hover:bg-gray-100 dark:hover:bg-gray-600'
            }`}
            title={`${modeOption.label} - ${modeOption.width}`}
          >
            {modeOption.icon}
            <span>{modeOption.label}</span>
            <span className="text-xs opacity-75">
              {modeOption.width}
            </span>
          </button>
        ))}
      </div>
    </div>
  );
}