/**
 * Property Panel - Right Sidebar
 * Purpose: Edit selected section properties and content
 * Author: generated by Amazon Q
 * Created: 2024-01-15
 */

'use client';

import React from 'react';
import { useForm } from 'react-hook-form';
import { SectionConfig } from '@/lib/page-builder/section-schemas';
import { MediaBrowser } from './MediaBrowser';
import InteractiveFeatureWallPropertyPanel from './InteractiveFeatureWallPropertyPanel';
import { WallOfFeaturesPropertyPanel } from './WallOfFeaturesPropertyPanel';
import { ProductHeroPropertyPanel } from './ProductHeroPropertyPanel';
import { ProcessStepsPropertyPanel } from './ProcessStepsPropertyPanel';
import { WhyAutomateWithUsPropertyPanel } from './WhyAutomateWithUsPropertyPanel';
import {
  ReportsHeroPanelPanel, ReportsWhatYouCanBuildPanel, ReportsChartBuilderPanel,
  ReportsTablePanel, ReportsKanbanPanel, ReportsAIInsightsPanel,
  ReportsDataSourcesPanel, ReportsScalePanel, ReportsIntegrationPanel, ReportsRolesPanel,
} from './ReportsPropertyPanels';
import { PartnerShowcaseHeroPropertyPanel } from './PartnerShowcaseHeroPropertyPanel';
import { PlatformSnapshotPropertyPanel } from './PlatformSnapshotPropertyPanel';
import { PlatformModulesBentoPropertyPanel } from './PlatformModulesBentoPropertyPanel';
import { HowItWorksStepsPropertyPanel } from './HowItWorksStepsPropertyPanel';
import { AutomationEnginePropertyPanel } from './AutomationEnginePropertyPanel';
import { IndustriesGridPropertyPanel } from './IndustriesGridPropertyPanel';
import { SlaIntegrationSplitPropertyPanel } from './SlaIntegrationSplitPropertyPanel';
import { PartnerCtaStripPropertyPanel } from './PartnerCtaStripPropertyPanel';
import { PlatformCapabilitiesPropertyPanel } from './PlatformCapabilitiesPropertyPanel';
import { GovernanceGridPropertyPanel } from './GovernanceGridPropertyPanel';

interface PropertyPanelProps {
  section: SectionConfig;
  onUpdate: (updates: Partial<SectionConfig>) => void;
  onClose: () => void;
}

function ImageUploader({ value, onChange, field, onSettingsChange }: { 
  value: string | any; 
  onChange: (url: string | any, settings?: any) => void; 
  field?: string;
  onSettingsChange?: (settings: any) => void;
}) {
  const [uploading, setUploading] = React.useState(false);
  const [showMediaBrowser, setShowMediaBrowser] = React.useState(false);
  const [showAdvanced, setShowAdvanced] = React.useState(false);
  const [imageSettings, setImageSettings] = React.useState({
    alt: '',
    maxWidth: '',
    maxHeight: '',
    objectFit: 'cover' as 'cover' | 'contain' | 'fill' | 'scale-down' | 'none'
  });

  // Extract alt text and existing settings if they exist
  React.useEffect(() => {
    if (field && field.toLowerCase().includes('alt')) {
      setImageSettings(prev => ({ ...prev, alt: value }));
    } else if (typeof value === 'object' && value !== null && value.src) {
      // Load existing settings from object
      setImageSettings({
        alt: value.alt || '',
        maxWidth: value.maxWidth || '',
        maxHeight: value.maxHeight || '',
        objectFit: value.objectFit || 'cover'
      });
    }
  }, [field, value]);

  const handleUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    setUploading(true);
    try {
      const formData = new FormData();
      formData.append('file', file);
      const token = localStorage.getItem('adminToken');

      const response = await fetch('/api/admin/media', {
        method: 'POST',
        headers: { 'Authorization': `Bearer ${token}` },
        body: formData,
      });

      if (response.ok) {
        const data = await response.json();
        onChange(data.url);
      }
    } catch (error) {
      console.error('Upload failed:', error);
    } finally {
      setUploading(false);
    }
  };

  const isAltField = field && field.toLowerCase().includes('alt');
  const currentValue = typeof value === 'object' && value !== null && value.src ? value.src : value;
  const isImageObject = typeof value === 'object' && value !== null && value.src;

  return (
    <>
      <div className="space-y-2">
        {!isAltField && currentValue && (
          <div className="relative w-full h-32 rounded-lg overflow-hidden border border-gray-300 dark:border-gray-600">
            <img 
              src={currentValue} 
              alt="Preview" 
              className={`w-full h-full object-${imageSettings.objectFit}`}
              style={{
                maxWidth: imageSettings.maxWidth ? `${imageSettings.maxWidth}px` : undefined,
                maxHeight: imageSettings.maxHeight ? `${imageSettings.maxHeight}px` : undefined
              }}
            />
            <button
              onClick={() => onChange('')}
              className="absolute top-1 right-1 p-1 bg-red-600 text-white rounded-full hover:bg-red-700 text-xs"
              title="Remove image"
            >
              ✕
            </button>
          </div>
        )}
        
        {isAltField ? (
          <div>
            <input
              type="text"
              value={value}
              onChange={(e) => onChange(e.target.value)}
              placeholder="Alt text for accessibility"
              className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-700 text-gray-900 dark:text-white text-sm"
            />
          </div>
        ) : (
          <>
            <div className="flex gap-2">
              <input
                type="text"
                value={currentValue}
                onChange={(e) => onChange(e.target.value)}
                placeholder="Image URL or path"
                className="flex-1 px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-700 text-gray-900 dark:text-white text-sm"
              />
              
              <button
                type="button"
                onClick={() => setShowMediaBrowser(true)}
                className="px-3 py-2 bg-purple-600 text-white rounded-md hover:bg-purple-700 text-sm font-medium whitespace-nowrap"
              >
                📚 Browse
              </button>
              
              <label className="px-3 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 cursor-pointer text-sm font-medium whitespace-nowrap">
                {uploading ? '⏳' : '📤'} Upload
                <input type="file" accept="image/*" onChange={handleUpload} className="hidden" disabled={uploading} />
              </label>
            </div>
            
            {currentValue && (
              <button
                type="button"
                onClick={() => setShowAdvanced(!showAdvanced)}
                className="text-xs text-blue-600 dark:text-blue-400 hover:underline"
              >
                {showAdvanced ? '🔽 Hide' : '🔧 Show'} Advanced Settings {isImageObject ? '(Applied)' : ''}
              </button>
            )}
            
            {showAdvanced && currentValue && (
              <div className="space-y-2 p-3 bg-gray-50 dark:bg-gray-700 rounded-md border">
                <div className="grid grid-cols-2 gap-2">
                  <div>
                    <label className="block text-xs font-medium text-gray-700 dark:text-gray-300 mb-1">
                      Max Width (px)
                    </label>
                    <input
                      type="number"
                      value={imageSettings.maxWidth}
                      onChange={(e) => setImageSettings(prev => ({ ...prev, maxWidth: e.target.value }))}
                      placeholder="Auto"
                      className="w-full px-2 py-1 border border-gray-300 dark:border-gray-600 rounded text-xs bg-white dark:bg-gray-800 text-gray-900 dark:text-white"
                    />
                  </div>
                  <div>
                    <label className="block text-xs font-medium text-gray-700 dark:text-gray-300 mb-1">
                      Max Height (px)
                    </label>
                    <input
                      type="number"
                      value={imageSettings.maxHeight}
                      onChange={(e) => setImageSettings(prev => ({ ...prev, maxHeight: e.target.value }))}
                      placeholder="Auto"
                      className="w-full px-2 py-1 border border-gray-300 dark:border-gray-600 rounded text-xs bg-white dark:bg-gray-800 text-gray-900 dark:text-white"
                    />
                  </div>
                </div>
                
                <div>
                  <label className="block text-xs font-medium text-gray-700 dark:text-gray-300 mb-1">
                    Object Fit
                  </label>
                  <select
                    value={imageSettings.objectFit}
                    onChange={(e) => setImageSettings(prev => ({ ...prev, objectFit: e.target.value as any }))}
                    className="w-full px-2 py-1 border border-gray-300 dark:border-gray-600 rounded text-xs bg-white dark:bg-gray-800 text-gray-900 dark:text-white"
                  >
                    <option value="cover">Cover (crop to fill)</option>
                    <option value="contain">Contain (fit inside)</option>
                    <option value="fill">Fill (stretch to fill)</option>
                    <option value="scale-down">Scale Down (smaller of contain/none)</option>
                    <option value="none">None (original size)</option>
                  </select>
                </div>
                
                <div>
                  <label className="block text-xs font-medium text-gray-700 dark:text-gray-300 mb-1">
                    Alt Text
                  </label>
                  <input
                    type="text"
                    value={imageSettings.alt}
                    onChange={(e) => setImageSettings(prev => ({ ...prev, alt: e.target.value }))}
                    placeholder="Describe the image for accessibility"
                    className="w-full px-2 py-1 border border-gray-300 dark:border-gray-600 rounded text-xs bg-white dark:bg-gray-800 text-gray-900 dark:text-white"
                  />
                </div>
                
                <div className="flex gap-2">
                  <button
                    type="button"
                    onClick={() => {
                      // Apply settings to image URL
                      const newImageObject = {
                        src: currentValue,
                        alt: imageSettings.alt || '',
                        maxWidth: imageSettings.maxWidth || null,
                        maxHeight: imageSettings.maxHeight || null,
                        objectFit: imageSettings.objectFit || 'cover'
                      };
                      onChange(newImageObject, imageSettings);
                      onSettingsChange?.(imageSettings);
                    }}
                    className="flex-1 px-2 py-1 bg-green-600 text-white rounded text-xs hover:bg-green-700"
                  >
                    ✓ Apply Settings
                  </button>
                  <button
                    type="button"
                    onClick={() => setImageSettings({ alt: '', maxWidth: '', maxHeight: '', objectFit: 'cover' })}
                    className="px-2 py-1 bg-gray-600 text-white rounded text-xs hover:bg-gray-700"
                  >
                    Reset
                  </button>
                </div>
              </div>
            )}
          </>
        )}
      </div>

      <MediaBrowser
        isOpen={showMediaBrowser}
        onClose={() => setShowMediaBrowser(false)}
        onSelect={(url) => {
          onChange(url);
          setShowMediaBrowser(false);
        }}
        acceptTypes={['image/*', 'video/*']}
      />
    </>
  );
}

function JSONEditor({ section, onUpdate }: { section: SectionConfig; onUpdate: (updates: Partial<SectionConfig>) => void }) {
  const [jsonText, setJsonText] = React.useState(JSON.stringify(section.data, null, 2));
  const [error, setError] = React.useState('');
  const [hasChanges, setHasChanges] = React.useState(false);
  const [showImageHelper, setShowImageHelper] = React.useState(false);
  const sectionIdRef = React.useRef(section.id);

  React.useEffect(() => {
    if (sectionIdRef.current !== section.id) {
      sectionIdRef.current = section.id;
      setJsonText(JSON.stringify(section.data, null, 2));
      setError('');
      setHasChanges(false);
      setShowImageHelper(false);
    }
  }, [section.id]);

  const handleChange = (value: string) => {
    setJsonText(value);
    setHasChanges(true);
    try {
      JSON.parse(value);
      setError('');
    } catch (err) {
      setError('Invalid JSON');
    }
  };

  const handleSave = () => {
    try {
      const newData = JSON.parse(jsonText);
      console.log('🔄 Updating section data:', newData);
      onUpdate({ data: newData });
      setError('');
      setHasChanges(false);
      console.log('✅ Section updated successfully');
    } catch (err) {
      console.error('❌ Save error:', err);
      setError('Cannot save - Invalid JSON');
    }
  };

  const handleImageUpload = (field: string, urlOrObject: string | any, settings?: any) => {
    try {
      const data = JSON.parse(jsonText);
      const keys = field.split('.');
      let obj = data;
      
      // Handle array notation like slides[0].mediaSrc
      for (let i = 0; i < keys.length - 1; i++) {
        const key = keys[i];
        const arrayMatch = key.match(/^(.+)\[(\d+)\]$/);
        
        if (arrayMatch) {
          const [, arrayName, index] = arrayMatch;
          const idx = parseInt(index);
          
          if (!obj[arrayName]) obj[arrayName] = [];
          if (!obj[arrayName][idx]) obj[arrayName][idx] = {};
          obj = obj[arrayName][idx];
        } else {
          if (obj[key] === undefined || obj[key] === null || typeof obj[key] !== 'object') {
            obj[key] = {};
          }
          obj = obj[key];
        }
      }
      
      // Set the final value
      const finalKey = keys[keys.length - 1];
      
      // If it's already an object with settings, use it directly
      if (typeof urlOrObject === 'object' && urlOrObject !== null && urlOrObject.src) {
        obj[finalKey] = urlOrObject;
        
        // Also set alt field if it exists
        const altKey = finalKey.replace(/image|img|media|src/i, 'Alt').replace(/Alt$/, 'Alt');
        if (altKey !== finalKey && urlOrObject.alt) {
          obj[altKey] = urlOrObject.alt;
        }
      } else {
        // It's a simple string URL
        obj[finalKey] = urlOrObject;
      }
      
      // Clean up any duplicate entries like slides[0] at root level
      const newData = { ...data };
      Object.keys(newData).forEach(key => {
        if (key.match(/^slides\[\d+\]$/)) {
          delete newData[key];
        }
      });
      
      const newJson = JSON.stringify(newData, null, 2);
      setJsonText(newJson);
      setHasChanges(true);
    } catch (err) {
      console.error('Failed to update image:', err);
    }
  };

  const imageFields = React.useMemo(() => {
    try {
      const data = JSON.parse(jsonText);
      const fields: Array<{ path: string; value: string }> = [];
      
      const findImageFields = (obj: any, prefix = '', parentKey = '') => {
        for (const key in obj) {
          const path = prefix ? `${prefix}.${key}` : key;
          const value = obj[key];
          
          if (typeof value === 'string') {
            const isImageKey = key.toLowerCase().includes('image') || 
                              key.toLowerCase().includes('img') || 
                              key.toLowerCase().includes('media') || 
                              key.toLowerCase().includes('icon') ||
                              key.toLowerCase().includes('logo') ||
                              key.toLowerCase().includes('background') ||
                              key.toLowerCase().includes('preview') ||
                              key.toLowerCase().includes('poster') ||
                              key.toLowerCase().includes('video') ||
                              key === 'mediaSrc' ||
                              key === 'mediaPoster' ||
                              key === 'videoSrc';
            const isImageUrl = value.match(/\.(jpg|jpeg|png|gif|webp|svg|ico|mp4|webm|mov)/i) || 
                              value.startsWith('/uploads/') ||
                              value.startsWith('/api/media/') ||
                              value.startsWith('http') ||
                              value === '';
            
            if (isImageKey || (key.toLowerCase().includes('url') && isImageUrl) || (key.toLowerCase().includes('src') && isImageUrl)) {
              fields.push({ path, value });
            }
          } else if (typeof value === 'object' && value !== null && value.src) {
            // Handle image objects with settings
            const isImageKey = key.toLowerCase().includes('image') || 
                              key.toLowerCase().includes('img') || 
                              key.toLowerCase().includes('media') || 
                              key.toLowerCase().includes('icon') ||
                              key.toLowerCase().includes('logo') ||
                              key.toLowerCase().includes('background') ||
                              key.toLowerCase().includes('preview') ||
                              key.toLowerCase().includes('poster') ||
                              key.toLowerCase().includes('video') ||
                              key === 'mediaSrc' ||
                              key === 'mediaPoster' ||
                              key === 'videoSrc';
            
            if (isImageKey) {
              fields.push({ path, value });
            }
          } else if (Array.isArray(value)) {
            value.forEach((item, idx) => {
              if (typeof item === 'object' && item !== null) {
                findImageFields(item, `${path}[${idx}]`, key);
              }
            });
          } else if (typeof value === 'object' && value !== null) {
            findImageFields(value, path, key);
          }
        }
      };
      
      findImageFields(data);
      return fields;
    } catch {
      return [];
    }
  }, [jsonText]);

  return (
    <div className="space-y-4">
      <div className="bg-blue-50 dark:bg-blue-900/20 border border-blue-200 dark:border-blue-800 rounded-lg p-3">
        <p className="text-sm text-blue-800 dark:text-blue-200">
          ✏️ Edit JSON and click Save to apply changes
        </p>
      </div>
      
      {imageFields.length > 0 && (
        <div>
          <button
            type="button"
            onClick={() => setShowImageHelper(!showImageHelper)}
            className="w-full px-3 py-2 bg-purple-100 dark:bg-purple-900/20 text-purple-700 dark:text-purple-300 rounded-md text-sm font-medium hover:bg-purple-200 dark:hover:bg-purple-900/30 transition-colors"
          >
            {showImageHelper ? '🖼️ Hide' : '🖼️ Show'} Image Manager ({imageFields.length})
          </button>
          {showImageHelper && (
            <div className="mt-2 space-y-3 max-h-80 overflow-y-auto p-3 bg-gray-50 dark:bg-gray-700 rounded-lg">
              <div className="text-xs text-gray-600 dark:text-gray-400 mb-2 p-2 bg-blue-50 dark:bg-blue-900/20 rounded border">
                📝 <strong>Image Manager Tips:</strong><br/>
                • Alt fields: Only accept text for accessibility<br/>
                • Image fields: Upload/browse images + advanced settings<br/>
                • Use object-fit to control how images scale<br/>
                • Set max dimensions to limit image size
              </div>
              {imageFields.map((field) => (
                <div key={field.path}>
                  <label className="block text-xs font-medium text-gray-700 dark:text-gray-300 mb-1">
                    {field.path}
                  </label>
                  <ImageUploader
                    value={field.value}
                    onChange={(urlOrObject, settings) => handleImageUpload(field.path, urlOrObject, settings)}
                    field={field.path}
                  />
                </div>
              ))}
            </div>
          )}
        </div>
      )}
      {error && (
        <div className="bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 rounded-lg p-3">
          <p className="text-sm font-medium text-red-800 dark:text-red-200">⚠️ {error}</p>
        </div>
      )}
      <div>
        <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
          Section Data (JSON)
        </label>
        <textarea
          value={jsonText}
          onChange={(e) => handleChange(e.target.value)}
          rows={18}
          className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-700 text-gray-900 dark:text-white font-mono text-xs"
          spellCheck={false}
        />
      </div>
      <button
        onClick={handleSave}
        disabled={!!error || !hasChanges}
        className="w-full px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 disabled:bg-gray-400 disabled:cursor-not-allowed font-medium transition-colors"
      >
        {hasChanges ? '💾 Save Changes' : '✓ Saved'}
      </button>
    </div>
  );
}

export function PropertyPanel({ section, onUpdate, onClose }: PropertyPanelProps) {
  const { register, handleSubmit, watch, setValue } = useForm<any>({
    defaultValues: {
      ...section.data,
      style: section.style || {},
    },
  });

  const watchedValues = watch();
  const [editMode, setEditMode] = React.useState<'visual' | 'json'>('visual');

  // Update section when form values change (only for form-based sections)
  React.useEffect(() => {
    if (section.type === 'hero' || section.type === 'features' || section.type === 'cta') {
      const { style, ...data } = watchedValues;
      onUpdate({
        data: data as any,
        style: style as any,
      });
    }
  }, [watchedValues, onUpdate, section.type]);

  // Check if section has custom visual editor
  const hasCustomEditor = [
    'product-hero', 'process-steps', 'why-automate-with-us',
    'reports-hero', 'reports-what-you-can-build', 'reports-chart-builder',
    'reports-table', 'reports-kanban', 'reports-ai-insights',
    'reports-data-sources', 'reports-scale', 'reports-integration', 'reports-roles',
    'partner-showcase-hero', 'platform-snapshot', 'platform-modules-bento',
    'how-it-works-steps', 'automation-engine', 'industries-grid',
    'sla-integration-split', 'partner-cta-strip', 'platform-capabilities',
    'interactive-feature-wall', 'wall-of-features', 'governance-grid'
  ].includes(section.type);

  const renderSectionSpecificFields = () => {
    switch (section.type) {
      case 'product-hero':
        return <ProductHeroPropertyPanel section={section} onUpdate={onUpdate} />;
      case 'process-steps':
        return <ProcessStepsPropertyPanel section={section} onUpdate={onUpdate} />;
      case 'why-automate-with-us':
        return <WhyAutomateWithUsPropertyPanel section={section} onUpdate={onUpdate} />;
      case 'reports-hero':
        return <ReportsHeroPanelPanel section={section} onUpdate={onUpdate} />;
      case 'reports-what-you-can-build':
        return <ReportsWhatYouCanBuildPanel section={section} onUpdate={onUpdate} />;
      case 'reports-chart-builder':
        return <ReportsChartBuilderPanel section={section} onUpdate={onUpdate} />;
      case 'reports-table':
        return <ReportsTablePanel section={section} onUpdate={onUpdate} />;
      case 'reports-kanban':
        return <ReportsKanbanPanel section={section} onUpdate={onUpdate} />;
      case 'reports-ai-insights':
        return <ReportsAIInsightsPanel section={section} onUpdate={onUpdate} />;
      case 'reports-data-sources':
        return <ReportsDataSourcesPanel section={section} onUpdate={onUpdate} />;
      case 'reports-scale':
        return <ReportsScalePanel section={section} onUpdate={onUpdate} />;
      case 'reports-integration':
        return <ReportsIntegrationPanel section={section} onUpdate={onUpdate} />;
      case 'reports-roles':
        return <ReportsRolesPanel section={section} onUpdate={onUpdate} />;
      case 'partner-showcase-hero':
        return <PartnerShowcaseHeroPropertyPanel section={section} onUpdate={onUpdate} />;
      case 'platform-snapshot':
        return <PlatformSnapshotPropertyPanel section={section} onUpdate={onUpdate} />;
      case 'platform-modules-bento':
        return <PlatformModulesBentoPropertyPanel section={section} onUpdate={onUpdate} />;
      case 'how-it-works-steps':
        return <HowItWorksStepsPropertyPanel section={section} onUpdate={onUpdate} />;
      case 'automation-engine':
        return <AutomationEnginePropertyPanel section={section} onUpdate={onUpdate} />;
      case 'industries-grid':
        return <IndustriesGridPropertyPanel section={section} onUpdate={onUpdate} />;
      case 'sla-integration-split':
        return <SlaIntegrationSplitPropertyPanel section={section} onUpdate={onUpdate} />;
      case 'partner-cta-strip':
        return <PartnerCtaStripPropertyPanel section={section} onUpdate={onUpdate} />;
      case 'platform-capabilities':
        return <PlatformCapabilitiesPropertyPanel section={section} onUpdate={onUpdate} />;
      case 'interactive-feature-wall':
        return <InteractiveFeatureWallPropertyPanel section={section} onUpdate={onUpdate} />;
      case 'wall-of-features':
        return <WallOfFeaturesPropertyPanel section={section} onUpdate={onUpdate} />;
      case 'governance-grid':
        return <GovernanceGridPropertyPanel section={section} onUpdate={onUpdate} />;
      case 'hero-slider':
        return (
          <>
            <div className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                  Global Min Height
                </label>
                <input
                  type="text"
                  {...register('globalMinHeight')}
                  placeholder="90vh, 600px, 100%"
                  className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-700 text-gray-900 dark:text-white"
                />
              </div>
              
              <div>
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                  Autoplay
                </label>
                <label className="flex items-center">
                  <input
                    type="checkbox"
                    {...register('autoplay')}
                    className="mr-2"
                  />
                  <span className="text-sm">Enable automatic slide transitions</span>
                </label>
              </div>
              
              <div>
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                  Interval (ms)
                </label>
                <input
                  type="number"
                  {...register('interval')}
                  min="1000"
                  step="500"
                  className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-700 text-gray-900 dark:text-white"
                />
              </div>
              
              <div className="bg-blue-50 dark:bg-blue-900/20 border border-blue-200 dark:border-blue-800 rounded-lg p-3">
                <p className="text-sm text-blue-800 dark:text-blue-200">
                  💡 <strong>Height Controls:</strong><br/>
                  • <code>globalMinHeight</code> - Default height for all slides<br/>
                  • Per-slide <code>minHeight</code> - Overrides global setting<br/>
                  • Values: "90vh", "600px", "100%", etc.<br/><br/>
                  <strong>Per-Slide Settings:</strong><br/>
                  Use the JSON editor below to configure individual slides. Each slide can have:
                  <br/>• <code>useImageInsteadOfCard: true</code> - Replace card with image
                  <br/>• <code>cardImage: "path/to/image.jpg"</code> - Image to display
                  <br/>• <code>minHeight: "80vh"</code> - Custom height for this slide
                  <br/>• Standard card content (title, description, buttons, etc.)
                </p>
              </div>
            </div>
            <JSONEditor section={section} onUpdate={onUpdate} />
          </>
        );

      case 'hero-slider-nwm':
        return (
          <>
            <div className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                  Autoplay Interval (ms)
                </label>
                <input
                  type="number"
                  {...register('autoPlayInterval')}
                  min="1000"
                  step="500"
                  className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-700 text-gray-900 dark:text-white"
                />
              </div>
              
              <div className="bg-blue-50 dark:bg-blue-900/20 border border-blue-200 dark:border-blue-800 rounded-lg p-3">
                <p className="text-sm text-blue-800 dark:text-blue-200">
                  💡 <strong>Per-Slide Image Settings:</strong><br/>
                  Use JSON editor below to configure each slide:
                  <br/>• <code>useImageInsteadOfCard: true</code> - Show image instead of card
                  <br/>• <code>cardImage: "path/to/image.jpg"</code> - Image path
                  <br/>• <code>cardImageWidth: 600</code> - Image width in pixels (default: 600)
                  <br/>• <code>cardImageHeight: 400</code> - Image height in pixels (default: 400)
                  <br/>• <code>enableMagnifier: true</code> - Enable zoom on hover (default: false)
                </p>
              </div>
            </div>
            <JSONEditor section={section} onUpdate={onUpdate} />
          </>
        );

      case 'hero':
        return (
          <>
            <div className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                  Title
                </label>
                <input
                  {...register('title')}
                  className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-700 text-gray-900 dark:text-white"
                />
              </div>
              
              <div>
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                  Subtitle
                </label>
                <input
                  {...register('subtitle')}
                  className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-700 text-gray-900 dark:text-white"
                />
              </div>
              
              <div>
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                  Description
                </label>
                <textarea
                  {...register('description')}
                  rows={3}
                  className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-700 text-gray-900 dark:text-white"
                />
              </div>
            </div>
          </>
        );

      case 'features':
        return (
          <>
            <div className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                  Title
                </label>
                <input
                  {...register('title')}
                  className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-700 text-gray-900 dark:text-white"
                />
              </div>
              
              <div>
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                  Subtitle
                </label>
                <input
                  {...register('subtitle')}
                  className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-700 text-gray-900 dark:text-white"
                />
              </div>
              
              <div>
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                  Description
                </label>
                <textarea
                  {...register('description')}
                  rows={2}
                  className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-700 text-gray-900 dark:text-white"
                />
              </div>
            </div>
          </>
        );

      case 'cta':
        return (
          <>
            <div className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                  Title
                </label>
                <input
                  {...register('title')}
                  className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-700 text-gray-900 dark:text-white"
                />
              </div>
              
              <div>
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                  Description
                </label>
                <textarea
                  {...register('description')}
                  rows={2}
                  className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-700 text-gray-900 dark:text-white"
                />
              </div>
            </div>
          </>
        );

      default:
        return <JSONEditor section={section} onUpdate={onUpdate} />;
    }
  };

  return (
    <div className="w-96 bg-white dark:bg-gray-800 border-l border-gray-200 dark:border-gray-700 flex flex-col">
      {/* Header */}
      <div className="p-4 border-b border-gray-200 dark:border-gray-700 flex items-center justify-between">
        <h2 className="text-lg font-semibold text-gray-900 dark:text-white">
          Edit Section
        </h2>
        <button
          onClick={onClose}
          className="p-1 rounded-md hover:bg-gray-100 dark:hover:bg-gray-700 text-gray-500 dark:text-gray-400"
        >
          <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      </div>

      {/* Content */}
      <div className="flex-1 overflow-y-auto">
        <form className="p-4 space-y-6">
          {/* Section Info */}
          <div className="bg-gray-50 dark:bg-gray-700 rounded-lg p-3">
            <div className="flex items-center space-x-2 mb-2">
              <span className="text-2xl">
                {section.type === 'hero' ? '🎯' : 
                 section.type === 'features' ? '⭐' :
                 section.type === 'cta' ? '🚀' :
                 section.type === 'tabs' ? '📑' :
                 section.type === 'faq' ? '❓' : '📄'}
              </span>
              <span className="font-medium text-gray-900 dark:text-white capitalize">
                {section.type} Section
              </span>
            </div>
            <p className="text-sm text-gray-600 dark:text-gray-400">
              Configure the content and appearance of this section
            </p>
          </div>

          {/* Edit Mode Toggle (for sections with custom editors) */}
          {hasCustomEditor && (
            <div className="bg-gradient-to-r from-blue-50 to-purple-50 dark:from-blue-900/20 dark:to-purple-900/20 rounded-lg p-3 border border-blue-200 dark:border-blue-800">
              <div className="flex items-center justify-between mb-2">
                <span className="text-xs font-medium text-gray-700 dark:text-gray-300">Edit Mode</span>
                <div className="flex gap-1 bg-white dark:bg-gray-800 rounded-md p-0.5 border border-gray-300 dark:border-gray-600">
                  <button
                    type="button"
                    onClick={() => setEditMode('visual')}
                    className={`px-3 py-1 text-xs font-medium rounded transition-all ${
                      editMode === 'visual'
                        ? 'bg-blue-600 text-white shadow-sm'
                        : 'text-gray-600 dark:text-gray-400 hover:text-gray-900 dark:hover:text-white'
                    }`}
                  >
                    🎨 Visual
                  </button>
                  <button
                    type="button"
                    onClick={() => setEditMode('json')}
                    className={`px-3 py-1 text-xs font-medium rounded transition-all ${
                      editMode === 'json'
                        ? 'bg-purple-600 text-white shadow-sm'
                        : 'text-gray-600 dark:text-gray-400 hover:text-gray-900 dark:hover:text-white'
                    }`}
                  >
                    📝 JSON
                  </button>
                </div>
              </div>
              <p className="text-xs text-gray-600 dark:text-gray-400">
                {editMode === 'visual' 
                  ? '✨ Use visual controls to edit section properties'
                  : '⚡ Edit raw JSON for advanced customization & copy/paste'}
              </p>
            </div>
          )}

          {/* Content Tab */}
          <div>
            <h3 className="text-sm font-medium text-gray-900 dark:text-white mb-3 flex items-center">
              <span className="mr-2">{editMode === 'json' ? '📝' : '🎨'}</span>
              {editMode === 'json' ? 'JSON Editor' : 'Content'}
            </h3>
            {hasCustomEditor && editMode === 'json' ? (
              <JSONEditor section={section} onUpdate={onUpdate} />
            ) : (
              renderSectionSpecificFields()
            )}
          </div>

          {/* Style Tab */}
          <div>
            <h3 className="text-sm font-medium text-gray-900 dark:text-white mb-3 flex items-center">
              <span className="mr-2">🎨</span>
              Style
            </h3>
            <div className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                  Text Alignment
                </label>
                <select
                  {...register('style.alignment')}
                  className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-700 text-gray-900 dark:text-white"
                >
                  <option value="left">Left</option>
                  <option value="center">Center</option>
                  <option value="right">Right</option>
                </select>
              </div>
              
              <div>
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                  Padding
                </label>
                <select
                  {...register('style.padding')}
                  className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-700 text-gray-900 dark:text-white"
                >
                  <option value="py-8">Small (32px)</option>
                  <option value="py-16">Medium (64px)</option>
                  <option value="py-20">Large (80px)</option>
                  <option value="py-24">Extra Large (96px)</option>
                </select>
              </div>
            </div>
          </div>
        </form>
      </div>

      {/* Footer */}
      <div className="p-4 border-t border-gray-200 dark:border-gray-700">
        <p className="text-xs text-gray-500 dark:text-gray-400 text-center">
          {section.type === 'hero' || section.type === 'features' || section.type === 'cta' 
            ? 'Changes are applied automatically'
            : 'Edit JSON and click Save to apply'}
        </p>
      </div>
    </div>
  );
}
