/**
 * LanguageSwitcher Component - Switch between page translations in editor
 * Author: generated by Amazon Q
 * Created: 2024-01-20
 */

'use client';

import { useState, useEffect } from 'react';
import { Globe, Plus, AlertCircle } from 'lucide-react';
import Link from 'next/link';

interface PageLanguage {
  id: string;
  language: string;
  slug: string;
  isDefaultLang: boolean;
  lastSyncedAt: string | null;
  updatedAt: string;
}

interface LanguageSwitcherProps {
  currentPageId: string;
  currentLanguage: string;
  pageGroupId?: string | null;
  onAddTranslation?: () => void;
}

export function LanguageSwitcher({
  currentPageId,
  currentLanguage,
  pageGroupId,
  onAddTranslation
}: LanguageSwitcherProps) {
  const [languages, setLanguages] = useState<PageLanguage[]>([]);
  const [loading, setLoading] = useState(true);
  const [groupName, setGroupName] = useState('');

  useEffect(() => {
    if (pageGroupId) {
      fetchGroupLanguages();
    } else {
      setLoading(false);
    }
  }, [pageGroupId]);

  const fetchGroupLanguages = async () => {
    try {
      const res = await fetch('/api/admin/pages/grouped');
      const result = await res.json();
      
      if (result.success) {
        const group = result.data.groups.find((g: any) => g.id === pageGroupId);
        if (group) {
          setLanguages(group.pages);
          setGroupName(group.name);
        }
      }
    } catch (error) {
      console.error('Error fetching languages:', error);
    } finally {
      setLoading(false);
    }
  };

  const getLanguageFlag = (lang: string) => {
    const flags: Record<string, string> = {
      en: '🇺🇸',
      ar: '🇸🇦',
      fr: '🇫🇷',
      de: '🇩🇪',
      es: '🇪🇸'
    };
    return flags[lang] || '🌐';
  };

  const isOutdated = (page: PageLanguage) => {
    if (!page.lastSyncedAt || page.isDefaultLang) return false;
    const daysSinceSync = Math.floor(
      (Date.now() - new Date(page.lastSyncedAt).getTime()) / (1000 * 60 * 60 * 24)
    );
    return daysSinceSync > 7;
  };

  if (loading) {
    return (
      <div className="flex items-center gap-2 text-sm text-gray-500">
        <Globe size={16} className="animate-spin" />
        Loading...
      </div>
    );
  }

  if (!pageGroupId) {
    return (
      <div className="flex items-center gap-2 px-3 py-2 bg-yellow-50 dark:bg-yellow-900/20 border border-yellow-200 dark:border-yellow-800 rounded-lg text-sm text-yellow-800 dark:text-yellow-200">
        <AlertCircle size={16} />
        <span>This page is not part of a multilingual group</span>
      </div>
    );
  }

  const currentPage = languages.find(l => l.id === currentPageId);
  const otherLanguages = languages.filter(l => l.id !== currentPageId);

  return (
    <div className="space-y-3">
      {/* Group Info */}
      <div className="flex items-center gap-2 text-sm text-gray-600 dark:text-gray-400">
        <Globe size={16} />
        <span className="font-medium">{groupName}</span>
        <span className="text-gray-400">•</span>
        <span>{languages.length} language{languages.length !== 1 ? 's' : ''}</span>
      </div>

      {/* Current Language */}
      <div className="flex items-center gap-3 p-3 bg-indigo-50 dark:bg-indigo-900/20 border border-indigo-200 dark:border-indigo-800 rounded-lg">
        <span className="text-2xl">{getLanguageFlag(currentLanguage)}</span>
        <div className="flex-1">
          <div className="flex items-center gap-2">
            <span className="font-semibold text-indigo-900 dark:text-indigo-200">
              {currentLanguage.toUpperCase()}
            </span>
            {currentPage?.isDefaultLang && (
              <span className="text-xs bg-indigo-200 dark:bg-indigo-800 text-indigo-800 dark:text-indigo-200 px-2 py-0.5 rounded">
                Default
              </span>
            )}
          </div>
          <div className="text-xs text-indigo-700 dark:text-indigo-300">Currently editing</div>
        </div>
      </div>

      {/* Other Languages */}
      {otherLanguages.length > 0 && (
        <div className="space-y-2">
          <div className="text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">
            Other Languages
          </div>
          {otherLanguages.map(lang => (
            <Link
              key={lang.id}
              href={`/admin/pages/${lang.id}/edit`}
              className="flex items-center gap-3 p-3 bg-white dark:bg-slate-800 border border-gray-200 dark:border-gray-700 rounded-lg hover:border-indigo-300 dark:hover:border-indigo-700 hover:shadow-sm transition-all group"
            >
              <span className="text-2xl">{getLanguageFlag(lang.language)}</span>
              <div className="flex-1">
                <div className="flex items-center gap-2">
                  <span className="font-medium text-gray-900 dark:text-white group-hover:text-indigo-600 dark:group-hover:text-indigo-400 transition-colors">
                    {lang.language.toUpperCase()}
                  </span>
                  {lang.isDefaultLang && (
                    <span className="text-xs bg-blue-100 dark:bg-blue-900 text-blue-800 dark:text-blue-200 px-2 py-0.5 rounded">
                      Default
                    </span>
                  )}
                  {isOutdated(lang) && (
                    <span className="text-xs bg-yellow-100 dark:bg-yellow-900 text-yellow-800 dark:text-yellow-200 px-2 py-0.5 rounded flex items-center gap-1">
                      <AlertCircle size={12} />
                      Outdated
                    </span>
                  )}
                </div>
                <div className="text-xs text-gray-500 dark:text-gray-400">{lang.slug}</div>
              </div>
              <div className="text-xs text-gray-400 group-hover:text-indigo-600 dark:group-hover:text-indigo-400">
                Edit →
              </div>
            </Link>
          ))}
        </div>
      )}

      {/* Add Translation Button */}
      <button
        onClick={onAddTranslation}
        className="w-full flex items-center justify-center gap-2 p-3 border-2 border-dashed border-gray-300 dark:border-gray-600 rounded-lg text-gray-600 dark:text-gray-400 hover:border-indigo-400 dark:hover:border-indigo-600 hover:text-indigo-600 dark:hover:text-indigo-400 transition-colors"
      >
        <Plus size={16} />
        <span className="text-sm font-medium">Add Translation</span>
      </button>

      {/* Outdated Warning */}
      {currentPage && isOutdated(currentPage) && (
        <div className="p-3 bg-yellow-50 dark:bg-yellow-900/20 border border-yellow-200 dark:border-yellow-800 rounded-lg">
          <div className="flex items-start gap-2">
            <AlertCircle size={16} className="text-yellow-600 dark:text-yellow-400 mt-0.5" />
            <div className="flex-1">
              <div className="text-sm font-medium text-yellow-800 dark:text-yellow-200">
                Structure may be outdated
              </div>
              <div className="text-xs text-yellow-700 dark:text-yellow-300 mt-1">
                Last synced {Math.floor((Date.now() - new Date(currentPage.lastSyncedAt!).getTime()) / (1000 * 60 * 60 * 24))} days ago
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
