/**
 * SyncStructureButton Component - Sync structure between pages
 * Author: generated by Amazon Q
 * Created: 2024-01-20
 */

'use client';

import { useState } from 'react';
import { RefreshCw, AlertTriangle, CheckCircle, X } from 'lucide-react';

interface SyncStructureButtonProps {
  sourcePageId: string;
  targetPageId: string;
  targetLanguage: string;
  onSuccess?: () => void;
}

export function SyncStructureButton({
  sourcePageId,
  targetPageId,
  targetLanguage,
  onSuccess
}: SyncStructureButtonProps) {
  const [showModal, setShowModal] = useState(false);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [success, setSuccess] = useState(false);

  const handleSync = async (syncContent: boolean = false) => {
    setError('');
    setLoading(true);

    try {
      const res = await fetch(`/api/admin/pages/${sourcePageId}/sync-structure`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          targetPageId,
          syncContent
        })
      });

      const result = await res.json();

      if (result.success) {
        setSuccess(true);
        setTimeout(() => {
          setShowModal(false);
          setSuccess(false);
          onSuccess?.();
        }, 1500);
      } else {
        setError(result.error || 'Failed to sync structure');
      }
    } catch (err) {
      setError('Network error. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <>
      {/* Trigger Button */}
      <button
        onClick={() => setShowModal(true)}
        className="flex items-center gap-2 px-4 py-2 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700 transition-colors"
      >
        <RefreshCw size={16} />
        Sync Structure
      </button>

      {/* Modal */}
      {showModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm">
          <div className="bg-white dark:bg-slate-800 rounded-lg shadow-xl w-full max-w-md mx-4">
            {/* Header */}
            <div className="flex items-center justify-between p-6 border-b dark:border-slate-700">
              <div className="flex items-center gap-2">
                <RefreshCw className="text-indigo-600 dark:text-indigo-400" size={24} />
                <h2 className="text-xl font-semibold text-gray-900 dark:text-white">
                  Sync Structure
                </h2>
              </div>
              <button
                onClick={() => setShowModal(false)}
                className="text-gray-400 hover:text-gray-600 dark:hover:text-gray-300 transition-colors"
              >
                <X size={24} />
              </button>
            </div>

            {/* Content */}
            <div className="p-6 space-y-4">
              {success ? (
                <div className="flex flex-col items-center justify-center py-8 text-center">
                  <CheckCircle size={48} className="text-green-500 mb-4" />
                  <h3 className="text-lg font-semibold text-gray-900 dark:text-white mb-2">
                    Structure Synced!
                  </h3>
                  <p className="text-sm text-gray-600 dark:text-gray-400">
                    The page structure has been successfully synchronized.
                  </p>
                </div>
              ) : (
                <>
                  {error && (
                    <div className="p-3 bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 rounded text-sm text-red-600 dark:text-red-400">
                      {error}
                    </div>
                  )}

                  {/* Warning */}
                  <div className="flex items-start gap-3 p-4 bg-yellow-50 dark:bg-yellow-900/20 border border-yellow-200 dark:border-yellow-800 rounded-lg">
                    <AlertTriangle size={20} className="text-yellow-600 dark:text-yellow-400 flex-shrink-0 mt-0.5" />
                    <div className="text-sm text-yellow-800 dark:text-yellow-200">
                      <div className="font-medium mb-1">Important</div>
                      <p>
                        This will update the <strong>{targetLanguage.toUpperCase()}</strong> page structure 
                        to match the current page. Existing content will be preserved.
                      </p>
                    </div>
                  </div>

                  {/* Info */}
                  <div className="space-y-3">
                    <div className="text-sm text-gray-700 dark:text-gray-300">
                      <strong>What will be synced:</strong>
                    </div>
                    <ul className="space-y-2 text-sm text-gray-600 dark:text-gray-400">
                      <li className="flex items-start gap-2">
                        <span className="text-green-500 mt-0.5">✓</span>
                        <span>Section types and order</span>
                      </li>
                      <li className="flex items-start gap-2">
                        <span className="text-green-500 mt-0.5">✓</span>
                        <span>Style settings (colors, spacing, layout)</span>
                      </li>
                      <li className="flex items-start gap-2">
                        <span className="text-red-500 mt-0.5">✗</span>
                        <span>Content (text, images) - will be preserved</span>
                      </li>
                    </ul>
                  </div>

                  {/* Actions */}
                  <div className="flex flex-col gap-2 pt-4">
                    <button
                      onClick={() => handleSync(false)}
                      disabled={loading}
                      className="w-full px-4 py-2.5 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700 disabled:opacity-50 disabled:cursor-not-allowed transition-colors font-medium"
                    >
                      {loading ? (
                        <span className="flex items-center justify-center gap-2">
                          <RefreshCw size={16} className="animate-spin" />
                          Syncing...
                        </span>
                      ) : (
                        'Sync Structure Only'
                      )}
                    </button>

                    <button
                      onClick={() => handleSync(true)}
                      disabled={loading}
                      className="w-full px-4 py-2.5 border-2 border-indigo-600 text-indigo-600 dark:text-indigo-400 rounded-lg hover:bg-indigo-50 dark:hover:bg-indigo-900/20 disabled:opacity-50 disabled:cursor-not-allowed transition-colors font-medium"
                    >
                      Sync Structure + Content
                    </button>

                    <button
                      onClick={() => setShowModal(false)}
                      disabled={loading}
                      className="w-full px-4 py-2 text-gray-600 dark:text-gray-400 hover:text-gray-900 dark:hover:text-gray-200 transition-colors"
                    >
                      Cancel
                    </button>
                  </div>

                  {/* Additional Info */}
                  <div className="pt-2 border-t dark:border-slate-700">
                    <details className="text-xs text-gray-500 dark:text-gray-400">
                      <summary className="cursor-pointer hover:text-gray-700 dark:hover:text-gray-300">
                        Advanced: Sync with content
                      </summary>
                      <p className="mt-2 pl-4 border-l-2 border-gray-300 dark:border-gray-600">
                        This option will also copy all content (text, images, etc.) from the source page. 
                        Use this only if you want to completely replace the target page content.
                      </p>
                    </details>
                  </div>
                </>
              )}
            </div>
          </div>
        </div>
      )}
    </>
  );
}
