/**
 * useSectionTranslation Hook - Translate section fields
 * Author: generated by Amazon Q
 * Created: 2024-01-20
 */

'use client';

import { useLanguage } from '@/lib/i18n/context';
import { resolveFieldValue, resolveObjectFields } from '@/lib/i18n/dictionary-resolver';
import { SupportedLanguage } from '@/lib/i18n/config';
import { useEffect, useState } from 'react';

/**
 * Hook برای ترجمه فیلدهای سکشن
 */
export function useSectionTranslation() {
  const { language } = useLanguage();

  /**
   * Resolve کردن یک فیلد (string یا dictionary key)
   */
  const resolveField = async (value: any): Promise<string> => {
    return await resolveFieldValue(value, language as SupportedLanguage);
  };

  /**
   * Resolve کردن تمام فیلدهای یک object
   */
  const resolveObject = async (data: Record<string, any>): Promise<Record<string, any>> => {
    return await resolveObjectFields(data, language as SupportedLanguage);
  };

  return {
    language,
    resolveField,
    resolveObject
  };
}

/**
 * Hook برای resolve کردن یک فیلد خاص
 * @param value - مقدار فیلد (string یا dictionary key)
 * @returns مقدار resolve شده
 */
export function useResolvedField(value: any): string {
  const { language } = useLanguage();
  const [resolved, setResolved] = useState<string>(
    typeof value === 'string' && !value.startsWith('@') ? value : ''
  );

  useEffect(() => {
    let mounted = true;

    const resolve = async () => {
      const result = await resolveFieldValue(value, language as SupportedLanguage);
      if (mounted) {
        setResolved(result);
      }
    };

    resolve();

    return () => {
      mounted = false;
    };
  }, [value, language]);

  return resolved;
}

/**
 * Hook برای resolve کردن یک object کامل
 * @param data - object داده
 * @returns object با مقادیر resolve شده
 */
export function useResolvedObject<T extends Record<string, any>>(data: T): T {
  const { language } = useLanguage();
  const [resolved, setResolved] = useState<T>(data);

  useEffect(() => {
    let mounted = true;

    const resolve = async () => {
      const result = await resolveObjectFields(data, language as SupportedLanguage);
      if (mounted) {
        setResolved(result as T);
      }
    };

    resolve();

    return () => {
      mounted = false;
    };
  }, [data, language]);

  return resolved;
}
