/**
 * Translation Hook
 * Author: generated by Amazon Q
 * Created: 2024-01-15
 */

'use client';

import { useState, useEffect } from 'react';
import { useLanguage } from '@/lib/i18n/context';
import { loadTranslations, getNestedValue } from '@/lib/i18n/translations';

interface TranslationObject {
  [key: string]: string | TranslationObject;
}

export function useTranslation() {
  const { language } = useLanguage();
  const [translations, setTranslations] = useState<TranslationObject>({});
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    const loadNamespaceTranslations = async () => {
      setIsLoading(true);
      try {
        const data = await loadTranslations(language, 'common');
        setTranslations(data);
      } catch (error) {
        // Failed to load translations
        setTranslations({});
      } finally {
        setIsLoading(false);
      }
    };

    loadNamespaceTranslations();
  }, [language]);

  const t = (key: string, fallback?: string): string => {
    if (isLoading) return fallback || key;
    return getNestedValue(translations, key) || fallback || key;
  };

  return { t, isLoading, language };
}