/**
 * API Route: Find Equivalent Page in Different Language
 * Author: generated by Amazon Q
 * Created: 2025-01-20
 */

import { NextRequest, NextResponse } from 'next/server';
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const currentSlug = searchParams.get('slug');
    const targetLang = searchParams.get('lang');

    if (!currentSlug || !targetLang) {
      return NextResponse.json(
        { found: false, error: 'slug and lang parameters are required' },
        { status: 400 }
      );
    }

    // مرحله 1: پیدا کردن صفحه فعلی
    const currentPage = await prisma.page.findUnique({
      where: { slug: currentSlug, status: 'published' },
      select: {
        id: true,
        slug: true,
        language: true,
        pageGroupId: true,
      },
    });

    if (!currentPage) {
      return NextResponse.json({ found: false, reason: 'current_page_not_found' });
    }

    // مرحله 2: اگر pageGroupId داره، صفحه معادل رو پیدا کن
    if (currentPage.pageGroupId) {
      const equivalentPage = await prisma.page.findFirst({
        where: {
          pageGroupId: currentPage.pageGroupId,
          language: targetLang,
          status: 'published',
        },
        select: {
          slug: true,
          language: true,
        },
      });

      if (equivalentPage) {
        return NextResponse.json({
          found: true,
          slug: equivalentPage.slug,
          method: 'pageGroup',
        });
      }
    }

    return NextResponse.json({ found: false, reason: 'no_equivalent_in_group' });
  } catch (error) {
    console.error('Error finding equivalent page:', error);
    return NextResponse.json(
      { found: false, error: 'Failed to find equivalent page' },
      { status: 500 }
    );
  }
}
