/**
 * Root page redirect
 * Author: generated by Amazon Q
 * Created: 2024-01-15
 */

import { redirect } from 'next/navigation';
import { prisma } from '@/lib/prisma';

export default async function RootPage() {
  // Try to get default language from database
  let defaultLanguage = 'fa';
  
  try {
    const settings = await prisma.siteSettings.findFirst();
    if (settings) {
      const saved = JSON.parse(settings.data);
      defaultLanguage = saved?.languages?.defaultLanguage || 'fa';
    }
  } catch (error) {
    console.error('Failed to fetch default language:', error);
  }

  redirect(`/${defaultLanguage}`);
}
