/**
 * Admin Dashboard
 * Author: generated by Amazon Q
 * Created: 2024-01-15
 */

'use client';

import { useState, useEffect } from 'react';

interface DashboardStats {
  totalPages: number;
  publishedPages: number;
  draftPages: number;
  totalSections: number;
}

export default function AdminDashboard() {
  const [stats, setStats] = useState<DashboardStats>({
    totalPages: 0,
    publishedPages: 0,
    draftPages: 0,
    totalSections: 0,
  });

  useEffect(() => {
    // Mock data - replace with actual API call
    setStats({
      totalPages: 8,
      publishedPages: 6,
      draftPages: 2,
      totalSections: 12,
    });
  }, []);

  const statCards = [
    {
      title: 'Total Pages',
      value: stats.totalPages,
      icon: '📄',
      color: 'bg-blue-500',
    },
    {
      title: 'Published',
      value: stats.publishedPages,
      icon: '✅',
      color: 'bg-green-500',
    },
    {
      title: 'Drafts',
      value: stats.draftPages,
      icon: '📝',
      color: 'bg-yellow-500',
    },
    {
      title: 'Sections',
      value: stats.totalSections,
      icon: '🧩',
      color: 'bg-purple-500',
    },
  ];

  return (
    <div>
      <div className="mb-8">
        <h1 className="text-3xl font-bold text-gray-900 dark:text-white">
          Dashboard
        </h1>
        <p className="mt-2 text-gray-600 dark:text-gray-400">
          Welcome to your website admin panel
        </p>
      </div>

      {/* Stats Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-8">
        {statCards.map((card) => (
          <div
            key={card.title}
            className="bg-white dark:bg-gray-800 rounded-lg shadow p-6"
          >
            <div className="flex items-center">
              <div className={`p-3 rounded-lg ${card.color} text-white mr-4`}>
                <span className="text-2xl">{card.icon}</span>
              </div>
              <div>
                <p className="text-sm font-medium text-gray-600 dark:text-gray-400">
                  {card.title}
                </p>
                <p className="text-2xl font-bold text-gray-900 dark:text-white">
                  {card.value}
                </p>
              </div>
            </div>
          </div>
        ))}
      </div>

      {/* Quick Actions */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <div className="bg-white dark:bg-gray-800 rounded-lg shadow p-6">
          <h2 className="text-xl font-bold text-gray-900 dark:text-white mb-4">
            Quick Actions
          </h2>
          <div className="space-y-3">
            <button className="w-full text-left p-3 rounded-lg bg-blue-50 dark:bg-blue-900/20 hover:bg-blue-100 dark:hover:bg-blue-900/30 transition-colors">
              <div className="flex items-center">
                <span className="text-2xl mr-3">➕</span>
                <div>
                  <p className="font-medium text-gray-900 dark:text-white">
                    Create New Page
                  </p>
                  <p className="text-sm text-gray-600 dark:text-gray-400">
                    Add a new page to your website
                  </p>
                </div>
              </div>
            </button>
            
            <button className="w-full text-left p-3 rounded-lg bg-green-50 dark:bg-green-900/20 hover:bg-green-100 dark:hover:bg-green-900/30 transition-colors">
              <div className="flex items-center">
                <span className="text-2xl mr-3">🖼️</span>
                <div>
                  <p className="font-medium text-gray-900 dark:text-white">
                    Upload Media
                  </p>
                  <p className="text-sm text-gray-600 dark:text-gray-400">
                    Add images and files
                  </p>
                </div>
              </div>
            </button>
            
            <button className="w-full text-left p-3 rounded-lg bg-purple-50 dark:bg-purple-900/20 hover:bg-purple-100 dark:hover:bg-purple-900/30 transition-colors">
              <div className="flex items-center">
                <span className="text-2xl mr-3">🌐</span>
                <div>
                  <p className="font-medium text-gray-900 dark:text-white">
                    Manage Translations
                  </p>
                  <p className="text-sm text-gray-600 dark:text-gray-400">
                    Update multilingual content
                  </p>
                </div>
              </div>
            </button>
          </div>
        </div>

        <div className="bg-white dark:bg-gray-800 rounded-lg shadow p-6">
          <h2 className="text-xl font-bold text-gray-900 dark:text-white mb-4">
            Recent Activity
          </h2>
          <div className="space-y-3">
            <div className="flex items-center p-3 rounded-lg bg-gray-50 dark:bg-gray-700">
              <span className="text-xl mr-3">📝</span>
              <div>
                <p className="font-medium text-gray-900 dark:text-white">
                  App Builder page updated
                </p>
                <p className="text-sm text-gray-600 dark:text-gray-400">
                  2 hours ago
                </p>
              </div>
            </div>
            
            <div className="flex items-center p-3 rounded-lg bg-gray-50 dark:bg-gray-700">
              <span className="text-xl mr-3">🖼️</span>
              <div>
                <p className="font-medium text-gray-900 dark:text-white">
                  New image uploaded
                </p>
                <p className="text-sm text-gray-600 dark:text-gray-400">
                  5 hours ago
                </p>
              </div>
            </div>
            
            <div className="flex items-center p-3 rounded-lg bg-gray-50 dark:bg-gray-700">
              <span className="text-xl mr-3">🌐</span>
              <div>
                <p className="font-medium text-gray-900 dark:text-white">
                  Arabic translations updated
                </p>
                <p className="text-sm text-gray-600 dark:text-gray-400">
                  1 day ago
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}