/**
 * Admin Footers Management Page
 * Author: generated by Amazon Q
 * Created: 2024-01-20
 */

'use client';

import { useState, useEffect } from 'react';
import Link from 'next/link';
import { Globe, Copy, Plus, Edit, Trash2, Eye, EyeOff } from 'lucide-react';

interface Footer {
  id: string;
  language: string;
  companyName: string;
  tagline?: string;
  description?: string;
  isActive: boolean;
  columns: any[];
  createdAt: string;
  updatedAt: string;
}

const languageFlags: Record<string, string> = {
  en: '🇺🇸',
  ar: '🇸🇦',
  tr: '🇹🇷',
  fr: '🇫🇷',
  de: '🇩🇪',
  es: '🇪🇸'
};

const languageNames: Record<string, string> = {
  en: 'English',
  ar: 'العربية',
  tr: 'Türkçe',
  fr: 'Français',
  de: 'Deutsch',
  es: 'Español'
};

export default function FootersPage() {
  const [footers, setFooters] = useState<Footer[]>([]);
  const [loading, setLoading] = useState(true);
  const [selectedLanguage, setSelectedLanguage] = useState<string>('all');
  const [showCopyModal, setShowCopyModal] = useState(false);
  const [copySourceId, setCopySourceId] = useState<string>('');
  const [copyTargetLanguage, setCopyTargetLanguage] = useState('ar');

  useEffect(() => {
    fetchFooters();
  }, []);

  const fetchFooters = async () => {
    try {
      const token = localStorage.getItem('adminToken');
      const response = await fetch('/api/admin/footers', {
        headers: { 'Authorization': `Bearer ${token}` },
      });
      if (response.ok) {
        const data = await response.json();
        setFooters(data.footers || []);
      }
    } catch (error) {
      console.error('Failed to fetch footers:', error);
    } finally {
      setLoading(false);
    }
  };

  const toggleActive = async (id: string, currentStatus: boolean) => {
    try {
      const token = localStorage.getItem('adminToken');
      const footer = footers.find(f => f.id === id);
      if (!footer) return;

      const response = await fetch(`/api/admin/footers/${id}`, {
        method: 'PUT',
        headers: {
          'Authorization': `Bearer ${token}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          ...footer,
          isActive: !currentStatus
        }),
      });

      if (response.ok) {
        fetchFooters();
      }
    } catch (error) {
      console.error('Failed to toggle footer status:', error);
    }
  };

  const deleteFooter = async (id: string) => {
    if (!confirm('Are you sure you want to delete this footer?')) return;

    try {
      const token = localStorage.getItem('adminToken');
      const response = await fetch(`/api/admin/footers/${id}`, {
        method: 'DELETE',
        headers: { 'Authorization': `Bearer ${token}` },
      });

      if (response.ok) {
        alert('✅ Footer deleted successfully!');
        fetchFooters();
      }
    } catch (error) {
      console.error('Failed to delete footer:', error);
      alert('❌ Failed to delete footer');
    }
  };

  const openCopyModal = (footerId: string) => {
    setCopySourceId(footerId);
    setShowCopyModal(true);
  };

  const copyFooterForTranslation = async () => {
    if (!copyTargetLanguage || !copySourceId) return;

    try {
      const token = localStorage.getItem('adminToken');
      const sourceFooter = footers.find(f => f.id === copySourceId);
      if (!sourceFooter) return;

      const response = await fetch('/api/admin/footers', {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${token}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          language: copyTargetLanguage,
          companyName: sourceFooter.companyName,
          tagline: sourceFooter.tagline,
          description: sourceFooter.description,
          contactInfo: (sourceFooter as any).contactInfo,
          columns: sourceFooter.columns,
          bottomBar: (sourceFooter as any).bottomBar,
          style: (sourceFooter as any).style,
          isActive: false
        }),
      });

      if (response.ok) {
        alert(`✅ Footer copied successfully for ${languageNames[copyTargetLanguage]}!`);
        setShowCopyModal(false);
        fetchFooters();
      } else {
        const data = await response.json();
        alert(`❌ ${data.error || 'Failed to copy footer'}`);
      }
    } catch (error) {
      console.error('Failed to copy footer:', error);
      alert('❌ Failed to copy footer');
    }
  };

  const filteredFooters = selectedLanguage === 'all' 
    ? footers 
    : footers.filter(f => f.language === selectedLanguage);

  const usedLanguages = footers.map(f => f.language);
  const availableLanguages = Object.keys(languageNames).filter(
    lang => !usedLanguages.includes(lang)
  );

  return (
    <div>
      <div className="flex justify-between items-center mb-8">
        <div>
          <h1 className="text-3xl font-bold text-gray-900 dark:text-white">
            Footers
          </h1>
          <p className="mt-2 text-gray-600 dark:text-gray-400">
            Manage footer content for different languages
          </p>
        </div>
        {availableLanguages.length > 0 && (
          <Link
            href="/admin/footers/new"
            className="bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded-lg font-medium transition-colors flex items-center gap-2"
          >
            <Plus className="w-4 h-4" />
            Create Footer
          </Link>
        )}
      </div>

      {/* فیلتر زبان */}
      <div className="bg-white dark:bg-gray-800 rounded-lg shadow p-4 mb-6">
        <div className="flex items-center gap-4">
          <Globe className="w-5 h-5 text-gray-600 dark:text-gray-400" />
          <select
            value={selectedLanguage}
            onChange={(e) => setSelectedLanguage(e.target.value)}
            className="flex-1 px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-white"
          >
            <option value="all">All Languages ({footers.length})</option>
            {Object.entries(languageNames).map(([code, name]) => {
              const count = footers.filter(f => f.language === code).length;
              if (count === 0) return null;
              return (
                <option key={code} value={code}>
                  {languageFlags[code]} {name} ({count})
                </option>
              );
            })}
          </select>
        </div>
      </div>

      {loading ? (
        <div className="text-center py-12">
          <div className="inline-block animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600"></div>
        </div>
      ) : filteredFooters.length === 0 ? (
        <div className="text-center py-12 bg-white dark:bg-gray-800 rounded-lg shadow">
          <div className="text-6xl mb-4">🦶</div>
          <h3 className="text-xl font-semibold text-gray-900 dark:text-white mb-2">
            No footers found
          </h3>
          <p className="text-gray-600 dark:text-gray-400 mb-4">
            {selectedLanguage === 'all' 
              ? 'Create your first footer to get started'
              : `No footer found for ${languageNames[selectedLanguage]}`
            }
          </p>
          {availableLanguages.length > 0 && (
            <Link
              href="/admin/footers/new"
              className="inline-flex items-center gap-2 bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded-lg font-medium transition-colors"
            >
              <Plus className="w-4 h-4" />
              Create Footer
            </Link>
          )}
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {filteredFooters.map((footer) => (
            <div
              key={footer.id}
              className="bg-white dark:bg-gray-800 rounded-lg shadow p-6 hover:shadow-lg transition-shadow"
            >
              <div className="flex items-start justify-between mb-4">
                <div className="flex-1">
                  <div className="flex items-center gap-2 mb-2">
                    <span className="text-2xl">{languageFlags[footer.language] || '🌐'}</span>
                    <h3 className="text-lg font-semibold text-gray-900 dark:text-white">
                      {languageNames[footer.language] || footer.language.toUpperCase()}
                    </h3>
                  </div>
                  <p className="text-sm text-gray-600 dark:text-gray-400">
                    {footer.companyName}
                  </p>
                  {footer.tagline && (
                    <p className="text-xs text-gray-500 dark:text-gray-500 mt-1">
                      {footer.tagline}
                    </p>
                  )}
                </div>
                <button
                  onClick={() => toggleActive(footer.id, footer.isActive)}
                  className={`p-2 rounded-lg transition-colors ${
                    footer.isActive
                      ? 'bg-green-100 text-green-600 dark:bg-green-900/20 dark:text-green-400'
                      : 'bg-gray-100 text-gray-400 dark:bg-gray-700 dark:text-gray-500'
                  }`}
                  title={footer.isActive ? 'Active' : 'Inactive'}
                >
                  {footer.isActive ? <Eye className="w-4 h-4" /> : <EyeOff className="w-4 h-4" />}
                </button>
              </div>

              <div className="text-sm text-gray-600 dark:text-gray-400 mb-4">
                {footer.columns.length} columns
              </div>

              <div className="flex gap-2">
                <Link
                  href={`/admin/footers/edit/${footer.id}`}
                  className="flex-1 text-center px-4 py-2 bg-blue-50 dark:bg-blue-900/20 text-blue-600 dark:text-blue-400 rounded-md hover:bg-blue-100 dark:hover:bg-blue-900/30 transition-colors flex items-center justify-center gap-2"
                >
                  <Edit className="w-4 h-4" />
                  Edit
                </Link>
                <button
                  onClick={() => openCopyModal(footer.id)}
                  className="px-4 py-2 bg-purple-50 dark:bg-purple-900/20 text-purple-600 dark:text-purple-400 rounded-md hover:bg-purple-100 dark:hover:bg-purple-900/30 transition-colors"
                  title="Copy for Translation"
                >
                  <Copy className="w-4 h-4" />
                </button>
                <button
                  onClick={() => deleteFooter(footer.id)}
                  className="px-4 py-2 bg-red-50 dark:bg-red-900/20 text-red-600 dark:text-red-400 rounded-md hover:bg-red-100 dark:hover:bg-red-900/30 transition-colors"
                  title="Delete"
                >
                  <Trash2 className="w-4 h-4" />
                </button>
              </div>
            </div>
          ))}
        </div>
      )}

      {/* Copy Modal */}
      {showCopyModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm">
          <div className="bg-white dark:bg-gray-800 rounded-lg shadow-xl w-full max-w-md mx-4 p-6">
            <h3 className="text-xl font-bold text-gray-900 dark:text-white mb-4">
              📋 Copy Footer for Translation
            </h3>
            <p className="text-sm text-gray-600 dark:text-gray-400 mb-4">
              This will create a copy of this footer for translation to another language.
            </p>
            <div className="mb-6">
              <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                Target Language
              </label>
              <select
                value={copyTargetLanguage}
                onChange={(e) => setCopyTargetLanguage(e.target.value)}
                className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-white"
              >
                {availableLanguages.map(code => (
                  <option key={code} value={code}>
                    {languageFlags[code]} {languageNames[code]}
                  </option>
                ))}
              </select>
            </div>
            <div className="flex gap-3">
              <button
                onClick={() => setShowCopyModal(false)}
                className="flex-1 px-4 py-2 border border-gray-300 dark:border-gray-600 text-gray-700 dark:text-gray-300 rounded-lg hover:bg-gray-50 dark:hover:bg-gray-700"
              >
                Cancel
              </button>
              <button
                onClick={copyFooterForTranslation}
                className="flex-1 px-4 py-2 bg-purple-600 text-white rounded-lg hover:bg-purple-700"
              >
                Copy Footer
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
