/**
 * Features section component
 * Author: generated by Amazon Q
 * Created: 2024-01-15
 */

import { FeatureCard } from './FeatureCard';

const features = [
  {
    title: 'Interactive Lessons',
    description: 'Engage with dynamic content that adapts to your learning pace and style.',
    icon: '🎯',
  },
  {
    title: 'Real-time Feedback',
    description: 'Get instant corrections and suggestions to improve your pronunciation and grammar.',
    icon: '💬',
  },
  {
    title: 'Progress Tracking',
    description: 'Monitor your improvement with detailed analytics and personalized insights.',
    icon: '📊',
  },
];

export function Features() {
  return (
    <section className="py-20 bg-neutral-50 dark:bg-neutral-900">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center mb-16">
          <h2 className="text-3xl sm:text-4xl font-bold text-neutral-900 dark:text-white mb-4">
            Why Choose Our Platform?
          </h2>
          <p className="text-lg text-neutral-600 dark:text-neutral-300 max-w-2xl mx-auto">
            Discover the features that make learning English effective and enjoyable.
          </p>
        </div>
        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
          {features.map((feature, index) => (
            <FeatureCard
              key={index}
              title={feature.title}
              description={feature.description}
              icon={feature.icon}
            />
          ))}
        </div>
      </div>
    </section>
  );
}