/**
 * Footer component - Dynamic footer from database
 * Author: generated by Amazon Q
 * Created: 2024-01-15
 * Updated: 2024-01-20 - Using Footer table instead of Menu
 */

'use client';

import Link from 'next/link';
import { useParams } from 'next/navigation';
import { useState, useEffect } from 'react';
import { Twitter, Linkedin, Facebook, Instagram, Youtube, Github, Mail, Phone, MapPin } from 'lucide-react';

const SOCIAL_ICONS = {
  twitter: Twitter,
  linkedin: Linkedin,
  facebook: Facebook,
  instagram: Instagram,
  youtube: Youtube,
  github: Github,
};

interface FooterColumn {
  title: string;
  links: {
    label: string;
    url: string;
  }[];
}

interface FooterData {
  companyName?: string;
  tagline?: string;
  description?: string;
  columns?: FooterColumn[];
  contactInfo?: {
    show?: boolean;
    phone?: string;
    email?: string;
    address?: string;
  };
  bottomBar?: {
    show?: boolean;
    copyrightText?: string;
    showSocialLinks?: boolean;
    socialLinks?: {
      platform: string;
      url: string;
    }[];
  };
}

export function Footer() {
  const params = useParams();
  const lang = (params?.lang as string) || 'en';
  const [footerData, setFooterData] = useState<FooterData | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetch(`/api/footer?language=${lang}`)
      .then(res => res.json())
      .then(data => {
        if (data.success && data.footer) {
          console.log('Footer loaded from database:', data.footer.language);
          setFooterData(data.footer);
        } else {
          console.log('Footer not found, using default');
          setFooterData(getDefaultFooter(lang));
        }
      })
      .catch((error) => {
        console.error('Footer fetch error:', error);
        setFooterData(getDefaultFooter(lang));
      })
      .finally(() => {
        setLoading(false);
      });
  }, [lang]);

  const getDefaultFooter = (language: string): FooterData => {
    if (language === 'ar') {
      return {
        companyName: 'موقع الإنجليزية',
        description: 'تمكين المتعلمين في جميع أنحاء العالم من إتقان اللغة الإنجليزية بثقة وطلاقة.',
        columns: [
          {
            title: 'المنتج',
            links: [
              { label: 'الميزات', url: `/${language}/features` },
              { label: 'الأسعار', url: `/${language}/pricing` }
            ]
          },
          {
            title: 'الشركة',
            links: [
              { label: 'من نحن', url: `/${language}/about` },
              { label: 'اتصل بنا', url: `/${language}/contact` }
            ]
          }
        ],
        bottomBar: {
          show: true,
          copyrightText: `© ${new Date().getFullYear()} جميع الحقوق محفوظة.`,
          showSocialLinks: false,
          socialLinks: []
        }
      };
    }

    return {
      companyName: 'English Website',
      description: 'Empowering learners worldwide to master English with confidence and fluency.',
      columns: [
        {
          title: 'Product',
          links: [
            { label: 'Features', url: `/${language}/features` },
            { label: 'Pricing', url: `/${language}/pricing` }
          ]
        },
        {
          title: 'Company',
          links: [
            { label: 'About', url: `/${language}/about` },
            { label: 'Contact', url: `/${language}/contact` }
          ]
        }
      ],
      bottomBar: {
        show: true,
        copyrightText: `© ${new Date().getFullYear()} English Website. All rights reserved.`,
        showSocialLinks: false,
        socialLinks: []
      }
    };
  };

  if (loading) {
    return (
      <footer className="bg-slate-100 dark:bg-neutral-900 text-slate-600 dark:text-neutral-300 border-t border-slate-200 dark:border-neutral-800">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
          <div className="text-center text-sm">Loading...</div>
        </div>
      </footer>
    );
  }

  if (!footerData) return null;

  const copyrightText = (footerData.bottomBar?.copyrightText || `© ${new Date().getFullYear()} All rights reserved.`)
    .replace('{year}', new Date().getFullYear().toString());

  return (
    <footer
      className="bg-slate-100 dark:bg-neutral-900 text-slate-600 dark:text-neutral-300 border-t border-slate-200 dark:border-neutral-800"
      role="contentinfo"
    >
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        <div className={`grid gap-8 ${footerData.columns?.length ? `md:grid-cols-${Math.min(footerData.columns.length + 1, 4)}` : 'md:grid-cols-3'}`}>
          {/* Brand Column */}
          <div>
            <h3 className="font-semibold mb-3 text-slate-900 dark:text-white">
              {footerData.companyName || 'English Website'}
            </h3>
            {footerData.tagline && (
              <p className="text-sm font-medium mb-2 opacity-80">{footerData.tagline}</p>
            )}
            {footerData.description && (
              <p className="text-sm leading-relaxed">{footerData.description}</p>
            )}
            {/* Contact Info */}
            {footerData.contactInfo?.show && (
              <div className="mt-4 space-y-2">
                {footerData.contactInfo.phone && (
                  <a
                    href={`tel:${footerData.contactInfo.phone}`}
                    className="flex items-center gap-2 text-sm hover:text-slate-900 dark:hover:text-white transition-colors"
                  >
                    <Phone className="h-3.5 w-3.5 shrink-0" />
                    {footerData.contactInfo.phone}
                  </a>
                )}
                {footerData.contactInfo.email && (
                  <a
                    href={`mailto:${footerData.contactInfo.email}`}
                    className="flex items-center gap-2 text-sm hover:text-slate-900 dark:hover:text-white transition-colors"
                  >
                    <Mail className="h-3.5 w-3.5 shrink-0" />
                    {footerData.contactInfo.email}
                  </a>
                )}
                {footerData.contactInfo.address && (
                  <p className="flex items-start gap-2 text-sm">
                    <MapPin className="h-3.5 w-3.5 shrink-0 mt-0.5" />
                    {footerData.contactInfo.address}
                  </p>
                )}
              </div>
            )}
          </div>

          {/* Dynamic Link Columns */}
          {(footerData.columns || []).map((col, index) => (
            <div key={index}>
              <h4 className="font-medium mb-4 text-slate-900 dark:text-white">
                {col.title}
              </h4>
              <nav className="space-y-2">
                {col.links.map((link, idx) => {
                  const href = link.url.startsWith('http') ? link.url : link.url;
                  return (
                    <Link
                      key={idx}
                      href={href}
                      className="block text-sm hover:text-slate-900 dark:hover:text-white transition-colors"
                    >
                      {link.label}
                    </Link>
                  );
                })}
              </nav>
            </div>
          ))}
        </div>

        {/* Bottom Bar */}
        {footerData.bottomBar?.show && (
          <div className="border-t border-slate-200 dark:border-neutral-800 mt-8 pt-8 flex flex-col sm:flex-row items-center justify-between gap-4 text-sm">
            <p className="text-slate-500 dark:text-neutral-400">{copyrightText}</p>

            {footerData.bottomBar.showSocialLinks && footerData.bottomBar.socialLinks && footerData.bottomBar.socialLinks.length > 0 && (
              <div className="flex items-center gap-3">
                {footerData.bottomBar.socialLinks.map((social, idx) => {
                  const Icon = SOCIAL_ICONS[social.platform as keyof typeof SOCIAL_ICONS];
                  return Icon ? (
                    <a
                      key={idx}
                      href={social.url}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="text-slate-400 hover:text-slate-700 dark:hover:text-white transition-colors"
                      aria-label={social.platform}
                    >
                      <Icon className="h-4 w-4" />
                    </a>
                  ) : null;
                })}
              </div>
            )}
          </div>
        )}
      </div>
    </footer>
  );
}
