/**
 * Translation Management System
 * Author: generated by Amazon Q
 * Created: 2024-01-15
 */

import { SupportedLanguage, defaultLanguage } from './config';

interface TranslationObject {
  [key: string]: string | TranslationObject;
}
type Translations = Record<SupportedLanguage, TranslationObject>;

const translations: Translations = {
  en: {},
  ar: {}
};

export async function loadTranslations(language: SupportedLanguage, namespace: string): Promise<TranslationObject> {
  if (translations[language][namespace]) {
    return translations[language][namespace] as TranslationObject;
  }

  try {
    const translation = await import(`../../locales/${language}/${namespace}.json`);
    translations[language][namespace] = translation.default;
    return translation.default;
  } catch {
    if (language !== defaultLanguage) {
      return loadTranslations(defaultLanguage, namespace);
    }
    return {};
  }
}

export function getNestedValue(obj: TranslationObject, path: string): string {
  let current: string | TranslationObject = obj;
  
  for (const key of path.split('.')) {
    if (typeof current === 'object' && current && key in current) {
      current = current[key];
    } else {
      return path;
    }
  }
  
  return typeof current === 'string' ? current : path;
}

export function createTranslator(language: SupportedLanguage, namespace: string) {
  return async (key: string, fallback?: string): Promise<string> => {
    const translations = await loadTranslations(language, namespace);
    return getNestedValue(translations, key) || fallback || key;
  };
}