/**
 * Import/Export API Route
 * Author: generated by Amazon Q
 * Created: 2024-01-15
 */

import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';
import { ImportExportManager } from '@/lib/import-export/utils';
import { ExportData, PageExportData, SectionExportData, ImportResult } from '@/lib/import-export/types';

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { action, data, options } = body;

    if (action === 'import') {
      return handleImport(data, options);
    }

    return NextResponse.json({ error: 'Invalid action' }, { status: 400 });
  } catch (error) {
    console.error('Import/Export API error:', error);
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    );
  }
}

async function handleImport(
  importData: ExportData,
  options: { autoImportSections: boolean; validateData: boolean }
): Promise<NextResponse> {
  const result: ImportResult = {
    success: false,
    message: '',
    imported: { pages: 0, sections: 0 },
    errors: []
  };

  try {
    // Validate data
    if (options.validateData) {
      const validation = ImportExportManager.validateImportData(importData);
      if (!validation.valid) {
        result.errors = validation.errors;
        result.message = 'Validation failed';
        return NextResponse.json(result);
      }
    }

    if (importData.type === 'page') {
      const pageData = importData.data as PageExportData;
      
      // Check if page exists
      const existingPage = await prisma.page.findUnique({
        where: { slug: pageData.page.slug }
      });

      let finalTitle = pageData.page.title;
      let finalSlug = pageData.page.slug;

      // If page exists, create a copy with modified title and slug
      if (existingPage) {
        const timestamp = Date.now();
        finalTitle = `${pageData.page.title} (Copy ${timestamp})`;
        finalSlug = `${pageData.page.slug}-copy-${timestamp}`;
        
        // Ensure the new slug is unique
        let counter = 1;
        while (await prisma.page.findUnique({ where: { slug: finalSlug } })) {
          finalSlug = `${pageData.page.slug}-copy-${timestamp}-${counter}`;
          counter++;
        }
      }

      // Import new sections if needed
      if (options.autoImportSections) {
        const newSections = ImportExportManager.detectNewSections(pageData);
        if (newSections.length > 0) {
          console.log('New sections detected:', newSections);
        }
      }

      // Create page (always create, never update)
      const pageCreateData = {
        title: finalTitle,
        slug: finalSlug,
        metaTitle: pageData.page.metaTitle,
        metaDescription: pageData.page.metaDescription,
        language: pageData.page.language,
        builderData: JSON.stringify(pageData.page.builderData),
        isBuilderPage: true,
        status: 'draft'
      };

      await prisma.page.create({
        data: pageCreateData
      });

      result.imported.pages = 1;
      result.success = true;
      result.message = existingPage 
        ? `Page copied as "${finalTitle}" with slug "${finalSlug}"`
        : `Page "${finalTitle}" imported successfully`;
    }

    if (importData.type === 'section') {
      const sectionData = importData.data as SectionExportData;
      
      // Check if section template exists
      const existingTemplate = await prisma.sectionTemplate.findFirst({
        where: { type: sectionData.type }
      });

      // For sections, always create if doesn't exist, skip if exists
      if (existingTemplate) {
        result.success = true;
        result.message = `Section template "${sectionData.name}" already exists, skipped`;
        return NextResponse.json(result);
      }

      // Create section template (only if doesn't exist)
      const templateData = {
        name: sectionData.name,
        type: sectionData.type,
        category: sectionData.category,
        description: sectionData.description,
        defaultData: JSON.stringify(sectionData.defaultData)
      };

      await prisma.sectionTemplate.create({
        data: templateData
      });

      result.imported.sections = 1;
      result.success = true;
      result.message = `Section template "${sectionData.name}" imported successfully`;
    }

    return NextResponse.json(result);
  } catch (error) {
    console.error('Import error:', error);
    result.errors.push('Database error: ' + (error as Error).message);
    result.message = 'Import failed';
    return NextResponse.json(result);
  }
}