/**
 * Import/Export Buttons Component
 * Author: generated by Amazon Q
 * Created: 2024-01-15
 */

'use client';

import { useState } from 'react';
import ImportExportModal from './ImportExportModal';
import { ImportResult } from '@/lib/import-export/types';

interface ImportExportButtonsProps {
  type: 'page' | 'section';
  data?: any;
  onImportSuccess?: (result: ImportResult) => void;
  className?: string;
}

export default function ImportExportButtons({
  type,
  data,
  onImportSuccess,
  className = ''
}: ImportExportButtonsProps) {
  const [modalState, setModalState] = useState<{
    isOpen: boolean;
    mode: 'import' | 'export';
  }>({ isOpen: false, mode: 'export' });

  const openModal = (mode: 'import' | 'export') => {
    setModalState({ isOpen: true, mode });
  };

  const closeModal = () => {
    setModalState({ isOpen: false, mode: 'export' });
  };

  return (
    <>
      <div className={`flex space-x-2 ${className}`}>
        <button
          onClick={() => openModal('export')}
          disabled={!data}
          className="flex items-center px-3 py-1.5 text-sm bg-blue-600 text-white rounded hover:bg-blue-700 disabled:opacity-50 disabled:cursor-not-allowed"
          title={`Export ${type}`}
        >
          <svg className="w-4 h-4 mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
          </svg>
          Export
        </button>
        
        <button
          onClick={() => openModal('import')}
          className="flex items-center px-3 py-1.5 text-sm bg-green-600 text-white rounded hover:bg-green-700"
          title={`Import ${type}`}
        >
          <svg className="w-4 h-4 mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M7 16a4 4 0 01-.88-7.903A5 5 0 1115.9 6L16 6a5 5 0 011 9.9M9 19l3 3m0 0l3-3m-3 3V10" />
          </svg>
          Import
        </button>
      </div>

      <ImportExportModal
        isOpen={modalState.isOpen}
        onClose={closeModal}
        mode={modalState.mode}
        type={type}
        data={data}
        onImportSuccess={onImportSuccess}
      />
    </>
  );
}