/**
 * Admin Panel Types
 * Author: generated by Amazon Q
 * Created: 2024-01-15
 */

export interface Page {
  id: string;
  slug: string;
  title: string;
  metaTitle?: string;
  metaDescription?: string;
  status: 'published' | 'draft';
  language: 'en' | 'ar' | 'tr' | 'fr' | 'de' | 'es' | 'fa';
  sections: PageSection[];
  createdAt: string;
  updatedAt: string;
}

export interface PageSection {
  id: string;
  type: SectionType;
  order: number;
  data: SectionData;
  settings: SectionSettings;
}

export type SectionType = 
  | 'hero'
  | 'features'
  | 'cta'
  | 'testimonials'
  | 'faq'
  | 'stats'
  | 'text-image'
  | 'tabs'
  | 'contact'
  | 'pricing';

export interface SectionData {
  title?: string;
  subtitle?: string;
  description?: string;
  image?: MediaFile;
  buttons?: Button[];
  items?: Record<string, unknown>[];
  content?: string;
  [key: string]: unknown;
}

export interface SectionSettings {
  backgroundColor?: string;
  textColor?: string;
  padding?: string;
  margin?: string;
  alignment?: 'left' | 'center' | 'right';
  animation?: string;
  customCSS?: string;
}

export interface Button {
  text: string;
  href: string;
  variant: 'primary' | 'secondary' | 'outline';
  size: 'sm' | 'md' | 'lg';
}

export interface MediaFile {
  id: string;
  filename: string;
  path: string;
  altText?: string;
  fileSize: number;
  mimeType: string;
  createdAt: string;
}

export interface SectionTemplate {
  id: string;
  name: string;
  type: SectionType;
  category: string;
  description: string;
  previewImage: string;
  defaultData: SectionData;
  defaultSettings: SectionSettings;
  usageCount: number;
}

export interface Translation {
  id: string;
  key: string;
  language: 'en' | 'ar' | 'tr' | 'fr' | 'de' | 'es' | 'fa';
  value: string;
  namespace?: string;
  createdAt: string;
  updatedAt: string;
}

export interface User {
  id: string;
  email: string;
  name: string;
  role: 'admin' | 'editor' | 'viewer';
  createdAt: string;
  lastLogin?: string;
}

export interface AdminSettings {
  siteName: string;
  siteDescription: string;
  defaultLanguage: 'en' | 'ar' | 'tr' | 'fr' | 'de' | 'es' | 'fa';
  enabledLanguages: ('en' | 'ar' | 'tr' | 'fr' | 'de' | 'es' | 'fa')[];
  seoSettings: {
    defaultMetaTitle: string;
    defaultMetaDescription: string;
    googleAnalyticsId?: string;
    googleTagManagerId?: string;
  };
  emailSettings: {
    fromEmail: string;
    fromName: string;
    smtpHost?: string;
    smtpPort?: number;
    smtpUser?: string;
    smtpPassword?: string;
  };
}