/**
 * API Route: Add Translation to Page
 * Author: generated by Amazon Q
 * Created: 2024-01-20
 */

import { NextRequest, NextResponse } from 'next/server';
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

export async function POST(
  request: NextRequest,
  { params }: { params: { id: string } }
) {
  const debugLogs: string[] = [];
  
  try {
    const { id } = params;
    const body = await request.json();
    const { language, slug, copyStructure = true, copyStyles = true, copyContent = false } = body;

    debugLogs.push(`Request: lang=${language}, slug=${slug}, copyStructure=${copyStructure}, copyStyles=${copyStyles}, copyContent=${copyContent}`);

    // Validation
    if (!language || !slug) {
      return NextResponse.json(
        { success: false, error: 'Language and slug are required', debugLogs },
        { status: 400 }
      );
    }

    // دریافت صفحه مبدا
    const sourcePage = await prisma.page.findUnique({
      where: { id },
      include: { pageGroup: true }
    });

    if (!sourcePage) {
      return NextResponse.json(
        { success: false, error: 'Source page not found', debugLogs },
        { status: 404 }
      );
    }

    debugLogs.push(`Source page found: ${sourcePage.title}`);
    debugLogs.push(`builderData type: ${typeof sourcePage.builderData}`);
    debugLogs.push(`builderData exists: ${!!sourcePage.builderData}`);
    if (sourcePage.builderData) {
      debugLogs.push(`builderData length: ${sourcePage.builderData.length}`);
    }

    // بررسی اینکه slug تکراری نباشد
    const existingPage = await prisma.page.findUnique({
      where: { slug }
    });

    if (existingPage) {
      return NextResponse.json(
        { success: false, error: 'Slug already exists', debugLogs },
        { status: 400 }
      );
    }

    // اگر صفحه مبدا گروه نداره، یک گروه براش بساز
    let pageGroupId = sourcePage.pageGroupId;
    
    if (!pageGroupId) {
      const slugWithoutLang = sourcePage.slug.replace(/^\/(en|ar|tr|fr|de|es)\//, '');
      const newGroup = await prisma.pageGroup.create({
        data: {
          name: sourcePage.title,
          slug: slugWithoutLang,
          defaultLanguage: sourcePage.language
        }
      });
      
      // اتصال صفحه مبدا به گروه جدید
      await prisma.page.update({
        where: { id: sourcePage.id },
        data: {
          pageGroupId: newGroup.id,
          isDefaultLang: true
        }
      });
      
      pageGroupId = newGroup.id;
    }

    // آماده کردن داده صفحه جدید
    const newPageData: any = {
      title: `${sourcePage.title} (${language.toUpperCase()})`,
      slug,
      language,
      status: 'draft',
      pageGroupId,
      isDefaultLang: false,
      isBuilderPage: sourcePage.isBuilderPage,
      builderVersion: sourcePage.builderVersion,
      metaTitle: sourcePage.metaTitle,
      metaDescription: sourcePage.metaDescription
    };

    // کپی کردن ساختار (sections)
    if (copyStructure && sourcePage.builderData) {
      try {
        const builderData = typeof sourcePage.builderData === 'string' 
          ? JSON.parse(sourcePage.builderData) 
          : sourcePage.builderData;
        
        debugLogs.push(`Parsed builderData successfully`);
        debugLogs.push(`builderData is array: ${Array.isArray(builderData)}`);
        debugLogs.push(`builderData has sections: ${!!builderData.sections}`);
        debugLogs.push(`builderData keys: ${Object.keys(builderData).join(', ')}`);
        
        // اگر builderData خودش یک آرایه است (نه {sections: []})
        let sections = Array.isArray(builderData) ? builderData : builderData.sections;
        
        if (sections && sections.length > 0) {
          debugLogs.push(`Source has ${sections.length} sections`);
          
          const newSections = sections.map((section: any) => {
            const newSection: any = {
              id: section.id,
              type: section.type,
              order: section.order,
              data: copyContent ? section.data : { ...section.data },
              style: copyStyles ? section.style : {}
            };

            // اگر copyContent فعال نیست، فقط فیلدهای متنی رو خالی کن
            if (!copyContent && newSection.data) {
              const textFields = ['title', 'subtitle', 'description', 'content', 'text', 'heading', 'subheading', 'label', 'buttonText', 'buttonLabel'];
              textFields.forEach(field => {
                if (newSection.data[field]) {
                  newSection.data[field] = '';
                }
              });
              
              // خالی کردن آرایههای متنی
              if (Array.isArray(newSection.data.items)) {
                newSection.data.items = newSection.data.items.map((item: any) => {
                  const newItem = { ...item };
                  textFields.forEach(field => {
                    if (newItem[field]) newItem[field] = '';
                  });
                  return newItem;
                });
              }
              if (Array.isArray(newSection.data.features)) {
                newSection.data.features = newSection.data.features.map((item: any) => {
                  const newItem = { ...item };
                  textFields.forEach(field => {
                    if (newItem[field]) newItem[field] = '';
                  });
                  return newItem;
                });
              }
            }

            return newSection;
          });
          
          // ذخیره به همون فرمتی که در دیتابیس هست
          newPageData.builderData = Array.isArray(builderData)
            ? JSON.stringify(newSections)
            : JSON.stringify({ sections: newSections });
          
          debugLogs.push(`Created ${newSections.length} sections for new page`);
          debugLogs.push(`First section: type=${newSections[0]?.type}, hasData=${!!newSections[0]?.data}`);
        } else {
          debugLogs.push(`WARNING: No sections found in builderData`);
        }
      } catch (error) {
        debugLogs.push(`ERROR parsing builderData: ${error}`);
        console.error('Error parsing builderData:', error);
      }
    } else {
      debugLogs.push(`Skipping structure copy: copyStructure=${copyStructure}, hasBuilderData=${!!sourcePage.builderData}`);
    }

    // ایجاد صفحه جدید
    debugLogs.push(`Creating new page with builderData length: ${newPageData.builderData?.length || 0}`);
    const newPage = await prisma.page.create({
      data: newPageData
    });
    debugLogs.push(`New page created with ID: ${newPage.id}`);

    return NextResponse.json({
      success: true,
      data: {
        page: newPage,
        message: 'Translation created successfully'
      },
      debugLogs
    });

  } catch (error) {
    console.error('Error creating translation:', error);
    debugLogs.push(`FATAL ERROR: ${error}`);
    return NextResponse.json(
      {
        success: false,
        error: 'Failed to create translation',
        message: error instanceof Error ? error.message : 'Unknown error',
        debugLogs
      },
      { status: 500 }
    );
  }
}
