/**
 * API Route: Add Translation to Page
 * Author: generated by Amazon Q
 * Created: 2024-01-20
 */

import { NextRequest, NextResponse } from 'next/server';
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

export async function POST(
  request: NextRequest,
  { params }: { params: { id: string } }
) {
  try {
    const { id } = params;
    const body = await request.json();
    const { language, slug, copyStructure = true, copyStyles = true, copyContent = false } = body;

    // Validation
    if (!language || !slug) {
      return NextResponse.json(
        { success: false, error: 'Language and slug are required' },
        { status: 400 }
      );
    }

    // دریافت صفحه مبدا
    const sourcePage = await prisma.page.findUnique({
      where: { id },
      include: { pageGroup: true }
    });

    if (!sourcePage) {
      return NextResponse.json(
        { success: false, error: 'Source page not found' },
        { status: 404 }
      );
    }

    // بررسی اینکه slug تکراری نباشد
    const existingPage = await prisma.page.findUnique({
      where: { slug }
    });

    if (existingPage) {
      return NextResponse.json(
        { success: false, error: 'Slug already exists' },
        { status: 400 }
      );
    }

    // اگر صفحه مبدا گروه نداره، یک گروه براش بساز
    let pageGroupId = sourcePage.pageGroupId;
    
    if (!pageGroupId) {
      const slugWithoutLang = sourcePage.slug.replace(/^\/(en|ar|tr|fr|de|es)\//, '');
      const newGroup = await prisma.pageGroup.create({
        data: {
          name: sourcePage.title,
          slug: slugWithoutLang,
          defaultLanguage: sourcePage.language
        }
      });
      
      // اتصال صفحه مبدا به گروه جدید
      await prisma.page.update({
        where: { id: sourcePage.id },
        data: {
          pageGroupId: newGroup.id,
          isDefaultLang: true
        }
      });
      
      pageGroupId = newGroup.id;
    }

    console.log('Creating translation:', { language, slug, sourcePageId: id });

    // آماده کردن داده صفحه جدید
    const newPageData: any = {
      title: `${sourcePage.title} (${language.toUpperCase()})`,
      slug,
      language,
      status: 'draft',
      pageGroupId,
      isDefaultLang: false,
      isBuilderPage: sourcePage.isBuilderPage,
      builderVersion: sourcePage.builderVersion,
      metaTitle: sourcePage.metaTitle,
      metaDescription: sourcePage.metaDescription
    };

    // کپی کردن ساختار (sections)
    if (copyStructure && sourcePage.builderData) {
      try {
        const builderData = JSON.parse(sourcePage.builderData);
        
        // کپی sections
        if (builderData.sections) {
          const newSections = builderData.sections.map((section: any) => ({
            id: section.id,
            type: section.type,
            order: section.order,
            data: copyContent ? section.data : {}, // اگر copyContent فعال باشد، محتوا را هم کپی کن
            style: copyStyles ? section.style : {}
          }));
          
          newPageData.builderData = JSON.stringify({
            sections: newSections
          });
        }
      } catch (error) {
        console.error('Error parsing builderData:', error);
      }
    }

    // ایجاد صفحه جدید
    console.log('Creating new page with data:', newPageData);
    const newPage = await prisma.page.create({
      data: newPageData
    });
    console.log('New page created:', newPage.id);

    return NextResponse.json({
      success: true,
      data: {
        page: newPage,
        message: 'Translation created successfully'
      }
    });

  } catch (error) {
    console.error('Error creating translation:', error);
    return NextResponse.json(
      {
        success: false,
        error: 'Failed to create translation',
        message: error instanceof Error ? error.message : 'Unknown error'
      },
      { status: 500 }
    );
  }
}
