/**
 * Button component with variants
 * Author: generated by Amazon Q
 * Created: 2024-01-15
 */

import React, { ButtonHTMLAttributes, forwardRef } from 'react';
import { cn } from '@/lib/utils';

interface ButtonProps extends ButtonHTMLAttributes<HTMLButtonElement> {
  variant?: 'primary' | 'secondary' | 'outline';
  size?: 'sm' | 'md' | 'lg';
  asChild?: boolean;
}

interface ButtonAsChildProps extends ButtonProps {
  asChild: true;
  children: React.ReactElement;
}

const Button = forwardRef<HTMLButtonElement, ButtonProps | ButtonAsChildProps>(
  ({ className, variant = 'primary', size = 'md', asChild, ...props }, ref) => {
    const baseClasses = cn(
      'inline-flex items-center justify-center rounded-md font-medium transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary-500 disabled:pointer-events-none disabled:opacity-50',
      {
        'bg-primary-600 text-white hover:bg-primary-700': variant === 'primary',
        'bg-secondary-100 text-secondary-900 hover:bg-secondary-200': variant === 'secondary',
        'border border-secondary-300 bg-transparent hover:bg-secondary-50': variant === 'outline',
      },
      {
        'h-8 px-3 text-sm': size === 'sm',
        'h-10 px-4': size === 'md',
        'h-12 px-6 text-lg': size === 'lg',
      },
      className
    );

    if (asChild && 'children' in props) {
      const child = props.children as React.ReactElement;
      return React.cloneElement(child, {
        className: cn(baseClasses, child.props.className),
        ref,
      });
    }

    return (
      <button
        className={baseClasses}
        ref={ref}
        {...(props as ButtonHTMLAttributes<HTMLButtonElement>)}
      />
    );
  }
);

Button.displayName = 'Button';

export { Button, type ButtonProps, type ButtonAsChildProps };