/**
 * Logo Component with Site Settings
 * Author: generated by Amazon Q
 * Created: 2024-12-20
 */

'use client';

import Link from 'next/link';
import { useSiteSettings } from '@/hooks/useSiteSettings';
import { ThemeLogo } from './ThemeLogo';

interface LogoProps {
  href?: string;
  className?: string;
  size?: 'sm' | 'md' | 'lg';
  /**
   * Forces the light or dark logo asset regardless of the site's current
   * dark/light theme — used by ModernNavbar's Header Settings, where the
   * floating vs. solid header state picks its own logo variant independent
   * of the visitor's theme preference.
   */
  forceVariant?: 'light' | 'dark';
  /** Renders this URL directly instead of the configured logo assets (Header Settings' `logoVariant: 'custom'`). */
  overrideUrl?: string;
}

export function Logo({ href = '/', className = '', size = 'md', forceVariant, overrideUrl }: LogoProps) {
  const { settings, isLoading } = useSiteSettings();

  const sizeClasses = {
    sm: 'max-h-6',
    md: 'max-h-10',
    lg: 'max-h-16'
  };

  const sizeMultiplier = {
    sm: 0.6,
    md: 1,
    lg: 1.6
  };

  if (isLoading) {
    return (
      <div className={`animate-pulse bg-gray-200 dark:bg-gray-700 rounded ${sizeClasses[size]} w-24 ${className}`} />
    );
  }

  const logoWidth = Math.round(settings.logo.width * sizeMultiplier[size]);
  const logoHeight = Math.round(settings.logo.height * sizeMultiplier[size]);

  // When a variant is forced, resolve to a single URL (with light<->dark fallback)
  // and feed it to ThemeLogo as both light/dark so it never flips with the theme.
  const forcedUrl = forceVariant
    ? (forceVariant === 'dark' ? settings.logo.darkUrl : settings.logo.lightUrl) ||
      (forceVariant === 'dark' ? settings.logo.lightUrl : settings.logo.darkUrl)
    : '';

  const hasAnyLogo = overrideUrl || forcedUrl || settings.logo.lightUrl || settings.logo.darkUrl;

  return (
    <Link
      href={href}
      className={`flex-shrink-0 ${className}`}
      aria-label={settings.logo.alt}
    >
      {overrideUrl ? (
        <img
          src={overrideUrl}
          alt={settings.logo.alt}
          width={logoWidth}
          height={logoHeight}
          className={`object-contain ${sizeClasses[size]}`}
          style={{ maxWidth: logoWidth, maxHeight: logoHeight }}
        />
      ) : hasAnyLogo ? (
        <ThemeLogo
          lightUrl={forceVariant ? forcedUrl : settings.logo.lightUrl}
          darkUrl={forceVariant ? forcedUrl : settings.logo.darkUrl}
          alt={settings.logo.alt}
          width={logoWidth}
          height={logoHeight}
          className={sizeClasses[size]}
        />
      ) : (
        <div className={`text-xl font-bold text-primary-600 dark:text-primary-400 ${
          size === 'sm' ? 'text-lg' : size === 'lg' ? 'text-2xl' : 'text-xl'
        }`}>
          {settings.logo.alt}
        </div>
      )}
    </Link>
  );
}