/**
 * Theme-aware Logo Component
 * Author: generated by Amazon Q
 * Created: 2024-12-20
 */

'use client';

import { useEffect, useState } from 'react';

interface ThemeLogoProps {
  lightUrl?: string;
  darkUrl?: string;
  alt?: string;
  width?: number;
  height?: number;
  className?: string;
}

export function ThemeLogo({ 
  lightUrl, 
  darkUrl, 
  alt = 'Logo', 
  width = 120, 
  height = 40,
  className = ''
}: ThemeLogoProps) {
  const [mounted, setMounted] = useState(false);
  const [currentUrl, setCurrentUrl] = useState('');
  const [isDark, setIsDark] = useState(false);

  useEffect(() => {
    setMounted(true);
  }, []);

  useEffect(() => {
    if (!mounted) return;
    
    const checkTheme = () => {
      const htmlElement = document.documentElement;
      const isDarkMode = htmlElement.classList.contains('dark');
      setIsDark(isDarkMode);
      
      const logoUrl = isDarkMode ? darkUrl : lightUrl;
      const fallbackUrl = isDarkMode ? lightUrl : darkUrl;
      const finalUrl = logoUrl || fallbackUrl;
      
      setCurrentUrl(finalUrl || '');
    };

    // Initial check
    checkTheme();

    // Watch for theme changes
    const observer = new MutationObserver((mutations) => {
      mutations.forEach((mutation) => {
        if (mutation.type === 'attributes' && mutation.attributeName === 'class') {
          checkTheme();
        }
      });
    });

    observer.observe(document.documentElement, {
      attributes: true,
      attributeFilter: ['class']
    });

    return () => observer.disconnect();
  }, [mounted, lightUrl, darkUrl]);

  // Don't render until mounted to avoid hydration mismatch
  if (!mounted) {
    return (
      <div 
        className={`bg-gray-200 animate-pulse ${className}`}
        style={{ width, height }}
      />
    );
  }

  if (!currentUrl) {
    return (
      <div 
        className={`bg-gray-200 dark:bg-gray-700 flex items-center justify-center text-gray-500 dark:text-gray-400 text-sm ${className}`}
        style={{ width, height }}
      >
        Logo
      </div>
    );
  }

  return (
    <img
      src={currentUrl}
      alt={alt}
      width={width}
      height={height}
      className={`object-contain ${className}`}
      style={{ maxWidth: width, maxHeight: height }}
    />
  );
}